({
L_CANCEL: "Annuller",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Oplysningen blev ikke fundet",
L_ERR_INVALIDDATE: "Ugyldig dato.",
L_FETCHING: "Henter poster. . .",
L_FETCHINGNEXT: "Henter n\u00e6ste side med poster. . .",
L_FETCHINGPREV: "Henter foreg\u00e5ende side med poster. . .",
L_JAWS_GIGABYTES: "%1 Gigabyte",
L_JAWS_KILOBYTES: "%1 Kilobytes",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Sorteret stigende",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 kolonne. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Sorteret faldende",
L_JAWS_LISTVIEW_NOENTRY: "ingen indgang valgt",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Tryk p\u00e5 Enter for at sortere igen stigende",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Tryk p\u00e5 Enter for at sortere igen faldende",
L_JAWS_LISTVIEW_UNDORESORT: "Tryk p\u00e5 Enter for at fortryde sorteringen",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 kolonne. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 af %3",
L_JAWS_MEGABYTES: "%1 Megabyte",
L_JAWS_TERABYTES: "%1 Terabyte",
L_NARROW_DEFAULT: "Sorter som standard",
L_NARROW_NOTITLE: "Ingen titel",
L_NARROW_SORTBY: "Sorter efter %1",
L_SEARCH: "S\u00f8g",
L_STARTSWITH_COLUMN: "V\u00e6lg den kolonne, der skal sorteres efter:",
L_STARTSWITH_INVALID_NUMBER: "Der er angivet ugyldigt tal",
L_STARTSWITH_SEARCH: "S\u00f8g efter oplysninger, der starter med:",
L_STARTSWITH_TITLE: "Starter med...",
L_UPDATINGVIEW_MESSAGE: "Denne oversigt bliver sandsynligvis opdateret p\u00e5 serveren.\nDen vises s\u00e5 snart denne opdatering er udf\u00f8rt.\nDu kan forts\u00e6tte med at arbejde med andre faner eller fors\u00f8ge at f\u00e5 adgang til andre oversigter/mapper.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "Nyt dokument ",
L_VIEWICONTIPS_ELM_10: "Huskeseddel ",
L_VIEWICONTIPS_ELM_100: "Bl\u00e5 rombe ",
L_VIEWICONTIPS_ELM_101: "R\u00f8d pil op ",
L_VIEWICONTIPS_ELM_102: "R\u00f8d pil ned ",
L_VIEWICONTIPS_ELM_103: "R\u00f8d venstre pil ",
L_VIEWICONTIPS_ELM_104: "R\u00f8d h\u00f8jre pil ",
L_VIEWICONTIPS_ELM_105: "Gr\u00f8n pil op",
L_VIEWICONTIPS_ELM_106: "Gr\u00f8n pil ned ",
L_VIEWICONTIPS_ELM_107: "Gr\u00f8n venstre pil ",
L_VIEWICONTIPS_ELM_108: "Gr\u00f8n h\u00f8jre pil ",
L_VIEWICONTIPS_ELM_109: "Bl\u00e5 pil op ",
L_VIEWICONTIPS_ELM_11: "Oplysninger ",
L_VIEWICONTIPS_ELM_110: "Bl\u00e5 pil ned ",
L_VIEWICONTIPS_ELM_111: "Bl\u00e5 venstre pil ",
L_VIEWICONTIPS_ELM_112: "Bl\u00e5 h\u00f8jre pil ",
L_VIEWICONTIPS_ELM_113: "Bl\u00e5t display ",
L_VIEWICONTIPS_ELM_114: "Gr\u00f8n bold ",
L_VIEWICONTIPS_ELM_115: "R\u00f8d bold ",
L_VIEWICONTIPS_ELM_116: "Brun bold ",
L_VIEWICONTIPS_ELM_117: "Bl\u00e5 bold ",
L_VIEWICONTIPS_ELM_118: "M\u00f8rkebl\u00e5 bold ",
L_VIEWICONTIPS_ELM_119: "Lilla bold ",
L_VIEWICONTIPS_ELM_12: "Skriv tekst ",
L_VIEWICONTIPS_ELM_120: "Gul bold ",
L_VIEWICONTIPS_ELM_121: "U\u00e5bnet hvid konvolut ",
L_VIEWICONTIPS_ELM_122: "Sendt besked ",
L_VIEWICONTIPS_ELM_123: "U\u00e5bnet bl\u00e5 konvolut ",
L_VIEWICONTIPS_ELM_124: "U\u00e5bnet r\u00f8d konvolut ",
L_VIEWICONTIPS_ELM_125: "\u00c5bnet hvid konvolut ",
L_VIEWICONTIPS_ELM_126: "\u00c5bnet gul konvolut ",
L_VIEWICONTIPS_ELM_127: "\u00c5bnet bl\u00e5 konvolut ",
L_VIEWICONTIPS_ELM_128: "R\u00f8d konvolutbagside ",
L_VIEWICONTIPS_ELM_129: "Hvid konvolutbagside ",
L_VIEWICONTIPS_ELM_13: "Grafik ",
L_VIEWICONTIPS_ELM_130: "Gul konvolutbagside ",
L_VIEWICONTIPS_ELM_131: "R\u00f8d konvolutbagside ",
L_VIEWICONTIPS_ELM_132: "Hvid invitation ",
L_VIEWICONTIPS_ELM_133: "Gul invitation ",
L_VIEWICONTIPS_ELM_134: "R\u00f8d invitation ",
L_VIEWICONTIPS_ELM_135: "Lotus 123 ",
L_VIEWICONTIPS_ELM_136: "Tekstbehandlingsdokument ",
L_VIEWICONTIPS_ELM_137: "Pr\u00e6sentation ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "Videokamera ",
L_VIEWICONTIPS_ELM_14: "Diagram ",
L_VIEWICONTIPS_ELM_140: "Workflow-dokument ",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_144: "Cirkeldiagram ",
L_VIEWICONTIPS_ELM_145: "Visio ",
L_VIEWICONTIPS_ELM_146: "Vinter ",
L_VIEWICONTIPS_ELM_147: "For\u00e5r ",
L_VIEWICONTIPS_ELM_148: "Sommer ",
L_VIEWICONTIPS_ELM_149: "Efter\u00e5r ",
L_VIEWICONTIPS_ELM_15: "Lyd ",
L_VIEWICONTIPS_ELM_150: "Udr\u00e5bstegn ",
L_VIEWICONTIPS_ELM_151: "Nummer 1 ",
L_VIEWICONTIPS_ELM_152: "Nummer 2 ",
L_VIEWICONTIPS_ELM_153: "Nummer 3 ",
L_VIEWICONTIPS_ELM_154: "Nummer 4 ",
L_VIEWICONTIPS_ELM_155: "Nummer 5 ",
L_VIEWICONTIPS_ELM_156: "Madlavning ",
L_VIEWICONTIPS_ELM_157: "Dokument uacceptabelt ",
L_VIEWICONTIPS_ELM_158: "M\u00f8de ",
L_VIEWICONTIPS_ELM_159: "Guldstjerne ",
L_VIEWICONTIPS_ELM_16: "Mikrofon ",
L_VIEWICONTIPS_ELM_160: "Aftale ",
L_VIEWICONTIPS_ELM_161: "Widget ",
L_VIEWICONTIPS_ELM_162: "Sp\u00f8rgsm\u00e5l ",
L_VIEWICONTIPS_ELM_163: "Fortroligt ",
L_VIEWICONTIPS_ELM_164: "Krypteret e-mail ",
L_VIEWICONTIPS_ELM_165: "Bl\u00e5 h\u00e6ngel\u00e5s ",
L_VIEWICONTIPS_ELM_166: "Skjult ",
L_VIEWICONTIPS_ELM_167: "Bl\u00e5 afkrydsning ",
L_VIEWICONTIPS_ELM_168: "Opgave ",
L_VIEWICONTIPS_ELM_169: "R\u00f8d medaljon ",
L_VIEWICONTIPS_ELM_17: "Grafik ",
L_VIEWICONTIPS_ELM_170: "Gul medaljon ",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Flyvemaskine ",
L_VIEWICONTIPS_ELM_174: "Bil ",
L_VIEWICONTIPS_ELM_175: "Bygning ",
L_VIEWICONTIPS_ELM_176: "Nyt dokument ",
L_VIEWICONTIPS_ELM_177: "Partyballon ",
L_VIEWICONTIPS_ELM_178: "Besvaret besked ",
L_VIEWICONTIPS_ELM_179: "Videresendt besked ",
L_VIEWICONTIPS_ELM_18: "Gr\u00f8nt display ",
L_VIEWICONTIPS_ELM_180: "Besvaret og videresendt besked ",
L_VIEWICONTIPS_ELM_181: "Opf\u00f8lgning med h\u00f8j prioritet.",
L_VIEWICONTIPS_ELM_182: "Opf\u00f8lgning med normal prioritet.",
L_VIEWICONTIPS_ELM_183: "Opf\u00f8lgning med lav prioritet.",
L_VIEWICONTIPS_ELM_184: "Kun sendt til mig ",
L_VIEWICONTIPS_ELM_185: "Sendt til mig og nogle f\u00e5 andre ",
L_VIEWICONTIPS_ELM_186: "Sendt til mig og mange andre ",
L_VIEWICONTIPS_ELM_187: "Ubehandlet m\u00f8deindkaldelse ",
L_VIEWICONTIPS_ELM_188: "Ul\u00e6st besked ",
L_VIEWICONTIPS_ELM_189: "Online m\u00f8de ",
L_VIEWICONTIPS_ELM_19: "Tabel ",
L_VIEWICONTIPS_ELM_190: "H\u00f8j relevans ",
L_VIEWICONTIPS_ELM_191: "Medium relevans ",
L_VIEWICONTIPS_ELM_192: "Lav relevans ",
L_VIEWICONTIPS_ELM_193: "Ikke relevant ",
L_VIEWICONTIPS_ELM_194: "Heldagsaktivitet ",
L_VIEWICONTIPS_ELM_195: "Huskeseddel ",
L_VIEWICONTIPS_ELM_196: "Tidsplan \u00e6ndret ",
L_VIEWICONTIPS_ELM_197: "Afvis invitation ",
L_VIEWICONTIPS_ELM_198: "Invitation med modforslag ",
L_VIEWICONTIPS_ELM_199: "M\u00e6rkedag ",
L_VIEWICONTIPS_ELM_2: "U\u00e5bnet mappe ",
L_VIEWICONTIPS_ELM_20: "Tekst ",
L_VIEWICONTIPS_ELM_200: "Annulleret m\u00f8de ",
L_VIEWICONTIPS_ELM_201: "Udf\u00f8rt opgave ",
L_VIEWICONTIPS_ELM_202: "Accepteret ",
L_VIEWICONTIPS_ELM_203: "Afvist ",
L_VIEWICONTIPS_ELM_204: "H\u00f8j prioritet ",
L_VIEWICONTIPS_ELM_205: "Aftale ",
L_VIEWICONTIPS_ELM_206: "Privat invitation ",
L_VIEWICONTIPS_ELM_207: "Joke-ikon ",
L_VIEWICONTIPS_ELM_208: "Fortroligt-ikon ",
L_VIEWICONTIPS_ELM_209: "Personligt-ikon ",
L_VIEWICONTIPS_ELM_21: "Flere dokumenter ",
L_VIEWICONTIPS_ELM_210: "Accepteret invitation ",
L_VIEWICONTIPS_ELM_211: "L\u00e6st besked ",
L_VIEWICONTIPS_ELM_212: "Ny invitation ",
L_VIEWICONTIPS_ELM_22: "To dokumenter ",
L_VIEWICONTIPS_ELM_23: "Nyheder ",
L_VIEWICONTIPS_ELM_24: "R\u00f8d bog ",
L_VIEWICONTIPS_ELM_25: "Adressebog ",
L_VIEWICONTIPS_ELM_26: "\u00c5ben bog ",
L_VIEWICONTIPS_ELM_27: "Lukket bog ",
L_VIEWICONTIPS_ELM_28: "Hvis bog ",
L_VIEWICONTIPS_ELM_29: "Opsplittet gul side ",
L_VIEWICONTIPS_ELM_3: "Person ",
L_VIEWICONTIPS_ELM_30: "Opsplittet bl\u00e5 side ",
L_VIEWICONTIPS_ELM_31: "T\u00e6ndt lysp\u00e6re ",
L_VIEWICONTIPS_ELM_32: "Slukket lysp\u00e6re ",
L_VIEWICONTIPS_ELM_33: "Opdater ",
L_VIEWICONTIPS_ELM_34: "S\u00f8g i dokument ",
L_VIEWICONTIPS_ELM_35: "S\u00f8gning i dokument udf\u00f8rt ",
L_VIEWICONTIPS_ELM_36: "Dokument acceptabelt ",
L_VIEWICONTIPS_ELM_37: "Dokument f\u00e6rdigt ",
L_VIEWICONTIPS_ELM_38: "Dokumentproblem ",
L_VIEWICONTIPS_ELM_39: "Dokumentsp\u00f8rgsm\u00e5l ",
L_VIEWICONTIPS_ELM_4: "Gruppe ",
L_VIEWICONTIPS_ELM_40: "Dokumentadvarsel ",
L_VIEWICONTIPS_ELM_41: "Dokument gult ",
L_VIEWICONTIPS_ELM_42: "Svar gult dokument ",
L_VIEWICONTIPS_ELM_43: "Svar bl\u00e5t dokument ",
L_VIEWICONTIPS_ELM_44: "Telefon ",
L_VIEWICONTIPS_ELM_45: "Aktiv telefon ",
L_VIEWICONTIPS_ELM_46: "Computerterminal ",
L_VIEWICONTIPS_ELM_47: "Fax ",
L_VIEWICONTIPS_ELM_48: "CD-ROM ",
L_VIEWICONTIPS_ELM_49: "Floppy disk ",
L_VIEWICONTIPS_ELM_5: "Bilag ",
L_VIEWICONTIPS_ELM_50: "Diskette ",
L_VIEWICONTIPS_ELM_51: "Harddisk ",
L_VIEWICONTIPS_ELM_52: "Netv\u00e6rk ",
L_VIEWICONTIPS_ELM_53: "Computer ",
L_VIEWICONTIPS_ELM_54: "Server ",
L_VIEWICONTIPS_ELM_55: "Forbindelse ",
L_VIEWICONTIPS_ELM_56: "Find ",
L_VIEWICONTIPS_ELM_57: "Skriv ",
L_VIEWICONTIPS_ELM_58: "Kladde ",
L_VIEWICONTIPS_ELM_59: "Valuta ",
L_VIEWICONTIPS_ELM_6: "Sammenflettet ",
L_VIEWICONTIPS_ELM_60: "M\u00f8nter ",
L_VIEWICONTIPS_ELM_61: "N\u00f8gle ",
L_VIEWICONTIPS_ELM_62: "H\u00e6ngel\u00e5s ",
L_VIEWICONTIPS_ELM_63: "Kalender ",
L_VIEWICONTIPS_ELM_64: "Ur ",
L_VIEWICONTIPS_ELM_65: "Alarm ",
L_VIEWICONTIPS_ELM_66: "Flyvning ",
L_VIEWICONTIPS_ELM_67: "Satellit ",
L_VIEWICONTIPS_ELM_68: "Dokumentmappe ",
L_VIEWICONTIPS_ELM_69: "Hjem ",
L_VIEWICONTIPS_ELM_7: "Dyr ",
L_VIEWICONTIPS_ELM_70: "Globus ",
L_VIEWICONTIPS_ELM_71: "Helbred ",
L_VIEWICONTIPS_ELM_72: "\u00d8konomi ",
L_VIEWICONTIPS_ELM_73: "Transport ",
L_VIEWICONTIPS_ELM_74: "Kemikalie ",
L_VIEWICONTIPS_ELM_75: "Fremstilling ",
L_VIEWICONTIPS_ELM_76: "Hj\u00e6lpemidler ",
L_VIEWICONTIPS_ELM_77: "Telekommunikation ",
L_VIEWICONTIPS_ELM_78: "Konstruktion ",
L_VIEWICONTIPS_ELM_79: "Timeglas ",
L_VIEWICONTIPS_ELM_8: "S\u00f8g ",
L_VIEWICONTIPS_ELM_80: "Forbudt ",
L_VIEWICONTIPS_ELM_81: "Afvist ",
L_VIEWICONTIPS_ELM_82: "Fuldf\u00f8rt ",
L_VIEWICONTIPS_ELM_83: "Acceptabel ",
L_VIEWICONTIPS_ELM_84: "Uacceptabel ",
L_VIEWICONTIPS_ELM_85: "Glad ",
L_VIEWICONTIPS_ELM_86: "Ligeglad ",
L_VIEWICONTIPS_ELM_87: "Ked af det ",
L_VIEWICONTIPS_ELM_88: "Lunken ",
L_VIEWICONTIPS_ELM_89: "Varm ",
L_VIEWICONTIPS_ELM_9: "Netv\u00e6rksaktivitet",
L_VIEWICONTIPS_ELM_90: "Meget varm ",
L_VIEWICONTIPS_ELM_91: "Bombe ",
L_VIEWICONTIPS_ELM_92: "Stopskilt ",
L_VIEWICONTIPS_ELM_93: "Stop ",
L_VIEWICONTIPS_ELM_94: "Advarsel ",
L_VIEWICONTIPS_ELM_95: "G\u00e5 ",
L_VIEWICONTIPS_ELM_96: "Positiv ",
L_VIEWICONTIPS_ELM_97: "Negativ ",
L_VIEWICONTIPS_ELM_98: "R\u00f8d rombe ",
L_VIEWICONTIPS_ELM_99: "Gr\u00f8n rombe ",
L_VIEWMAIL: "E-mail"
})
