({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "FM",
L_CAL_LAST_DAY: "Dag %1 - sista dagen p\u00e5 \u00e5ret",
L_CAL_LAST_MONTH: "M\u00e5nad %1 - sista m\u00e5naden p\u00e5 \u00e5ret",
L_CAL_LAST_WEEK: "Vecka %1 - sista veckan p\u00e5 \u00e5ret",
L_CAL_LEFT_DAY: "Dag %1 - %2 dag kvar p\u00e5 \u00e5ret",
L_CAL_LEFT_DAYS: "Dag %1 - %2 dagar kvar p\u00e5 \u00e5ret",
L_CAL_LEFT_MONTH: "M\u00e5nad %1 - %2 m\u00e5nad kvar p\u00e5 \u00e5ret",
L_CAL_LEFT_MONTHS: "M\u00e5nad %1 - %2 m\u00e5nader kvar p\u00e5 \u00e5ret",
L_CAL_LEFT_WEEK: "Vecka %1 - %2 vecka kvar p\u00e5 \u00e5ret",
L_CAL_LEFT_WEEKS: "Vecka %1 - %2 veckor kvar p\u00e5 \u00e5ret",
L_CHARDAY_FRI: "F",
L_CHARDAY_MON: "M",
L_CHARDAY_SAT: "L",
L_CHARDAY_SUN: "S",
L_CHARDAY_THU: "T",
L_CHARDAY_TUE: "T",
L_CHARDAY_WED: "O",
L_NO_CAL_ENTRY_SELECTED: "Ingen kalenderuppgift var vald.  V\u00e4lj en uppgift och f\u00f6rs\u00f6k igen.",
L_PM_SUFFIX: "EM",
L_SIDECALENDAR_NOENTRY: "Det finns inga kalenderuppgifter f\u00f6r %1."
})
