({
L_CAL_NAV_PREVIOUS: "F\u00f6reg\u00e5ende",
L_CAL_NAV_NEXT: "N\u00e4sta",
L_CAL_NAV_MONTH: "M\u00e5nad",
L_CAL_HEADER_DAYS_WEEK: "Veckodagar",
L_CAL_HEADER: "Kalenderrubrik",
L_CAL_HEADER_DAY: "Dagrubrik %1",
L_CAL_EVENT_ALLDAY: "Heldagsh\u00e4ndelse %1",
L_CAL_NOENTRY: "Inga poster",
L_CAL_GRID: "Kalenderrutn\u00e4t",
L_CAL_PICKER_POPUP: "Datumv\u00e4ljarruta",
L_CAL_NAV_TIMESCALE_PREV_D: "F\u00f6reg\u00e5ende dag",
L_CAL_NAV_TIMESCALE_NEXT_D: "N\u00e4sta dag",
L_CAL_NAV_TIMESCALE_PREV_T: "F\u00f6reg\u00e5ende tv\u00e5 dagar",
L_CAL_NAV_TIMESCALE_NEXT_T: "N\u00e4sta tv\u00e5 dagar",
L_CAL_NAV_TIMESCALE_PREV_F: "F\u00f6reg\u00e5ende arbetsvecka",
L_CAL_NAV_TIMESCALE_NEXT_F: "N\u00e4sta arbetsvecka",
L_CAL_NAV_TIMESCALE_PREV_W: "F\u00f6reg\u00e5ende vecka",
L_CAL_NAV_TIMESCALE_NEXT_W: "N\u00e4sta vecka",
L_CAL_NAV_TIMESCALE_PREV_2: "F\u00f6reg\u00e5ende tv\u00e5 veckor",
L_CAL_NAV_TIMESCALE_NEXT_2: "N\u00e4sta tv\u00e5 veckor",
L_CAL_NAV_TIMESCALE_PREV_M: "F\u00f6reg\u00e5ende m\u00e5nad",
L_CAL_NAV_TIMESCALE_NEXT_M: "N\u00e4sta m\u00e5nad",
L_CAL_NAV_TIMESCALE_PREV_Y: "F\u00f6reg\u00e5ende \u00e5r",
L_CAL_NAV_TIMESCALE_NEXT_Y: "N\u00e4sta \u00e5r"
})
