({
L_CANCEL: "Cancelar",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Entrada n\u00e3o encontrada",
L_ERR_INVALIDDATE: "A data especificada n\u00e3o \u00e9 v\u00e1lida.",
L_FETCHING: "A obter registos. . .",
L_FETCHINGNEXT: "A obter a p\u00e1gina de registos seguinte . . .",
L_FETCHINGPREV: "A obter a p\u00e1gina de registos anterior . . .",
L_JAWS_GIGABYTES: "%1 Gigabytes",
L_JAWS_KILOBYTES: "%1 Kilobytes",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Ordena\u00e7\u00e3o ascendente",
L_JAWS_LISTVIEW_COLUMN: "Coluna %1 %2. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Ordena\u00e7\u00e3o descendente",
L_JAWS_LISTVIEW_NOENTRY: "nenhuma entrada encontrada",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Prima a tecla Enter para reordenar no sentido ascendente",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Prima a tecla Enter para reordenar no sentido descendente",
L_JAWS_LISTVIEW_UNDORESORT: "Prima a tecla Enter para anular a ordena\u00e7\u00e3o",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "Coluna %1. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 de %3",
L_JAWS_MEGABYTES: "%1 Megabytes",
L_JAWS_TERABYTES: "%1 Terabytes",
L_NARROW_DEFAULT: "Ordena\u00e7\u00e3o predefinida",
L_NARROW_NOTITLE: "Sem t\u00edtulo",
L_NARROW_SORTBY: "Ordenar por %1",
L_SEARCH: "Procurar",
L_STARTSWITH_COLUMN: "Seleccionar a coluna para ordenar por:",
L_STARTSWITH_INVALID_NUMBER: "N\u00famero n\u00e3o v\u00e1lido especificado",
L_STARTSWITH_SEARCH: "Procurar entradas que come\u00e7am por:",
L_STARTSWITH_TITLE: "Come\u00e7a por...",
L_UPDATINGVIEW_MESSAGE: "\u00c9 prov\u00e1vel que esta vista esteja a ser actualizada no servidor.\nSer\u00e1 apresentada logo que a actualiza\u00e7\u00e3o esteja conclu\u00edda.\nPode continuar a trabalhar com outros separadores ou pode tentar aceder a outras vistas/pastas.",
L_VIEWICONTIPS_ELM_0: ",",
L_VIEWICONTIPS_ELM_1: ",",
L_VIEWICONTIPS_ELM_10: ",",
L_VIEWICONTIPS_ELM_100: ",",
L_VIEWICONTIPS_ELM_101: ",",
L_VIEWICONTIPS_ELM_102: ",",
L_VIEWICONTIPS_ELM_103: ",",
L_VIEWICONTIPS_ELM_104: ",",
L_VIEWICONTIPS_ELM_105: ",",
L_VIEWICONTIPS_ELM_106: ",",
L_VIEWICONTIPS_ELM_107: ",",
L_VIEWICONTIPS_ELM_108: ",",
L_VIEWICONTIPS_ELM_109: ",",
L_VIEWICONTIPS_ELM_11: ",",
L_VIEWICONTIPS_ELM_110: ",",
L_VIEWICONTIPS_ELM_111: ",",
L_VIEWICONTIPS_ELM_112: ",",
L_VIEWICONTIPS_ELM_113: ",",
L_VIEWICONTIPS_ELM_114: ",",
L_VIEWICONTIPS_ELM_115: ",",
L_VIEWICONTIPS_ELM_116: "Bola amarela ",
L_VIEWICONTIPS_ELM_117: "Envelope branco fechado ",
L_VIEWICONTIPS_ELM_118: "Mensagem enviada ",
L_VIEWICONTIPS_ELM_119: "Envelope azul fechado ",
L_VIEWICONTIPS_ELM_12: ",",
L_VIEWICONTIPS_ELM_120: "Envelope vermelho fechado ",
L_VIEWICONTIPS_ELM_121: "Envelope branco fechado ",
L_VIEWICONTIPS_ELM_122: "Envelope amarelo aberto ",
L_VIEWICONTIPS_ELM_123: "Envelope azul aberto ",
L_VIEWICONTIPS_ELM_124: "Parte de tr\u00e1s de envelope vermelho ",
L_VIEWICONTIPS_ELM_125: "Parte de tr\u00e1s de envelope branco ",
L_VIEWICONTIPS_ELM_126: "Parte de tr\u00e1s de envelope amarelo ",
L_VIEWICONTIPS_ELM_127: "Parte de tr\u00e1s de envelope vermelho ",
L_VIEWICONTIPS_ELM_128: "Convite branco ",
L_VIEWICONTIPS_ELM_129: "Convite amarelo ",
L_VIEWICONTIPS_ELM_13: ",",
L_VIEWICONTIPS_ELM_130: "Convite vermelho ",
L_VIEWICONTIPS_ELM_131: "Lotus 123 ",
L_VIEWICONTIPS_ELM_132: "Documento de processamento de texto ",
L_VIEWICONTIPS_ELM_133: "Apresenta\u00e7\u00e3o ",
L_VIEWICONTIPS_ELM_134: "Lotus Approach ",
L_VIEWICONTIPS_ELM_135: "C\u00e2mara de v\u00eddeo ",
L_VIEWICONTIPS_ELM_136: "Documento de fluxo de trabalho ",
L_VIEWICONTIPS_ELM_137: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_138: "Microsoft Word ",
L_VIEWICONTIPS_ELM_139: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_14: ",",
L_VIEWICONTIPS_ELM_140: "Gr\u00e1fico circular ",
L_VIEWICONTIPS_ELM_141: "Visio ",
L_VIEWICONTIPS_ELM_142: "Inverno ",
L_VIEWICONTIPS_ELM_143: "Primavera ",
L_VIEWICONTIPS_ELM_144: "Ver\u00e3o ",
L_VIEWICONTIPS_ELM_145: "Outono ",
L_VIEWICONTIPS_ELM_146: "Ponto de exclama\u00e7\u00e3o ",
L_VIEWICONTIPS_ELM_147: "N\u00famero 1 ",
L_VIEWICONTIPS_ELM_148: "N\u00famero 2 ",
L_VIEWICONTIPS_ELM_149: "N\u00famero 3 ",
L_VIEWICONTIPS_ELM_15: ",",
L_VIEWICONTIPS_ELM_150: "N\u00famero 4 ",
L_VIEWICONTIPS_ELM_151: "N\u00famero 5 ",
L_VIEWICONTIPS_ELM_152: "Cozinhar ",
L_VIEWICONTIPS_ELM_153: "Documento inaceit\u00e1vel ",
L_VIEWICONTIPS_ELM_154: "Reuni\u00e3o ",
L_VIEWICONTIPS_ELM_155: "Estrela dourada ",
L_VIEWICONTIPS_ELM_156: "Compromisso ",
L_VIEWICONTIPS_ELM_157: "Mecanismo ",
L_VIEWICONTIPS_ELM_158: "Quest\u00e3o ",
L_VIEWICONTIPS_ELM_159: "Confidencial ",
L_VIEWICONTIPS_ELM_16: ",",
L_VIEWICONTIPS_ELM_160: "Correio encriptado ",
L_VIEWICONTIPS_ELM_161: "Cadeado azul ",
L_VIEWICONTIPS_ELM_162: "Disfar\u00e7ado ",
L_VIEWICONTIPS_ELM_163: "Marca de verifica\u00e7\u00e3o azul ",
L_VIEWICONTIPS_ELM_164: "Tarefa ",
L_VIEWICONTIPS_ELM_165: "Medalh\u00e3o vermelho ",
L_VIEWICONTIPS_ELM_166: "Medalh\u00e3o amarelo ",
L_VIEWICONTIPS_ELM_167: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_168: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_169: "Avi\u00e3o ",
L_VIEWICONTIPS_ELM_17: ",",
L_VIEWICONTIPS_ELM_170: "Carro ",
L_VIEWICONTIPS_ELM_171: "Edif\u00edcio ",
L_VIEWICONTIPS_ELM_172: "Novo documento ",
L_VIEWICONTIPS_ELM_173: "Bal\u00e3o de festa ",
L_VIEWICONTIPS_ELM_174: "Mensagem respondida a ",
L_VIEWICONTIPS_ELM_175: "Mensagem reencaminhada ",
L_VIEWICONTIPS_ELM_176: "Mensagem respondida e reencaminhada ",
L_VIEWICONTIPS_ELM_177: "Acompanhamento de prioridade alta.",
L_VIEWICONTIPS_ELM_178: "Acompanhamento de prioridade normal.",
L_VIEWICONTIPS_ELM_179: "Acompanhamento de prioridade baixa.",
L_VIEWICONTIPS_ELM_18: ",",
L_VIEWICONTIPS_ELM_180: "Enviada apenas para mim ",
L_VIEWICONTIPS_ELM_181: "Enviada para mim e para algumas pessoas ",
L_VIEWICONTIPS_ELM_182: "Enviada para mim e para muitas pessoas ",
L_VIEWICONTIPS_ELM_183: "Aviso de reuni\u00e3o n\u00e3o processado ",
L_VIEWICONTIPS_ELM_184: "Mensagem por ler",
L_VIEWICONTIPS_ELM_185: "Reuni\u00e3o online ",
L_VIEWICONTIPS_ELM_186: "Import\u00e2ncia elevada ",
L_VIEWICONTIPS_ELM_187: "Import\u00e2ncia m\u00e9dia ",
L_VIEWICONTIPS_ELM_188: "Import\u00e2ncia reduzida ",
L_VIEWICONTIPS_ELM_189: "Sem import\u00e2ncia ",
L_VIEWICONTIPS_ELM_19: ",",
L_VIEWICONTIPS_ELM_190: "Evento para todo o dia ",
L_VIEWICONTIPS_ELM_191: "Lembrete ",
L_VIEWICONTIPS_ELM_192: "Reagendada ",
L_VIEWICONTIPS_ELM_193: "Convite recusado ",
L_VIEWICONTIPS_ELM_194: "Contraproposta de convite ",
L_VIEWICONTIPS_ELM_195: "Anivers\u00e1rio ",
L_VIEWICONTIPS_ELM_196: "Reuni\u00e3o cancelada ",
L_VIEWICONTIPS_ELM_197: "Tarefa conclu\u00edda ",
L_VIEWICONTIPS_ELM_198: "Aceite ",
L_VIEWICONTIPS_ELM_199: "Recusado ",
L_VIEWICONTIPS_ELM_2: ",",
L_VIEWICONTIPS_ELM_20: ",",
L_VIEWICONTIPS_ELM_200: "Prioridade alta ",
L_VIEWICONTIPS_ELM_201: "Compromisso ",
L_VIEWICONTIPS_ELM_202: "Convite particular ",
L_VIEWICONTIPS_ELM_203: "\u00cdcone expressivo de piada ",
L_VIEWICONTIPS_ELM_204: "\u00cdcone expressivo confidencial ",
L_VIEWICONTIPS_ELM_205: "\u00cdcone expressivo pessoal",
L_VIEWICONTIPS_ELM_206: "Convite aceite ",
L_VIEWICONTIPS_ELM_207: "Mensagem lida ",
L_VIEWICONTIPS_ELM_208: "Novo convite ",
L_VIEWICONTIPS_ELM_21: ",",
L_VIEWICONTIPS_ELM_22: ",",
L_VIEWICONTIPS_ELM_23: ",",
L_VIEWICONTIPS_ELM_24: ",",
L_VIEWICONTIPS_ELM_25: ",",
L_VIEWICONTIPS_ELM_26: ",",
L_VIEWICONTIPS_ELM_27: ",",
L_VIEWICONTIPS_ELM_28: ",",
L_VIEWICONTIPS_ELM_29: ",",
L_VIEWICONTIPS_ELM_3: ",",
L_VIEWICONTIPS_ELM_30: ",",
L_VIEWICONTIPS_ELM_31: ",",
L_VIEWICONTIPS_ELM_32: ",",
L_VIEWICONTIPS_ELM_33: ",",
L_VIEWICONTIPS_ELM_34: ",",
L_VIEWICONTIPS_ELM_35: ",",
L_VIEWICONTIPS_ELM_36: ",",
L_VIEWICONTIPS_ELM_37: ",",
L_VIEWICONTIPS_ELM_38: ",",
L_VIEWICONTIPS_ELM_39: ",",
L_VIEWICONTIPS_ELM_4: ",",
L_VIEWICONTIPS_ELM_40: ",",
L_VIEWICONTIPS_ELM_41: ",",
L_VIEWICONTIPS_ELM_42: ",",
L_VIEWICONTIPS_ELM_43: ",",
L_VIEWICONTIPS_ELM_44: ",",
L_VIEWICONTIPS_ELM_45: ",",
L_VIEWICONTIPS_ELM_46: ",",
L_VIEWICONTIPS_ELM_47: ",",
L_VIEWICONTIPS_ELM_48: ",",
L_VIEWICONTIPS_ELM_49: ",",
L_VIEWICONTIPS_ELM_5: ",",
L_VIEWICONTIPS_ELM_50: ",",
L_VIEWICONTIPS_ELM_51: ",",
L_VIEWICONTIPS_ELM_52: ",",
L_VIEWICONTIPS_ELM_53: ",",
L_VIEWICONTIPS_ELM_54: ",",
L_VIEWICONTIPS_ELM_55: ",",
L_VIEWICONTIPS_ELM_56: ",",
L_VIEWICONTIPS_ELM_57: ",",
L_VIEWICONTIPS_ELM_58: ",",
L_VIEWICONTIPS_ELM_59: ",",
L_VIEWICONTIPS_ELM_6: ",",
L_VIEWICONTIPS_ELM_60: ",",
L_VIEWICONTIPS_ELM_61: ",",
L_VIEWICONTIPS_ELM_62: ",",
L_VIEWICONTIPS_ELM_63: ",",
L_VIEWICONTIPS_ELM_64: ",",
L_VIEWICONTIPS_ELM_65: ",",
L_VIEWICONTIPS_ELM_66: ",",
L_VIEWICONTIPS_ELM_67: ",",
L_VIEWICONTIPS_ELM_68: ",",
L_VIEWICONTIPS_ELM_69: ",",
L_VIEWICONTIPS_ELM_7: ",",
L_VIEWICONTIPS_ELM_70: ",",
L_VIEWICONTIPS_ELM_71: ",",
L_VIEWICONTIPS_ELM_72: ",",
L_VIEWICONTIPS_ELM_73: ",",
L_VIEWICONTIPS_ELM_74: ",",
L_VIEWICONTIPS_ELM_75: ",",
L_VIEWICONTIPS_ELM_76: ",",
L_VIEWICONTIPS_ELM_77: ",",
L_VIEWICONTIPS_ELM_78: ",",
L_VIEWICONTIPS_ELM_79: ",",
L_VIEWICONTIPS_ELM_8: ",",
L_VIEWICONTIPS_ELM_80: ",",
L_VIEWICONTIPS_ELM_81: ",",
L_VIEWICONTIPS_ELM_82: ",",
L_VIEWICONTIPS_ELM_83: ",",
L_VIEWICONTIPS_ELM_84: ",",
L_VIEWICONTIPS_ELM_85: ",",
L_VIEWICONTIPS_ELM_86: ",",
L_VIEWICONTIPS_ELM_87: ",",
L_VIEWICONTIPS_ELM_88: ",",
L_VIEWICONTIPS_ELM_89: ",",
L_VIEWICONTIPS_ELM_9: ",",
L_VIEWICONTIPS_ELM_90: ",",
L_VIEWICONTIPS_ELM_91: ",",
L_VIEWICONTIPS_ELM_92: ",",
L_VIEWICONTIPS_ELM_93: ",",
L_VIEWICONTIPS_ELM_94: ",",
L_VIEWICONTIPS_ELM_95: ",",
L_VIEWICONTIPS_ELM_96: ",",
L_VIEWICONTIPS_ELM_97: ",",
L_VIEWICONTIPS_ELM_98: ",",
L_VIEWICONTIPS_ELM_99: ",",
L_VIEWMAIL: "Correio"
})
