({
L_CAL_NAV_PREVIOUS: "Wstecz",
L_CAL_NAV_NEXT: "Dalej",
L_CAL_NAV_MONTH: "Miesi\u0105c",
L_CAL_HEADER_DAYS_WEEK: "Dni tygodnia",
L_CAL_HEADER: "Nag\u0142\u00f3wek kalendarza",
L_CAL_HEADER_DAY: "Nag\u0142\u00f3wek dnia %1",
L_CAL_EVENT_ALLDAY: "Zdarzenie ca\u0142odniowe %1",
L_CAL_NOENTRY: "Brak pozycji",
L_CAL_GRID: "Siatka kalendarza",
L_CAL_PICKER_POPUP: "Element wywo\u0142ywany narz\u0119dzia wyboru daty",
L_CAL_NAV_TIMESCALE_PREV_D: "Poprzedni dzie\u0144",
L_CAL_NAV_TIMESCALE_NEXT_D: "Nast\u0119pny dzie\u0144",
L_CAL_NAV_TIMESCALE_PREV_T: "Poprzednie 2 dni",
L_CAL_NAV_TIMESCALE_NEXT_T: "Nast\u0119pne two dni",
L_CAL_NAV_TIMESCALE_PREV_F: "Poprzedni tydzie\u0144 roboczy",
L_CAL_NAV_TIMESCALE_NEXT_F: "Nast\u0119pny tydzie\u0144 roboczy",
L_CAL_NAV_TIMESCALE_PREV_W: "Poprzedni tydzie\u0144",
L_CAL_NAV_TIMESCALE_NEXT_W: "Nast\u0119pny tydzie\u0144",
L_CAL_NAV_TIMESCALE_PREV_2: "Poprzednie 2 tygodnie",
L_CAL_NAV_TIMESCALE_NEXT_2: "Nast\u0119pne 2 tygodnie",
L_CAL_NAV_TIMESCALE_PREV_M: "Poprzedni miesi\u0105c",
L_CAL_NAV_TIMESCALE_NEXT_M: "Nast\u0119pny miesi\u0105c",
L_CAL_NAV_TIMESCALE_PREV_Y: "Poprzedni rok",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Nast\u0119pny rok"
})
