({
L_CAL_NAV_PREVIOUS: "Anterior",
L_CAL_NAV_NEXT: "Siguiente",
L_CAL_NAV_MONTH: "4Mes",
L_CAL_HEADER_DAYS_WEEK: "D\u00edas de la semana",
L_CAL_HEADER: "Cabecera de agenda",
L_CAL_HEADER_DAY: "Cabecera de d\u00eda %1",
L_CAL_EVENT_ALLDAY: "Evento de todo el d\u00eda %1",
L_CAL_NOENTRY: "Sin entradas",
L_CAL_GRID: "Cuadr\u00edcula de agenda",
L_CAL_PICKER_POPUP: "Ventana emergente de selector de fechas",
L_CAL_NAV_TIMESCALE_PREV_D: "El d\u00eda anterior",
L_CAL_NAV_TIMESCALE_NEXT_D: "El d\u00eda siguiente",
L_CAL_NAV_TIMESCALE_PREV_T: "Los dos d\u00edas anteriores",
L_CAL_NAV_TIMESCALE_NEXT_T: "Los dos d\u00edas siguientes",
L_CAL_NAV_TIMESCALE_PREV_F: "La semana de trabajo anterior",
L_CAL_NAV_TIMESCALE_NEXT_F: "La semana de trabajo siguiente",
L_CAL_NAV_TIMESCALE_PREV_W: "La semana anterior",
L_CAL_NAV_TIMESCALE_NEXT_W: "la semana siguiente",
L_CAL_NAV_TIMESCALE_PREV_2: "La quincena anterior",
L_CAL_NAV_TIMESCALE_NEXT_2: "La quincena siguiente",
L_CAL_NAV_TIMESCALE_PREV_M: "El mes anterior",
L_CAL_NAV_TIMESCALE_NEXT_M: "El mes siguiente",
L_CAL_NAV_TIMESCALE_PREV_Y: "El a\u00f1o anterior",
L_CAL_NAV_TIMESCALE_NEXT_Y: "El a\u00f1o siguiente"
})
