({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM de yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM de yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "a.m.",
L_CAL_LAST_DAY: "D\u00eda %1 - \u00faltimo d\u00eda del a\u00f1o",
L_CAL_LAST_MONTH: "Mes %1 - \u00faltimo mes del a\u00f1o",
L_CAL_LAST_WEEK: "Semana %1 - \u00faltima semana del a\u00f1o",
L_CAL_LEFT_DAY: "D\u00eda %1 - queda %2 d\u00eda hasta final de a\u00f1o",
L_CAL_LEFT_DAYS: "D\u00eda %1 - quedan %2 d\u00edas hasta final de a\u00f1o",
L_CAL_LEFT_MONTH: "Mes %1 - queda %2 mes hasta final de a\u00f1o",
L_CAL_LEFT_MONTHS: "Mes %1 - quedan %2 meses hasta final de a\u00f1o",
L_CAL_LEFT_WEEK: "Semana %1 - queda %2 semana hasta final de a\u00f1o",
L_CAL_LEFT_WEEKS: "Semana %1 - quedan %2 semanas hasta final de a\u00f1o",
L_CHARDAY_FRI: "V",
L_CHARDAY_MON: "L",
L_CHARDAY_SAT: "S",
L_CHARDAY_SUN: "D",
L_CHARDAY_THU: "J",
L_CHARDAY_TUE: "M",
L_CHARDAY_WED: "M",
L_NO_CAL_ENTRY_SELECTED: "No se ha seleccionado ninguna entrada de agenda. Seleccione una e int\u00e9ntelo de nuevo.",
L_PM_SUFFIX: "p.m.",
L_SIDECALENDAR_NOENTRY: "No existen entradas de agenda para el %1."
})
