({
L_CANCEL: "Annuleren",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Item niet gevonden",
L_ERR_INVALIDDATE: "Ongeldige datum opgegeven.",
L_FETCHING: "Bezig met  ophalen van records. . .",
L_FETCHINGNEXT: "Bezig met ophalen van volgende pagina van records. . .",
L_FETCHINGPREV: "Bezig met ophalen van vorige pagina van records. . .",
L_JAWS_GIGABYTES: "%1 Gigabyte",
L_JAWS_KILOBYTES: "%1 kilobyte",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Oplopend gesorteerd",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 kolom. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Aflopend gesorteerd",
L_JAWS_LISTVIEW_NOENTRY: "geen item geselecteerd",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Druk op Enter om oplopend te sorteren",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Druk op Enter om aflopend te sorteren",
L_JAWS_LISTVIEW_UNDORESORT: "Druk op Enter om de sorteeractie ongedaan te maken",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 kolom. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 van %3",
L_JAWS_MEGABYTES: "%1 megabyte",
L_JAWS_TERABYTES: "%1 terabyte",
L_NARROW_DEFAULT: "Standaard sorteren",
L_NARROW_NOTITLE: "Naamloos",
L_NARROW_SORTBY: "Sorteren op %1&nbsp;%2&nbsp;",
L_SEARCH: "Zoeken",
L_STARTSWITH_COLUMN: "Kies de kolom om op te sorteren:",
L_STARTSWITH_INVALID_NUMBER: "Ongeldig getal opgegeven",
L_STARTSWITH_SEARCH: "Items zoeken die beginnen met:",
L_STARTSWITH_TITLE: "Begint met...",
L_UPDATINGVIEW_MESSAGE: "Deze view wordt momenteel waarschijnlijk bijgewerkt op de server.\nDe view wordt weergegeven zodra de update is voltooid.\nU kunt doorwerken met andere tabbladen, views of mappen.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "Nieuw document ",
L_VIEWICONTIPS_ELM_10: "Herinnering ",
L_VIEWICONTIPS_ELM_100: "Blauwe ruit ",
L_VIEWICONTIPS_ELM_101: "Rode pijl omhoog ",
L_VIEWICONTIPS_ELM_102: "Rode pijl omlaag ",
L_VIEWICONTIPS_ELM_103: "Rode pijl links ",
L_VIEWICONTIPS_ELM_104: "Rode pijl rechts ",
L_VIEWICONTIPS_ELM_105: "Groene pijl omhoog ",
L_VIEWICONTIPS_ELM_106: "Groene pijl omlaag ",
L_VIEWICONTIPS_ELM_107: "Groene pijl links ",
L_VIEWICONTIPS_ELM_108: "Groene pijl rechts ",
L_VIEWICONTIPS_ELM_109: "Blauwe pijl omhoog ",
L_VIEWICONTIPS_ELM_11: "Informatie ",
L_VIEWICONTIPS_ELM_110: "Blauwe pijl omlaag ",
L_VIEWICONTIPS_ELM_111: "Blauwe pijl links ",
L_VIEWICONTIPS_ELM_112: "Blauwe pijl rechts ",
L_VIEWICONTIPS_ELM_113: "Blauw scherm ",
L_VIEWICONTIPS_ELM_114: "Groene bal ",
L_VIEWICONTIPS_ELM_115: "Rode bal ",
L_VIEWICONTIPS_ELM_116: "Bruine bal ",
L_VIEWICONTIPS_ELM_117: "Blauwe bal ",
L_VIEWICONTIPS_ELM_118: "Donkerblauwe bal ",
L_VIEWICONTIPS_ELM_119: "Paarse bal ",
L_VIEWICONTIPS_ELM_12: "Tekst schrijven ",
L_VIEWICONTIPS_ELM_120: "Gele bal ",
L_VIEWICONTIPS_ELM_121: "Ongeopende witte envelop ",
L_VIEWICONTIPS_ELM_122: "Verzonden bericht ",
L_VIEWICONTIPS_ELM_123: "Ongeopende blauwe envelop ",
L_VIEWICONTIPS_ELM_124: "Ongeopende rode envelop ",
L_VIEWICONTIPS_ELM_125: "Geopende witte envelop ",
L_VIEWICONTIPS_ELM_126: "Geopende gele envelop ",
L_VIEWICONTIPS_ELM_127: "Geopende blauwe envelop ",
L_VIEWICONTIPS_ELM_128: "Achterkant rode envelop ",
L_VIEWICONTIPS_ELM_129: "Achterkant witte envelop ",
L_VIEWICONTIPS_ELM_13: "Afbeelding ",
L_VIEWICONTIPS_ELM_130: "Achterkant gele envelop ",
L_VIEWICONTIPS_ELM_131: "Achterkant rode envelop ",
L_VIEWICONTIPS_ELM_132: "Witte uitnodiging ",
L_VIEWICONTIPS_ELM_133: "Gele uitnodiging ",
L_VIEWICONTIPS_ELM_134: "Rode uitnodiging ",
L_VIEWICONTIPS_ELM_135: "Lotus 1-2-3 ",
L_VIEWICONTIPS_ELM_136: "Tekstverwerkingsdocument ",
L_VIEWICONTIPS_ELM_137: "Presentatie ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "Videocamera ",
L_VIEWICONTIPS_ELM_14: "Diagram ",
L_VIEWICONTIPS_ELM_140: "Werkstroomdocument ",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft PowerPoint ",
L_VIEWICONTIPS_ELM_144: "Cirkeldiagram ",
L_VIEWICONTIPS_ELM_145: "Visio ",
L_VIEWICONTIPS_ELM_146: "Winter ",
L_VIEWICONTIPS_ELM_147: "Voorjaar ",
L_VIEWICONTIPS_ELM_148: "Zomer ",
L_VIEWICONTIPS_ELM_149: "Najaar ",
L_VIEWICONTIPS_ELM_15: "Geluid ",
L_VIEWICONTIPS_ELM_150: "Uitroepteken ",
L_VIEWICONTIPS_ELM_151: "Nummer 1 ",
L_VIEWICONTIPS_ELM_152: "Nummer 2 ",
L_VIEWICONTIPS_ELM_153: "Nummer 3 ",
L_VIEWICONTIPS_ELM_154: "Nummer 4 ",
L_VIEWICONTIPS_ELM_155: "Nummer 5 ",
L_VIEWICONTIPS_ELM_156: "Koken ",
L_VIEWICONTIPS_ELM_157: "Document onacceptabel ",
L_VIEWICONTIPS_ELM_158: "Vergadering ",
L_VIEWICONTIPS_ELM_159: "Gouden ster ",
L_VIEWICONTIPS_ELM_16: "Microfoon ",
L_VIEWICONTIPS_ELM_160: "Afspraak ",
L_VIEWICONTIPS_ELM_161: "Widget ",
L_VIEWICONTIPS_ELM_162: "Vraag ",
L_VIEWICONTIPS_ELM_163: "Vertrouwelijk ",
L_VIEWICONTIPS_ELM_164: "Versleutelde e-mail ",
L_VIEWICONTIPS_ELM_165: "Blauw hangslot ",
L_VIEWICONTIPS_ELM_166: "Vermomd ",
L_VIEWICONTIPS_ELM_167: "Blauw vinkje ",
L_VIEWICONTIPS_ELM_168: "Taak ",
L_VIEWICONTIPS_ELM_169: "Rode medaille ",
L_VIEWICONTIPS_ELM_17: "Afbeelding ",
L_VIEWICONTIPS_ELM_170: "Gele medaille ",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Vliegtuig ",
L_VIEWICONTIPS_ELM_174: "Auto ",
L_VIEWICONTIPS_ELM_175: "Gebouw ",
L_VIEWICONTIPS_ELM_176: "Nieuw document ",
L_VIEWICONTIPS_ELM_177: "Feestballon ",
L_VIEWICONTIPS_ELM_178: "Bericht beantwoord ",
L_VIEWICONTIPS_ELM_179: "Bericht doorgestuurd ",
L_VIEWICONTIPS_ELM_18: "Groen scherm ",
L_VIEWICONTIPS_ELM_180: "Bericht beantwoord en doorgestuurd ",
L_VIEWICONTIPS_ELM_181: "Follow-up hoge prioriteit ",
L_VIEWICONTIPS_ELM_182: "Follow-up normale prioriteit ",
L_VIEWICONTIPS_ELM_183: "Follow-up lage prioriteit ",
L_VIEWICONTIPS_ELM_184: "Alleen aan mij verzonden ",
L_VIEWICONTIPS_ELM_185: "Naar mij en een paar personen verzonden ",
L_VIEWICONTIPS_ELM_186: "Naar mij en veel personen verzonden ",
L_VIEWICONTIPS_ELM_187: "Niet-verwerkt vergaderbericht ",
L_VIEWICONTIPS_ELM_188: "Ongelezen bericht ",
L_VIEWICONTIPS_ELM_189: "Online vergadering ",
L_VIEWICONTIPS_ELM_19: "Tabel ",
L_VIEWICONTIPS_ELM_190: "Hoge relevantie ",
L_VIEWICONTIPS_ELM_191: "Gemiddelde relevantie ",
L_VIEWICONTIPS_ELM_192: "Lage relevantie ",
L_VIEWICONTIPS_ELM_193: "Niet relevant ",
L_VIEWICONTIPS_ELM_194: "Dagevenement ",
L_VIEWICONTIPS_ELM_195: "Herinnering ",
L_VIEWICONTIPS_ELM_196: "Opnieuw gepland ",
L_VIEWICONTIPS_ELM_197: "Uitnodiging afwijzen ",
L_VIEWICONTIPS_ELM_198: "Tegenvoorstel ",
L_VIEWICONTIPS_ELM_199: "Feestdag ",
L_VIEWICONTIPS_ELM_2: "Ongeopende map ",
L_VIEWICONTIPS_ELM_20: "Tekst ",
L_VIEWICONTIPS_ELM_200: "Geannuleerde vergadering ",
L_VIEWICONTIPS_ELM_201: "Voltooide taak ",
L_VIEWICONTIPS_ELM_202: "Geaccepteerd ",
L_VIEWICONTIPS_ELM_203: "Afgewezen ",
L_VIEWICONTIPS_ELM_204: "Hoge prioriteit ",
L_VIEWICONTIPS_ELM_205: "Afspraak ",
L_VIEWICONTIPS_ELM_206: "Persoonlijke uitnodiging ",
L_VIEWICONTIPS_ELM_207: "Grap ",
L_VIEWICONTIPS_ELM_208: "Vertrouwelijk ",
L_VIEWICONTIPS_ELM_209: "Persoonlijk ",
L_VIEWICONTIPS_ELM_21: "Meerdere documenten ",
L_VIEWICONTIPS_ELM_210: "Geaccepteerde uitnodiging ",
L_VIEWICONTIPS_ELM_211: "Gelezen bericht ",
L_VIEWICONTIPS_ELM_212: "Nieuwe uitnodiging ",
L_VIEWICONTIPS_ELM_22: "Twee documenten ",
L_VIEWICONTIPS_ELM_23: "Nieuws ",
L_VIEWICONTIPS_ELM_24: "Rood boek ",
L_VIEWICONTIPS_ELM_25: "Adresboek ",
L_VIEWICONTIPS_ELM_26: "Open boek ",
L_VIEWICONTIPS_ELM_27: "Gesloten boek ",
L_VIEWICONTIPS_ELM_28: "Wit boek ",
L_VIEWICONTIPS_ELM_29: "Gescheurde gele pagina ",
L_VIEWICONTIPS_ELM_3: "Persoon ",
L_VIEWICONTIPS_ELM_30: "Gescheurde blauwe pagina ",
L_VIEWICONTIPS_ELM_31: "Lamp aan ",
L_VIEWICONTIPS_ELM_32: "Lamp uit ",
L_VIEWICONTIPS_ELM_33: "Vernieuwen ",
L_VIEWICONTIPS_ELM_34: "Document doorzoeken ",
L_VIEWICONTIPS_ELM_35: "Document doorzoeken voltooid ",
L_VIEWICONTIPS_ELM_36: "Document acceptabel ",
L_VIEWICONTIPS_ELM_37: "Document voltooid ",
L_VIEWICONTIPS_ELM_38: "Documentprobleem ",
L_VIEWICONTIPS_ELM_39: "Documentvraag",
L_VIEWICONTIPS_ELM_4: "Groep ",
L_VIEWICONTIPS_ELM_40: "Documentwaarschuwing ",
L_VIEWICONTIPS_ELM_41: "Geel document",
L_VIEWICONTIPS_ELM_42: "Antwoord geel document ",
L_VIEWICONTIPS_ELM_43: "Antwoord blauw document ",
L_VIEWICONTIPS_ELM_44: "Telefoon ",
L_VIEWICONTIPS_ELM_45: "Actieve telefoon ",
L_VIEWICONTIPS_ELM_46: "Computerterminal ",
L_VIEWICONTIPS_ELM_47: "Fax ",
L_VIEWICONTIPS_ELM_48: "Cd-rom ",
L_VIEWICONTIPS_ELM_49: "Floppy disk ",
L_VIEWICONTIPS_ELM_5: "Bijlage ",
L_VIEWICONTIPS_ELM_50: "Diskette ",
L_VIEWICONTIPS_ELM_51: "Vaste schijf ",
L_VIEWICONTIPS_ELM_52: "Netwerk ",
L_VIEWICONTIPS_ELM_53: "Computer ",
L_VIEWICONTIPS_ELM_54: "Server ",
L_VIEWICONTIPS_ELM_55: "Verbinding ",
L_VIEWICONTIPS_ELM_56: "Zoeken ",
L_VIEWICONTIPS_ELM_57: "Schrijven ",
L_VIEWICONTIPS_ELM_58: "Concept ",
L_VIEWICONTIPS_ELM_59: "Valuta ",
L_VIEWICONTIPS_ELM_6: "Verweven ",
L_VIEWICONTIPS_ELM_60: "Munten ",
L_VIEWICONTIPS_ELM_61: "Sleutel ",
L_VIEWICONTIPS_ELM_62: "Hangslot ",
L_VIEWICONTIPS_ELM_63: "Agenda ",
L_VIEWICONTIPS_ELM_64: "Klok ",
L_VIEWICONTIPS_ELM_65: "Waarschuwing ",
L_VIEWICONTIPS_ELM_66: "Vliegen ",
L_VIEWICONTIPS_ELM_67: "Satelliet ",
L_VIEWICONTIPS_ELM_68: "Aktetas ",
L_VIEWICONTIPS_ELM_69: "Huis ",
L_VIEWICONTIPS_ELM_7: "Dier ",
L_VIEWICONTIPS_ELM_70: "Wereldbol ",
L_VIEWICONTIPS_ELM_71: "Gezondheidszorg ",
L_VIEWICONTIPS_ELM_72: "Financi\u00ebn ",
L_VIEWICONTIPS_ELM_73: "Transport ",
L_VIEWICONTIPS_ELM_74: "Chemisch ",
L_VIEWICONTIPS_ELM_75: "Productie ",
L_VIEWICONTIPS_ELM_76: "Nutsbedrijven ",
L_VIEWICONTIPS_ELM_77: "Telecommunicatie ",
L_VIEWICONTIPS_ELM_78: "Bouw ",
L_VIEWICONTIPS_ELM_79: "Zandloper ",
L_VIEWICONTIPS_ELM_8: "Zoeken ",
L_VIEWICONTIPS_ELM_80: "Verboden ",
L_VIEWICONTIPS_ELM_81: "Afgewezen ",
L_VIEWICONTIPS_ELM_82: "Voltooid ",
L_VIEWICONTIPS_ELM_83: "Acceptabel ",
L_VIEWICONTIPS_ELM_84: "Onacceptabel ",
L_VIEWICONTIPS_ELM_85: "Vrolijk ",
L_VIEWICONTIPS_ELM_86: "Onverschillig ",
L_VIEWICONTIPS_ELM_87: "Droevig ",
L_VIEWICONTIPS_ELM_88: "Lauw ",
L_VIEWICONTIPS_ELM_89: "Warm ",
L_VIEWICONTIPS_ELM_9: "Netwerkactiviteit ",
L_VIEWICONTIPS_ELM_90: "Zeer heet ",
L_VIEWICONTIPS_ELM_91: "Bom ",
L_VIEWICONTIPS_ELM_92: "Stopteken ",
L_VIEWICONTIPS_ELM_93: "Stop ",
L_VIEWICONTIPS_ELM_94: "Let op ",
L_VIEWICONTIPS_ELM_95: "Gaan ",
L_VIEWICONTIPS_ELM_96: "Positief ",
L_VIEWICONTIPS_ELM_97: "Negatief ",
L_VIEWICONTIPS_ELM_98: "Rode ruit ",
L_VIEWICONTIPS_ELM_99: "Groene ruit ",
L_VIEWMAIL: "E-mail"
})
