// Generated by IBM Domino Designer
package %PLUGIN-NAME%;

import java.sql.Driver;
import java.sql.SQLException;

import com.ibm.commons.jdbc.drivers.IJDBCDriverAlias;
import com.ibm.commons.jdbc.drivers.JDBCProvider;

public class JdbcDriverProvider implements JDBCProvider {

	public Driver loadDriver(String className) throws SQLException {
		if(className.equals(%CLASS-NAME%.class.getName())) {
			return new %CLASS-NAME%();
		}
		return null;
	}

	public IJDBCDriverAlias[] getDriverAliases() {
		return null;
	}
}
