({
L_CAL_NAV_PREVIOUS: "Foreg\u00e5ende",
L_CAL_NAV_NEXT: "N\u00e6ste",
L_CAL_NAV_MONTH: "M\u00e5ned",
L_CAL_HEADER_DAYS_WEEK: "Dage i ugen",
L_CAL_HEADER: "Kalenderoverskrifter",
L_CAL_HEADER_DAY: "Dagoverskrift %1",
L_CAL_EVENT_ALLDAY: "Heldagsaktivitet %1",
L_CAL_NOENTRY: "Ingen indgange",
L_CAL_GRID: "Kalendergitter",
L_CAL_PICKER_POPUP: "Datov\u00e6lgerpopop",
L_CAL_NAV_TIMESCALE_PREV_D: "Foreg\u00e5ende dag",
L_CAL_NAV_TIMESCALE_NEXT_D: "N\u00e6ste dag",
L_CAL_NAV_TIMESCALE_PREV_T: "Foreg\u00e5ende to dage",
L_CAL_NAV_TIMESCALE_NEXT_T: "N\u00e6ste to dage",
L_CAL_NAV_TIMESCALE_PREV_F: "Foreg\u00e5ende arbejdsuge",
L_CAL_NAV_TIMESCALE_NEXT_F: "N\u00e6ste arbejdsuge",
L_CAL_NAV_TIMESCALE_PREV_W: "Foreg\u00e5ende uge",
L_CAL_NAV_TIMESCALE_NEXT_W: "N\u00e6ste uge",
L_CAL_NAV_TIMESCALE_PREV_2: "Foreg\u00e5ende to uger",
L_CAL_NAV_TIMESCALE_NEXT_2: "N\u00e6ste to uger",
L_CAL_NAV_TIMESCALE_PREV_M: "Foreg\u00e5ende m\u00e5ned",
L_CAL_NAV_TIMESCALE_NEXT_M: "N\u00e6ste m\u00e5ned",
L_CAL_NAV_TIMESCALE_PREV_Y: "Foreg\u00e5ende \u00e5r",
L_CAL_NAV_TIMESCALE_NEXT_Y: "N\u00e6ste \u00e5r"
})
