({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Dag %1 - sidste dag i \u00e5ret",
L_CAL_LAST_MONTH: "M\u00e5ned %1 - sidste m\u00e5ned i \u00e5ret",
L_CAL_LAST_WEEK: "Uge %1 - sidste uge i \u00e5ret",
L_CAL_LEFT_DAY: "Dag %1 - %2 dag tilbage af \u00e5ret",
L_CAL_LEFT_DAYS: "Dag %1 - %2 dage tilbage af \u00e5ret",
L_CAL_LEFT_MONTH: "M\u00e5ned %1 - %2 m\u00e5ned tilbage af \u00e5ret",
L_CAL_LEFT_MONTHS: "M\u00e5ned %1 - %2 m\u00e5neder tilbage af \u00e5ret",
L_CAL_LEFT_WEEK: "Uge %1 - %2 uge tilbage af \u00e5ret",
L_CAL_LEFT_WEEKS: "Uge %1 - %2 uger tilbage af \u00e5ret",
L_CHARDAY_FRI: "F",
L_CHARDAY_MON: "M",
L_CHARDAY_SAT: "L",
L_CHARDAY_SUN: "S",
L_CHARDAY_THU: "T",
L_CHARDAY_TUE: "T",
L_CHARDAY_WED: "O",
L_NO_CAL_ENTRY_SELECTED: "Der er ingen kalenderoplysning markeret. Marker en oplysning, og pr\u00f8v igen.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "Ingen kalenderoplysninger for %1."
})
