({
L_CANCEL: "Avbryt",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Det gick inte att hitta uppgiften.",
L_ERR_INVALIDDATE: "Ogiltigt datum angavs.",
L_FETCHING: "H\u00e4mtar poster . . .",
L_FETCHINGNEXT: "H\u00e4mtar n\u00e4sta sida med poster . . .",
L_FETCHINGPREV: "H\u00e4mtar f\u00f6reg\u00e5ende sida med poster . . .",
L_JAWS_GIGABYTES: "%1Gigabyte",
L_JAWS_KILOBYTES: "%1Kilobyte",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Stigande sortering",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 kolumn. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Fallande sortering",
L_JAWS_LISTVIEW_NOENTRY: "ingen post vald",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Tryck p\u00e5 Enter f\u00f6r att sortera om stigande",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Tryck p\u00e5 Enter f\u00f6r att sortera om fallande",
L_JAWS_LISTVIEW_UNDORESORT: "Tryck p\u00e5 Enter f\u00f6r att \u00e5ngra omsortering",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 kolumn. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 av %3",
L_JAWS_MEGABYTES: "%1Megabyte",
L_JAWS_TERABYTES: "%1Terabyte",
L_NARROW_DEFAULT: "Sortera som standard",
L_NARROW_NOTITLE: "Namnl\u00f6st",
L_NARROW_SORTBY: "Sortera efter %1",
L_SEARCH: "S\u00f6k",
L_STARTSWITH_COLUMN: "V\u00e4lj kolumn att sortera efter:",
L_STARTSWITH_INVALID_NUMBER: "Ogiltigt antal angavs",
L_STARTSWITH_SEARCH: "S\u00f6k efter uppgifter som b\u00f6rjar med:",
L_STARTSWITH_TITLE: "B\u00f6rjar med...",
L_UPDATINGVIEW_MESSAGE: "Den h\u00e4r vyn uppdateras troligen p\u00e5 servern.\nDen visas s\u00e5 snart uppdateringen \u00e4r slutf\u00f6rd.\nDu kan forts\u00e4tta arbeta med andra flikar eller f\u00f6rs\u00f6ka g\u00e5 till andra vyer/mappar.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "Nytt dokument ",
L_VIEWICONTIPS_ELM_10: "P\u00e5minnelse ",
L_VIEWICONTIPS_ELM_100: "Bl\u00e5 diamant ",
L_VIEWICONTIPS_ELM_101: "R\u00f6d upp\u00e5tpil ",
L_VIEWICONTIPS_ELM_102: "R\u00f6d ned\u00e5tpil ",
L_VIEWICONTIPS_ELM_103: "R\u00f6d v\u00e4nsterpil ",
L_VIEWICONTIPS_ELM_104: "R\u00f6d h\u00f6gerpil ",
L_VIEWICONTIPS_ELM_105: "Gr\u00f6n upp\u00e5tpil ",
L_VIEWICONTIPS_ELM_106: "Gr\u00f6n ned\u00e5tpil ",
L_VIEWICONTIPS_ELM_107: "Gr\u00f6n v\u00e4nsterpil ",
L_VIEWICONTIPS_ELM_108: "Gr\u00f6n h\u00f6gerpil ",
L_VIEWICONTIPS_ELM_109: "Bl\u00e5 upp\u00e5tpil",
L_VIEWICONTIPS_ELM_11: "Information ",
L_VIEWICONTIPS_ELM_110: "Bl\u00e5 ned\u00e5tpil ",
L_VIEWICONTIPS_ELM_111: "Bl\u00e5 v\u00e4nsterpil ",
L_VIEWICONTIPS_ELM_112: "Bl\u00e5 h\u00f6gerpil ",
L_VIEWICONTIPS_ELM_113: "Bl\u00e5 sk\u00e4rm ",
L_VIEWICONTIPS_ELM_114: "Gr\u00f6n boll ",
L_VIEWICONTIPS_ELM_115: "R\u00f6d boll ",
L_VIEWICONTIPS_ELM_116: "Brun boll ",
L_VIEWICONTIPS_ELM_117: "Bl\u00e5 boll ",
L_VIEWICONTIPS_ELM_118: "M\u00f6rkbl\u00e5 boll ",
L_VIEWICONTIPS_ELM_119: "Lila boll ",
L_VIEWICONTIPS_ELM_12: "Skriv text ",
L_VIEWICONTIPS_ELM_120: "Gul boll ",
L_VIEWICONTIPS_ELM_121: "O\u00f6ppnat vitt kuvert ",
L_VIEWICONTIPS_ELM_122: "S\u00e4nt meddelande ",
L_VIEWICONTIPS_ELM_123: "O\u00f6ppnat bl\u00e5tt kuvert ",
L_VIEWICONTIPS_ELM_124: "O\u00f6ppnat r\u00f6tt kuvert ",
L_VIEWICONTIPS_ELM_125: "\u00d6ppnat vitt kuvert ",
L_VIEWICONTIPS_ELM_126: "\u00d6ppnat gult kuvert ",
L_VIEWICONTIPS_ELM_127: "\u00d6ppnat bl\u00e5tt kuvert ",
L_VIEWICONTIPS_ELM_128: "R\u00f6d kuvertbaksida ",
L_VIEWICONTIPS_ELM_129: "Vit kuvertbaksida ",
L_VIEWICONTIPS_ELM_13: "Bild ",
L_VIEWICONTIPS_ELM_130: "Gul kuvertbaksida ",
L_VIEWICONTIPS_ELM_131: "Gul kuvertbaksida ",
L_VIEWICONTIPS_ELM_132: "Vit kallelse ",
L_VIEWICONTIPS_ELM_133: "Gul kallelse ",
L_VIEWICONTIPS_ELM_134: "R\u00f6d kallelse ",
L_VIEWICONTIPS_ELM_135: "Lotus 1-2-3 ",
L_VIEWICONTIPS_ELM_136: "Ordbehandlingsdokument ",
L_VIEWICONTIPS_ELM_137: "Presentation ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "Videokamera ",
L_VIEWICONTIPS_ELM_14: "Tabell ",
L_VIEWICONTIPS_ELM_140: "Arbetsfl\u00f6desdokument ",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_144: "Cirkeldiagram ",
L_VIEWICONTIPS_ELM_145: "Visio ",
L_VIEWICONTIPS_ELM_146: "Vinter ",
L_VIEWICONTIPS_ELM_147: "V\u00e5r ",
L_VIEWICONTIPS_ELM_148: "Sommar ",
L_VIEWICONTIPS_ELM_149: "H\u00f6st ",
L_VIEWICONTIPS_ELM_15: "Ljud ",
L_VIEWICONTIPS_ELM_150: "Utropstecken ",
L_VIEWICONTIPS_ELM_151: "Nummer 1 ",
L_VIEWICONTIPS_ELM_152: "Nummer 2 ",
L_VIEWICONTIPS_ELM_153: "Nummer 3 ",
L_VIEWICONTIPS_ELM_154: "Nummer 4 ",
L_VIEWICONTIPS_ELM_155: "Nummer 5 ",
L_VIEWICONTIPS_ELM_156: "Matlagning ",
L_VIEWICONTIPS_ELM_157: "Oaccepterbart dokument ",
L_VIEWICONTIPS_ELM_158: "M\u00f6te ",
L_VIEWICONTIPS_ELM_159: "Guldstj\u00e4rna ",
L_VIEWICONTIPS_ELM_16: "Mikrofon ",
L_VIEWICONTIPS_ELM_160: "Bokning ",
L_VIEWICONTIPS_ELM_161: "Widgetprogram ",
L_VIEWICONTIPS_ELM_162: "Fr\u00e5ga ",
L_VIEWICONTIPS_ELM_163: "Konfidentiellt ",
L_VIEWICONTIPS_ELM_164: "Krypterad post ",
L_VIEWICONTIPS_ELM_165: "Bl\u00e5tt h\u00e4ngl\u00e5s ",
L_VIEWICONTIPS_ELM_166: "F\u00f6rkl\u00e4dnad ",
L_VIEWICONTIPS_ELM_167: "Bl\u00e5 bockmarkering ",
L_VIEWICONTIPS_ELM_168: "Att g\u00f6ra-uppgift ",
L_VIEWICONTIPS_ELM_169: "R\u00f6d medalj ",
L_VIEWICONTIPS_ELM_17: "Grafik ",
L_VIEWICONTIPS_ELM_170: "Gul medalj ",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Flygplan ",
L_VIEWICONTIPS_ELM_174: "Bil ",
L_VIEWICONTIPS_ELM_175: "Byggnad ",
L_VIEWICONTIPS_ELM_176: "Nytt dokument ",
L_VIEWICONTIPS_ELM_177: "Ballong ",
L_VIEWICONTIPS_ELM_178: "Besvarat meddelande ",
L_VIEWICONTIPS_ELM_179: "Vidarebefordrat meddelande ",
L_VIEWICONTIPS_ELM_18: "Gr\u00f6n sk\u00e4rm ",
L_VIEWICONTIPS_ELM_180: "Besvarat och vidarebefordrat meddelande ",
L_VIEWICONTIPS_ELM_181: "Uppf\u00f6ljning med h\u00f6g prioritet.",
L_VIEWICONTIPS_ELM_182: "Uppf\u00f6ljning med normal prioritet.",
L_VIEWICONTIPS_ELM_183: "Uppf\u00f6ljning med l\u00e5g prioritet.",
L_VIEWICONTIPS_ELM_184: "Endast s\u00e4nt till mig ",
L_VIEWICONTIPS_ELM_185: "S\u00e4nt till mig och ett f\u00e5tal andra personer ",
L_VIEWICONTIPS_ELM_186: "S\u00e4nt till mig och m\u00e5nga andra personer ",
L_VIEWICONTIPS_ELM_187: "Obehandlad m\u00f6teskallelse ",
L_VIEWICONTIPS_ELM_188: "Ol\u00e4st meddelande ",
L_VIEWICONTIPS_ELM_189: "Onlinem\u00f6te ",
L_VIEWICONTIPS_ELM_19: "Tabell ",
L_VIEWICONTIPS_ELM_190: "H\u00f6g relevans ",
L_VIEWICONTIPS_ELM_191: "Medelh\u00f6g relevans ",
L_VIEWICONTIPS_ELM_192: "L\u00e5g relevans ",
L_VIEWICONTIPS_ELM_193: "Inte relevant ",
L_VIEWICONTIPS_ELM_194: "Heldagsh\u00e4ndelse ",
L_VIEWICONTIPS_ELM_195: "P\u00e5minnelse ",
L_VIEWICONTIPS_ELM_196: "Ombokat ",
L_VIEWICONTIPS_ELM_197: "Avb\u00f6j kallelse ",
L_VIEWICONTIPS_ELM_198: "Kallelse med motf\u00f6rslag ",
L_VIEWICONTIPS_ELM_199: "H\u00f6gtidsdag ",
L_VIEWICONTIPS_ELM_2: "O\u00f6ppnad mapp ",
L_VIEWICONTIPS_ELM_20: "Text ",
L_VIEWICONTIPS_ELM_200: "Avbokat m\u00f6te ",
L_VIEWICONTIPS_ELM_201: "Slutf\u00f6rd Att g\u00f6ra-uppgift ",
L_VIEWICONTIPS_ELM_202: "Accepterat ",
L_VIEWICONTIPS_ELM_203: "Avb\u00f6jt ",
L_VIEWICONTIPS_ELM_204: "H\u00f6g prioritet",
L_VIEWICONTIPS_ELM_205: "Bokning ",
L_VIEWICONTIPS_ELM_206: "Privat kallelse ",
L_VIEWICONTIPS_ELM_207: "K\u00e4nslol\u00e4gesikon f\u00f6r sk\u00e4mt ",
L_VIEWICONTIPS_ELM_208: "K\u00e4nslol\u00e4gesikon f\u00f6r konfidentiellt ",
L_VIEWICONTIPS_ELM_209: "K\u00e4nslol\u00e4gesikon f\u00f6r privat ",
L_VIEWICONTIPS_ELM_21: "Flera dokument ",
L_VIEWICONTIPS_ELM_210: "Accepterad kallelse ",
L_VIEWICONTIPS_ELM_211: "L\u00e4st meddelande ",
L_VIEWICONTIPS_ELM_212: "Ny kallelse ",
L_VIEWICONTIPS_ELM_22: "Tv\u00e5 dokument ",
L_VIEWICONTIPS_ELM_23: "Nyheter ",
L_VIEWICONTIPS_ELM_24: "R\u00f6d bok ",
L_VIEWICONTIPS_ELM_25: "Adressbok ",
L_VIEWICONTIPS_ELM_26: "\u00d6ppen bok ",
L_VIEWICONTIPS_ELM_27: "St\u00e4ngd bok ",
L_VIEWICONTIPS_ELM_28: "Vit bok ",
L_VIEWICONTIPS_ELM_29: "Avriven gul sida ",
L_VIEWICONTIPS_ELM_3: "Person ",
L_VIEWICONTIPS_ELM_30: "Avriven bl\u00e5 sida ",
L_VIEWICONTIPS_ELM_31: "T\u00e4nd gl\u00f6dlampa ",
L_VIEWICONTIPS_ELM_32: "Sl\u00e4ckt gl\u00f6dlampa ",
L_VIEWICONTIPS_ELM_33: "Uppdatera ",
L_VIEWICONTIPS_ELM_34: "Dokuments\u00f6kning ",
L_VIEWICONTIPS_ELM_35: "Dokuments\u00f6kningen slutf\u00f6rdes ",
L_VIEWICONTIPS_ELM_36: "Accepterbart dokument ",
L_VIEWICONTIPS_ELM_37: "Fullst\u00e4ndigt dokument ",
L_VIEWICONTIPS_ELM_38: "Dokumentproblem ",
L_VIEWICONTIPS_ELM_39: "Dokumentfr\u00e5ga ",
L_VIEWICONTIPS_ELM_4: "Grupp ",
L_VIEWICONTIPS_ELM_40: "Dokumentvarning ",
L_VIEWICONTIPS_ELM_41: "Gult dokument ",
L_VIEWICONTIPS_ELM_42: "Gult besvarat dokument ",
L_VIEWICONTIPS_ELM_43: "Bl\u00e5tt besvarat dokument ",
L_VIEWICONTIPS_ELM_44: "Telefon ",
L_VIEWICONTIPS_ELM_45: "Aktiv telefon ",
L_VIEWICONTIPS_ELM_46: "Terminal ",
L_VIEWICONTIPS_ELM_47: "Fax ",
L_VIEWICONTIPS_ELM_48: "CD-ROM ",
L_VIEWICONTIPS_ELM_49: "Diskett ",
L_VIEWICONTIPS_ELM_5: "Bilaga ",
L_VIEWICONTIPS_ELM_50: "Diskett ",
L_VIEWICONTIPS_ELM_51: "H\u00e5rddisk ",
L_VIEWICONTIPS_ELM_52: "N\u00e4tverk ",
L_VIEWICONTIPS_ELM_53: "Dator ",
L_VIEWICONTIPS_ELM_54: "Server ",
L_VIEWICONTIPS_ELM_55: "Anslutning ",
L_VIEWICONTIPS_ELM_56: "S\u00f6k ",
L_VIEWICONTIPS_ELM_57: "Skriv ",
L_VIEWICONTIPS_ELM_58: "Utkast ",
L_VIEWICONTIPS_ELM_59: "Valuta ",
L_VIEWICONTIPS_ELM_6: "Sammanv\u00e4vd ",
L_VIEWICONTIPS_ELM_60: "Mynt ",
L_VIEWICONTIPS_ELM_61: "Nyckel ",
L_VIEWICONTIPS_ELM_62: "H\u00e4ngl\u00e5s ",
L_VIEWICONTIPS_ELM_63: "Kalender ",
L_VIEWICONTIPS_ELM_64: "Klocka ",
L_VIEWICONTIPS_ELM_65: "Alarm ",
L_VIEWICONTIPS_ELM_66: "Flyger ",
L_VIEWICONTIPS_ELM_67: "Satellit ",
L_VIEWICONTIPS_ELM_68: "Portf\u00f6lj ",
L_VIEWICONTIPS_ELM_69: "Hem ",
L_VIEWICONTIPS_ELM_7: "Djur ",
L_VIEWICONTIPS_ELM_70: "Jordglob ",
L_VIEWICONTIPS_ELM_71: "H\u00e4lsa ",
L_VIEWICONTIPS_ELM_72: "Ekonomi ",
L_VIEWICONTIPS_ELM_73: "Transport ",
L_VIEWICONTIPS_ELM_74: "Kemiskt ",
L_VIEWICONTIPS_ELM_75: "Tillverkning ",
L_VIEWICONTIPS_ELM_76: "Verktyg ",
L_VIEWICONTIPS_ELM_77: "Telekommunikation ",
L_VIEWICONTIPS_ELM_78: "Konstruktion ",
L_VIEWICONTIPS_ELM_79: "Timglas ",
L_VIEWICONTIPS_ELM_8: "S\u00f6k ",
L_VIEWICONTIPS_ELM_80: "Sp\u00e4rrad ",
L_VIEWICONTIPS_ELM_81: "Avvisat ",
L_VIEWICONTIPS_ELM_82: "Slutf\u00f6rd ",
L_VIEWICONTIPS_ELM_83: "Accepterbart ",
L_VIEWICONTIPS_ELM_84: "Oaccepterbart ",
L_VIEWICONTIPS_ELM_85: "Glad ",
L_VIEWICONTIPS_ELM_86: "Likgiltig ",
L_VIEWICONTIPS_ELM_87: "Ledsen ",
L_VIEWICONTIPS_ELM_88: "Ljummet ",
L_VIEWICONTIPS_ELM_89: "Varmt ",
L_VIEWICONTIPS_ELM_9: "N\u00e4tverksaktivitet ",
L_VIEWICONTIPS_ELM_90: "Mycket varmt ",
L_VIEWICONTIPS_ELM_91: "Bomb ",
L_VIEWICONTIPS_ELM_92: "Stopptecken ",
L_VIEWICONTIPS_ELM_93: "Stopp ",
L_VIEWICONTIPS_ELM_94: "Varning ",
L_VIEWICONTIPS_ELM_95: "OK ",
L_VIEWICONTIPS_ELM_96: "Positivt ",
L_VIEWICONTIPS_ELM_97: "Negativt ",
L_VIEWICONTIPS_ELM_98: "R\u00f6d diamant ",
L_VIEWICONTIPS_ELM_99: "Gr\u00f6n diamant ",
L_VIEWMAIL: "Post"
})
