({
L_CAL_NAV_PREVIOUS: "Vorige",
L_CAL_NAV_NEXT: "Volgende",
L_CAL_NAV_MONTH: "Maand",
L_CAL_HEADER_DAYS_WEEK: "Dagen van de week",
L_CAL_HEADER: "Agendakoptekst",
L_CAL_HEADER_DAY: "Dagkoptekst %1",
L_CAL_EVENT_ALLDAY: "Dagevenement %1",
L_CAL_NOENTRY: "Geen items",
L_CAL_GRID: "Agendaraster",
L_CAL_PICKER_POPUP: "Datumkiezermenu",
L_CAL_NAV_TIMESCALE_PREV_D: "Vorige dag",
L_CAL_NAV_TIMESCALE_NEXT_D: "Volgende dag",
L_CAL_NAV_TIMESCALE_PREV_T: "Vorige twee dagen",
L_CAL_NAV_TIMESCALE_NEXT_T: "Volgende twee dagen",
L_CAL_NAV_TIMESCALE_PREV_F: "Vorige werkweek",
L_CAL_NAV_TIMESCALE_NEXT_F: "Volgende werkweek",
L_CAL_NAV_TIMESCALE_PREV_W: "Vorige week",
L_CAL_NAV_TIMESCALE_NEXT_W: "Volgende week",
L_CAL_NAV_TIMESCALE_PREV_2: "Vorige twee weken",
L_CAL_NAV_TIMESCALE_NEXT_2: "Volgende twee weken",
L_CAL_NAV_TIMESCALE_PREV_M: "Vorige maand",
L_CAL_NAV_TIMESCALE_NEXT_M: "Volgende maand",
L_CAL_NAV_TIMESCALE_PREV_Y: "Vorig jaar",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Volgend jaar"
})
