({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Dag %1 - laatste dag van het jaar",
L_CAL_LAST_MONTH: "Maand %1 - laatste maand van het jaar",
L_CAL_LAST_WEEK: "Week %1 - laatste week van het jaar",
L_CAL_LEFT_DAY: "Dag %1 - %2 dag in de rest van het jaar",
L_CAL_LEFT_DAYS: "Dag %1 - %2 dagen in de rest van het jaar",
L_CAL_LEFT_MONTH: "Maand %1 - %2 maand in de rest van het jaar",
L_CAL_LEFT_MONTHS: "Maand %1 - %2 maanden in de rest van het jaar",
L_CAL_LEFT_WEEK: "Week %1 - %2 week in de rest van het jaar",
L_CAL_LEFT_WEEKS: "Week %1 - %2 weken in de rest van het jaar",
L_CHARDAY_FRI: "V",
L_CHARDAY_MON: "M",
L_CHARDAY_SAT: "Z",
L_CHARDAY_SUN: "Z",
L_CHARDAY_THU: "D",
L_CHARDAY_TUE: "D",
L_CHARDAY_WED: "W",
L_NO_CAL_ENTRY_SELECTED: "Er is geen kalenderitem geselecteerd.  Selecteer een item en probeer het opnieuw.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "Geen agenda-items voor %1."
})
