({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Dia %1 - darrer dia de l'any",
L_CAL_LAST_MONTH: "Mes %1 - darrer mes de l'any",
L_CAL_LAST_WEEK: "Setmana %1 - darrera setmana de l'any",
L_CAL_LEFT_DAY: "Dia %1 - queda %2 dia de l'any",
L_CAL_LEFT_DAYS: "Dia %1 - queden %2 dies de l'any",
L_CAL_LEFT_MONTH: "Mes %1 - queda %2 mes de l'any",
L_CAL_LEFT_MONTHS: "Mes %1 - queden %2 mesos de l'any",
L_CAL_LEFT_WEEK: "Setmana %1 - queda %2 setmana de l'any",
L_CAL_LEFT_WEEKS: "Setmana %1 - queden %2 setmanes de l'any",
L_CHARDAY_FRI: "dv",
L_CHARDAY_MON: "dl",
L_CHARDAY_SAT: "ds",
L_CHARDAY_SUN: "dg",
L_CHARDAY_THU: "dj",
L_CHARDAY_TUE: "dt",
L_CHARDAY_WED: "dc",
L_NO_CAL_ENTRY_SELECTED: "No heu seleccionat cap entrada de calendari.  Seleccioneu una entrada i torneu-ho a provar.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "No hi ha entrades de calendari per a %1."
})
