({
L_CAL_NAV_PREVIOUS: "Anterior",
L_CAL_NAV_NEXT: "Seg\u00fcent",
L_CAL_NAV_MONTH: "Mes",
L_CAL_HEADER_DAYS_WEEK: "Dies de la setmana",
L_CAL_HEADER: "Cap\u00e7alera de calendari",
L_CAL_HEADER_DAY: "Cap\u00e7alera de dia %1",
L_CAL_EVENT_ALLDAY: "Esdeveniment de tot el dia %1",
L_CAL_NOENTRY: "Cap entrada",
L_CAL_GRID: "Graella de calendari",
L_CAL_PICKER_POPUP: "Element emergent de selector de dates",
L_CAL_NAV_TIMESCALE_PREV_D: "El dia anterior",
L_CAL_NAV_TIMESCALE_NEXT_D: "El dia seg\u00fcent",
L_CAL_NAV_TIMESCALE_PREV_T: "Els dos dies anteriors",
L_CAL_NAV_TIMESCALE_NEXT_T: "Els dos dies seg\u00fcents",
L_CAL_NAV_TIMESCALE_PREV_F: "La setmana de feina anterior",
L_CAL_NAV_TIMESCALE_NEXT_F: "La setmana de feina seg\u00fcent",
L_CAL_NAV_TIMESCALE_PREV_W: "La setmana anterior",
L_CAL_NAV_TIMESCALE_NEXT_W: "La setmana seg\u00fcent",
L_CAL_NAV_TIMESCALE_PREV_2: "La quinzena anterior",
L_CAL_NAV_TIMESCALE_NEXT_2: "La quinzena seg\u00fcent",
L_CAL_NAV_TIMESCALE_PREV_M: "El mes anterior",
L_CAL_NAV_TIMESCALE_NEXT_M: "El mes seg\u00fcent",
L_CAL_NAV_TIMESCALE_PREV_Y: "L'any anterior",
L_CAL_NAV_TIMESCALE_NEXT_Y: "L'any seg\u00fcent"
})
