({
D_DIR_DEFAULT: "ltr",
D_GIGABYTES: "%1 G",
D_KILOBYTES: "%1 k",
D_MEGABYTES: "%1 M",
D_NUMFMT_DECIMALSYMBOL: ",",
D_NUMFMT_THOUSANDSSEPARATOR: ",",
D_PADDING_REVERSE: "padding-right",
D_TERABYTES: "%1 T"
})
