({
L_CANCEL: "Annuler",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Entr\u00e9e introuvable",
L_ERR_INVALIDDATE: "Date sp\u00e9cifi\u00e9e non valide.",
L_FETCHING: "R\u00e9cup\u00e9ration des enregistrements . . .",
L_FETCHINGNEXT: "R\u00e9cup\u00e9ration des enregistrements de la page suivante . . .",
L_FETCHINGPREV: "R\u00e9cup\u00e9ration des enregistrements de la page pr\u00e9c\u00e9dente . . .",
L_JAWS_GIGABYTES: "%1giga-octets",
L_JAWS_KILOBYTES: "%1kilo-octets",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Tri en ordre croissant",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 colonne. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Tri en ordre d\u00e9croissant",
L_JAWS_LISTVIEW_NOENTRY: "aucune entr\u00e9e s\u00e9lectionn\u00e9e",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Appuyez sur la touche pour retrier en ordre croissant",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Appuyez sur la touche pour retrier en ordre d\u00e9croissant",
L_JAWS_LISTVIEW_UNDORESORT: "Appuyez sur la touche pour annuler le nouveau tri",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 colonne. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 sur %3",
L_JAWS_MEGABYTES: "%1m\u00e9ga-octets",
L_JAWS_TERABYTES: "%1t\u00e9ra-octets",
L_NARROW_DEFAULT: "Trier par d\u00e9faut",
L_NARROW_NOTITLE: "Sans titre",
L_NARROW_SORTBY: "Trier par %1&nbsp;%2&nbsp;",
L_SEARCH: "Recherche",
L_STARTSWITH_COLUMN: "Choisir de trier la colonne par\u00a0:",
L_STARTSWITH_INVALID_NUMBER: "Nombre sp\u00e9cifi\u00e9 non valide",
L_STARTSWITH_SEARCH: "Rechercher des entr\u00e9es commen\u00e7ant par\u00a0:",
L_STARTSWITH_TITLE: "Commence par...",
L_UPDATINGVIEW_MESSAGE: "Cette vue est probablement en cours de mise \u00e0 jour sur le serveur.\nElle s'affichera une fois la mise \u00e0 jour termin\u00e9e.\nVous pouvez continuer de travailler sur d'autres onglets ou tenter d'acc\u00e9der \u00e0 d'autres vues/dossiers.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "Nouveau document ",
L_VIEWICONTIPS_ELM_10: "Rappel ",
L_VIEWICONTIPS_ELM_100: "Diamant bleu ",
L_VIEWICONTIPS_ELM_101: "Fl\u00e8che haut rougeRed ",
L_VIEWICONTIPS_ELM_102: "Fl\u00e8che bas bleue ",
L_VIEWICONTIPS_ELM_103: "Fl\u00e8che gauche rouge ",
L_VIEWICONTIPS_ELM_104: "Fl\u00e8che droite rouge ",
L_VIEWICONTIPS_ELM_105: "Fl\u00e8che haut verte ",
L_VIEWICONTIPS_ELM_106: "Fl\u00e8che bas verte ",
L_VIEWICONTIPS_ELM_107: "Fl\u00e8che gauche verte ",
L_VIEWICONTIPS_ELM_108: "Fl\u00e8che droite verte ",
L_VIEWICONTIPS_ELM_109: "Fl\u00e8che haut bleue ",
L_VIEWICONTIPS_ELM_11: "Informations ",
L_VIEWICONTIPS_ELM_110: "Fl\u00e8che bas bleue ",
L_VIEWICONTIPS_ELM_111: "Fl\u00e8che gauche bleue ",
L_VIEWICONTIPS_ELM_112: "Fl\u00e8che droite bleue ",
L_VIEWICONTIPS_ELM_113: "Affichage bleu ",
L_VIEWICONTIPS_ELM_114: "Balle verte ",
L_VIEWICONTIPS_ELM_115: "Balle rouge ",
L_VIEWICONTIPS_ELM_116: "Balle marron ",
L_VIEWICONTIPS_ELM_117: "Balle bleue ",
L_VIEWICONTIPS_ELM_118: "Balle bleu fonc\u00e9 ",
L_VIEWICONTIPS_ELM_119: "Balle violette ",
L_VIEWICONTIPS_ELM_12: "Ecriture de texte ",
L_VIEWICONTIPS_ELM_120: "Balle jaune ",
L_VIEWICONTIPS_ELM_121: "Enveloppe blanche ferm\u00e9e ",
L_VIEWICONTIPS_ELM_122: "Message envoy\u00e9 ",
L_VIEWICONTIPS_ELM_123: "Enveloppe bleue ferm\u00e9e ",
L_VIEWICONTIPS_ELM_124: "Enveloppe rouge ferm\u00e9e ",
L_VIEWICONTIPS_ELM_125: "Enveloppe blanche ouverte ",
L_VIEWICONTIPS_ELM_126: "Enveloppe jaune ouverte ",
L_VIEWICONTIPS_ELM_127: "Enveloppe bleue ouverte ",
L_VIEWICONTIPS_ELM_128: "Dos enveloppe rouge ",
L_VIEWICONTIPS_ELM_129: "Dos enveloppe blanche ",
L_VIEWICONTIPS_ELM_13: "Image ",
L_VIEWICONTIPS_ELM_130: "Dos enveloppe jaune ",
L_VIEWICONTIPS_ELM_131: "Dos enveloppe rouge ",
L_VIEWICONTIPS_ELM_132: "Invitation blanche ",
L_VIEWICONTIPS_ELM_133: "Invitation jaune ",
L_VIEWICONTIPS_ELM_134: "Invitation rouge ",
L_VIEWICONTIPS_ELM_135: "Lotus 123 ",
L_VIEWICONTIPS_ELM_136: "Document de traitement de texte ",
L_VIEWICONTIPS_ELM_137: "Pr\u00e9sentation ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "Cam\u00e9ra ",
L_VIEWICONTIPS_ELM_14: "Graphique ",
L_VIEWICONTIPS_ELM_140: "Document de flux de travail ",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_144: "Graphique sectoriel ",
L_VIEWICONTIPS_ELM_145: "Visio ",
L_VIEWICONTIPS_ELM_146: "Hiver ",
L_VIEWICONTIPS_ELM_147: "Printemps ",
L_VIEWICONTIPS_ELM_148: "Et\u00e9 ",
L_VIEWICONTIPS_ELM_149: "Automne ",
L_VIEWICONTIPS_ELM_15: "Son ",
L_VIEWICONTIPS_ELM_150: "Point d'exclamation ",
L_VIEWICONTIPS_ELM_151: "Num\u00e9ro 1 ",
L_VIEWICONTIPS_ELM_152: "Num\u00e9ro 2 ",
L_VIEWICONTIPS_ELM_153: "Num\u00e9ro 3 ",
L_VIEWICONTIPS_ELM_154: "Num\u00e9ro 4 ",
L_VIEWICONTIPS_ELM_155: "Num\u00e9ro 5 ",
L_VIEWICONTIPS_ELM_156: "Cuisine ",
L_VIEWICONTIPS_ELM_157: "Document inacceptable ",
L_VIEWICONTIPS_ELM_158: "R\u00e9union ",
L_VIEWICONTIPS_ELM_159: "Etoile d'or ",
L_VIEWICONTIPS_ELM_16: "Microphone ",
L_VIEWICONTIPS_ELM_160: "Rendez-vous ",
L_VIEWICONTIPS_ELM_161: "Gadget logiciel ",
L_VIEWICONTIPS_ELM_162: "Question ",
L_VIEWICONTIPS_ELM_163: "Confidentiel ",
L_VIEWICONTIPS_ELM_164: "Courrier chiffr\u00e9 ",
L_VIEWICONTIPS_ELM_165: "Verrou bleu ",
L_VIEWICONTIPS_ELM_166: "D\u00e9guis\u00e9 ",
L_VIEWICONTIPS_ELM_167: "Case \u00e0 cocher bleue ",
L_VIEWICONTIPS_ELM_168: "T\u00e2che en instance ",
L_VIEWICONTIPS_ELM_169: "M\u00e9daillon rouge ",
L_VIEWICONTIPS_ELM_17: "Image ",
L_VIEWICONTIPS_ELM_170: "M\u00e9daillon jaune ",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Avion ",
L_VIEWICONTIPS_ELM_174: "Voiture ",
L_VIEWICONTIPS_ELM_175: "Construction ",
L_VIEWICONTIPS_ELM_176: "Nouveau document ",
L_VIEWICONTIPS_ELM_177: "Ballon d'anniversaire ",
L_VIEWICONTIPS_ELM_178: "Message r\u00e9pondu ",
L_VIEWICONTIPS_ELM_179: "Message transf\u00e9r\u00e9 ",
L_VIEWICONTIPS_ELM_18: "Affichage vert ",
L_VIEWICONTIPS_ELM_180: "Message r\u00e9pondu et transf\u00e9r\u00e9 ",
L_VIEWICONTIPS_ELM_181: "Suivi haute priorit\u00e9.",
L_VIEWICONTIPS_ELM_182: "Suivi priorit\u00e9 normale.",
L_VIEWICONTIPS_ELM_183: "Suivi basse priorit\u00e9.",
L_VIEWICONTIPS_ELM_184: "N'envoyer qu'\u00e0 moi",
L_VIEWICONTIPS_ELM_185: "Envoyer \u00e0 moi et \u00e0 quelques personnes ",
L_VIEWICONTIPS_ELM_186: "Envoyer \u00e0 moi et \u00e0 de nombreuses personnes ",
L_VIEWICONTIPS_ELM_187: "Avis de r\u00e9union non trait\u00e9 ",
L_VIEWICONTIPS_ELM_188: "Message non lu ",
L_VIEWICONTIPS_ELM_189: "R\u00e9union en ligne ",
L_VIEWICONTIPS_ELM_19: "Table ",
L_VIEWICONTIPS_ELM_190: "Pertinence \u00e9lev\u00e9e ",
L_VIEWICONTIPS_ELM_191: "Pertinence moyenne ",
L_VIEWICONTIPS_ELM_192: "Pertinence faible ",
L_VIEWICONTIPS_ELM_193: "Aucune pertinence ",
L_VIEWICONTIPS_ELM_194: "Ev\u00e9nement sur une journ\u00e9e ",
L_VIEWICONTIPS_ELM_195: "Rappel ",
L_VIEWICONTIPS_ELM_196: "Replanifi\u00e9e ",
L_VIEWICONTIPS_ELM_197: "Refuser invitation ",
L_VIEWICONTIPS_ELM_198: "Contre-proposition ",
L_VIEWICONTIPS_ELM_199: "Anniversaire ",
L_VIEWICONTIPS_ELM_2: "Dossier ferm\u00e9 ",
L_VIEWICONTIPS_ELM_20: "Texte ",
L_VIEWICONTIPS_ELM_200: "R\u00e9union annul\u00e9e ",
L_VIEWICONTIPS_ELM_201: "Termin\u00e9 ",
L_VIEWICONTIPS_ELM_202: "Accept\u00e9 ",
L_VIEWICONTIPS_ELM_203: "Refus\u00e9 ",
L_VIEWICONTIPS_ELM_204: "Priorit\u00e9 \u00e9lev\u00e9e ",
L_VIEWICONTIPS_ELM_205: "Rendez-vous ",
L_VIEWICONTIPS_ELM_206: "Invitation priv\u00e9e ",
L_VIEWICONTIPS_ELM_207: "Plaisanterie",
L_VIEWICONTIPS_ELM_208: "Confidentiel ",
L_VIEWICONTIPS_ELM_209: "Personnel ",
L_VIEWICONTIPS_ELM_21: "Plusieurs documents ",
L_VIEWICONTIPS_ELM_210: "Invitation accept\u00e9e ",
L_VIEWICONTIPS_ELM_211: "Message lu ",
L_VIEWICONTIPS_ELM_212: "Nouvelle invitation ",
L_VIEWICONTIPS_ELM_22: "Deux documents ",
L_VIEWICONTIPS_ELM_23: "Nouvelles ",
L_VIEWICONTIPS_ELM_24: "Livre rouge ",
L_VIEWICONTIPS_ELM_25: "Carnet d'adresses ",
L_VIEWICONTIPS_ELM_26: "Livre ouvert ",
L_VIEWICONTIPS_ELM_27: "Livre ferm\u00e9 ",
L_VIEWICONTIPS_ELM_28: "Livre blanc ",
L_VIEWICONTIPS_ELM_29: "Page jaune d\u00e9chir\u00e9e ",
L_VIEWICONTIPS_ELM_3: "Personne ",
L_VIEWICONTIPS_ELM_30: "Page bleue d\u00e9chir\u00e9e ",
L_VIEWICONTIPS_ELM_31: "Ampoule allum\u00e9e ",
L_VIEWICONTIPS_ELM_32: "Ampoule \u00e9teinte ",
L_VIEWICONTIPS_ELM_33: "Rafra\u00eechir ",
L_VIEWICONTIPS_ELM_34: "Recherche document ",
L_VIEWICONTIPS_ELM_35: "Recherche document termin\u00e9e",
L_VIEWICONTIPS_ELM_36: "Document acceptable ",
L_VIEWICONTIPS_ELM_37: "Document termin\u00e9 ",
L_VIEWICONTIPS_ELM_38: "Probl\u00e8me de document ",
L_VIEWICONTIPS_ELM_39: "Question document ",
L_VIEWICONTIPS_ELM_4: "Groupe ",
L_VIEWICONTIPS_ELM_40: "Prudence document ",
L_VIEWICONTIPS_ELM_41: "Document jaune ",
L_VIEWICONTIPS_ELM_42: "Document r\u00e9ponse jaune",
L_VIEWICONTIPS_ELM_43: "Document r\u00e9ponse bleue ",
L_VIEWICONTIPS_ELM_44: "T\u00e9l\u00e9phone ",
L_VIEWICONTIPS_ELM_45: "T\u00e9l\u00e9phone actif ",
L_VIEWICONTIPS_ELM_46: "Terminal informatique ",
L_VIEWICONTIPS_ELM_47: "Fax ",
L_VIEWICONTIPS_ELM_48: "CD-ROM ",
L_VIEWICONTIPS_ELM_49: "Disquette ",
L_VIEWICONTIPS_ELM_5: "Pi\u00e8ce jointe ",
L_VIEWICONTIPS_ELM_50: "Disquette ",
L_VIEWICONTIPS_ELM_51: "Disque dur ",
L_VIEWICONTIPS_ELM_52: "R\u00e9seau ",
L_VIEWICONTIPS_ELM_53: "Ordinateur ",
L_VIEWICONTIPS_ELM_54: "Serveur ",
L_VIEWICONTIPS_ELM_55: "Connexion ",
L_VIEWICONTIPS_ELM_56: "Rechercher ",
L_VIEWICONTIPS_ELM_57: "Ecrire ",
L_VIEWICONTIPS_ELM_58: "Brouillon ",
L_VIEWICONTIPS_ELM_59: "Devise ",
L_VIEWICONTIPS_ELM_6: "Entrecrois\u00e9 ",
L_VIEWICONTIPS_ELM_60: "Monnaie ",
L_VIEWICONTIPS_ELM_61: "Touche ",
L_VIEWICONTIPS_ELM_62: "Verrou ",
L_VIEWICONTIPS_ELM_63: "Agenda ",
L_VIEWICONTIPS_ELM_64: "Horloge ",
L_VIEWICONTIPS_ELM_65: "Alarme ",
L_VIEWICONTIPS_ELM_66: "Volante ",
L_VIEWICONTIPS_ELM_67: "Satellite ",
L_VIEWICONTIPS_ELM_68: "Porte-documents ",
L_VIEWICONTIPS_ELM_69: "Accueil ",
L_VIEWICONTIPS_ELM_7: "Animal ",
L_VIEWICONTIPS_ELM_70: "Globe ",
L_VIEWICONTIPS_ELM_71: "Sant\u00e9 ",
L_VIEWICONTIPS_ELM_72: "Finance ",
L_VIEWICONTIPS_ELM_73: "Transport ",
L_VIEWICONTIPS_ELM_74: "Chimique ",
L_VIEWICONTIPS_ELM_75: "Fabrication ",
L_VIEWICONTIPS_ELM_76: "Utilitaires ",
L_VIEWICONTIPS_ELM_77: "T\u00e9l\u00e9communication ",
L_VIEWICONTIPS_ELM_78: "B\u00e4timent ",
L_VIEWICONTIPS_ELM_79: "Sablier ",
L_VIEWICONTIPS_ELM_8: "Recherche ",
L_VIEWICONTIPS_ELM_80: "Interdit ",
L_VIEWICONTIPS_ELM_81: "Rejet\u00e9 ",
L_VIEWICONTIPS_ELM_82: "Termin\u00e9 ",
L_VIEWICONTIPS_ELM_83: "Acceptable ",
L_VIEWICONTIPS_ELM_84: "Inacceptable ",
L_VIEWICONTIPS_ELM_85: "Joyeux ",
L_VIEWICONTIPS_ELM_86: "Indiff\u00e9rent ",
L_VIEWICONTIPS_ELM_87: "Triste ",
L_VIEWICONTIPS_ELM_88: "Ti\u00e8de ",
L_VIEWICONTIPS_ELM_89: "Chaud ",
L_VIEWICONTIPS_ELM_9: "Activit\u00e9 r\u00e9seau ",
L_VIEWICONTIPS_ELM_90: "Tr\u00e8s chaud ",
L_VIEWICONTIPS_ELM_91: "Bombe ",
L_VIEWICONTIPS_ELM_92: "Signe Stop ",
L_VIEWICONTIPS_ELM_93: "Stop ",
L_VIEWICONTIPS_ELM_94: "Prudence ",
L_VIEWICONTIPS_ELM_95: "Feu vert ",
L_VIEWICONTIPS_ELM_96: "Positif ",
L_VIEWICONTIPS_ELM_97: "N\u00e9gatif ",
L_VIEWICONTIPS_ELM_98: "Diamant rouge ",
L_VIEWICONTIPS_ELM_99: "Diamant vert ",
L_VIEWMAIL: "Courrier"
})
