({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM De yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM De yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Dia %1 - \u00faltimo dia no ano",
L_CAL_LAST_MONTH: "M\u00eas %1 - \u00faltimo m\u00eas no ano",
L_CAL_LAST_WEEK: "Semana %1 - \u00faltima semana no ano",
L_CAL_LEFT_DAY: "Dia %1 - restam %2 dias no ano",
L_CAL_LEFT_DAYS: "Dia %1 - restam %2 dias no ano",
L_CAL_LEFT_MONTH: "M\u00eas %1 - restam %2 meses no ano",
L_CAL_LEFT_MONTHS: "M\u00eas %1 - restam %2 meses no ano",
L_CAL_LEFT_WEEK: "Semana %1 - restam %2 semanas no ano",
L_CAL_LEFT_WEEKS: "Semana %1 - restam %2 semanas no ano",
L_CHARDAY_FRI: "S",
L_CHARDAY_MON: "S",
L_CHARDAY_SAT: "S",
L_CHARDAY_SUN: "D",
L_CHARDAY_THU: "Q",
L_CHARDAY_TUE: "T",
L_CHARDAY_WED: "Q",
L_NO_CAL_ENTRY_SELECTED: "Nenhuma entrada de agenda foi selecionada.  Selecione uma entrada e tente novamente.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "Nenhuma entrada na agenda de %1."
})
