({
L_CAL_NAV_PREVIOUS: "Anterior",
L_CAL_NAV_NEXT: "Pr\u00f3ximo",
L_CAL_NAV_MONTH: "M\u00eas",
L_CAL_HEADER_DAYS_WEEK: "Dias da semana",
L_CAL_HEADER: "Cabe\u00e7alho do calend\u00e1rio",
L_CAL_HEADER_DAY: "Cabe\u00e7alho do dia %1",
L_CAL_EVENT_ALLDAY: "Evento de dia inteiro %1",
L_CAL_NOENTRY: "Sem entradas",
L_CAL_GRID: "Grade de calend\u00e1rio",
L_CAL_PICKER_POPUP: "Popup do selecionador de data",
L_CAL_NAV_TIMESCALE_PREV_D: "Dia anterior",
L_CAL_NAV_TIMESCALE_NEXT_D: "Pr\u00f3ximo dia",
L_CAL_NAV_TIMESCALE_PREV_T: "Dois dias anteriores",
L_CAL_NAV_TIMESCALE_NEXT_T: "Pr\u00f3ximos dois dias",
L_CAL_NAV_TIMESCALE_PREV_F: "Semana de trabalho anterior",
L_CAL_NAV_TIMESCALE_NEXT_F: "Pr\u00f3xima semana de trabalho",
L_CAL_NAV_TIMESCALE_PREV_W: "Semana anterior",
L_CAL_NAV_TIMESCALE_NEXT_W: "Pr\u00f3xima semana",
L_CAL_NAV_TIMESCALE_PREV_2: "Quinzena anterior",
L_CAL_NAV_TIMESCALE_NEXT_2: "Pr\u00f3xima quinzena",
L_CAL_NAV_TIMESCALE_PREV_M: "M\u00eas anterior",
L_CAL_NAV_TIMESCALE_NEXT_M: "Pr\u00f3ximo m\u00eas",
L_CAL_NAV_TIMESCALE_PREV_Y: "Ano anterior",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Pr\u00f3ximo ano"
})
