({
L_CANCEL: "Cancel\u00b7la",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "No s'ha trobat l'entrada",
L_ERR_INVALIDDATE: "La data especificada no \u00e9s v\u00e0lida.",
L_FETCHING: "S'estan recuperant registres . . .",
L_FETCHINGNEXT: "S'est\u00e0 recuperant la p\u00e0gina seg\u00fcent de registres . . .",
L_FETCHINGPREV: "S'est\u00e0 recuperant la p\u00e0gina anterior de registres . . .",
L_JAWS_GIGABYTES: "%1 Gigabytes",
L_JAWS_KILOBYTES: "%1 Kilobytes",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Ordenat de manera ascendent",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 columna. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Ordenat de manera descendent",
L_JAWS_LISTVIEW_NOENTRY: "cap entrada seleccionada",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Premeu la tecla Intro per tornar a ordenar de manera ascendent",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Premeu la tecla Intro per tornar a ordenar de manera descendent",
L_JAWS_LISTVIEW_UNDORESORT: "Premeu la tecla Intro per desfer la reordenaci\u00f3",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 columna. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 de %3",
L_JAWS_MEGABYTES: "%1 Megabytes",
L_JAWS_TERABYTES: "%1 Terabytes",
L_NARROW_DEFAULT: "Ordena per defecte",
L_NARROW_NOTITLE: "Sense t\u00edtol",
L_NARROW_SORTBY: "Ordena per %1&nbsp;%2&nbsp;",
L_SEARCH: "Cerca",
L_STARTSWITH_COLUMN: "Seleccioneu la columna per la qual voleu ordenar:",
L_STARTSWITH_INVALID_NUMBER: "El n\u00famero especificat no \u00e9s v\u00e0lid",
L_STARTSWITH_SEARCH: "Cerca entrades que comencin per:",
L_STARTSWITH_TITLE: "Comen\u00e7a per...",
L_UPDATINGVIEW_MESSAGE: "\u00c9s possible que aquesta vista s'estigui actualitzant al servidor.\nEs mostrar\u00e0 quan finalitzi aquesta actualitzaci\u00f3.\nPodeu continuar treballant amb altres pestanyes o intentar accedir a altres vistes/carpetes.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "Document nou",
L_VIEWICONTIPS_ELM_10: "Recordatori",
L_VIEWICONTIPS_ELM_100: "Diamant blau",
L_VIEWICONTIPS_ELM_101: "Fletxa amunt vermella",
L_VIEWICONTIPS_ELM_102: "Fletxa avall vermella",
L_VIEWICONTIPS_ELM_103: "Fletxa esquerra vermella",
L_VIEWICONTIPS_ELM_104: "Fletxa dreta vermella",
L_VIEWICONTIPS_ELM_105: "Fletxa amunt verda",
L_VIEWICONTIPS_ELM_106: "Fletxa avall verda",
L_VIEWICONTIPS_ELM_107: "Fletxa esquerra verda",
L_VIEWICONTIPS_ELM_108: "Fletxa dreta verda",
L_VIEWICONTIPS_ELM_109: "Fletxa amunt blava",
L_VIEWICONTIPS_ELM_11: "Informaci\u00f3",
L_VIEWICONTIPS_ELM_110: "Fletxa avall blava",
L_VIEWICONTIPS_ELM_111: "Fletxa esquerra blava",
L_VIEWICONTIPS_ELM_112: "Fletxa dreta blava ",
L_VIEWICONTIPS_ELM_113: "Visualitzaci\u00f3 blava",
L_VIEWICONTIPS_ELM_114: "Pilot verda",
L_VIEWICONTIPS_ELM_115: "Pilota vermella",
L_VIEWICONTIPS_ELM_116: "Pilota marr\u00f3",
L_VIEWICONTIPS_ELM_117: "Pilota blava",
L_VIEWICONTIPS_ELM_118: "Pilota blau fosc",
L_VIEWICONTIPS_ELM_119: "Pilota porpra",
L_VIEWICONTIPS_ELM_12: "Escriu text",
L_VIEWICONTIPS_ELM_120: "Pilota groga",
L_VIEWICONTIPS_ELM_121: "Sobre blanc sense obrir",
L_VIEWICONTIPS_ELM_122: "Missatge enviat",
L_VIEWICONTIPS_ELM_123: "Sobre balu sense obrir",
L_VIEWICONTIPS_ELM_124: "Sobre vermell sense obrir",
L_VIEWICONTIPS_ELM_125: "Sobre blanc obert",
L_VIEWICONTIPS_ELM_126: "Sobre groc obert",
L_VIEWICONTIPS_ELM_127: "Sobre blau obert",
L_VIEWICONTIPS_ELM_128: "Dors del sobre vermell",
L_VIEWICONTIPS_ELM_129: "Dors del sobre blanc ",
L_VIEWICONTIPS_ELM_13: "Gr\u00e0fic",
L_VIEWICONTIPS_ELM_130: "Dors del sobre groc",
L_VIEWICONTIPS_ELM_131: "Dors del sobre vermell",
L_VIEWICONTIPS_ELM_132: "Invitaci\u00f3 blanca",
L_VIEWICONTIPS_ELM_133: "Invitaci\u00f3 groga",
L_VIEWICONTIPS_ELM_134: "Invitaci\u00f3 vermella",
L_VIEWICONTIPS_ELM_135: "Lotus 123 ",
L_VIEWICONTIPS_ELM_136: "Document de Word",
L_VIEWICONTIPS_ELM_137: "Presentaci\u00f3 ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "C\u00e0mara de v\u00eddeo",
L_VIEWICONTIPS_ELM_14: "Diagrama",
L_VIEWICONTIPS_ELM_140: "Document de fluxe de treball",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_144: "Diagrama circular",
L_VIEWICONTIPS_ELM_145: "Visi\u00f3 ",
L_VIEWICONTIPS_ELM_146: "Hivern",
L_VIEWICONTIPS_ELM_147: "Primavera",
L_VIEWICONTIPS_ELM_148: "Estiu",
L_VIEWICONTIPS_ELM_149: "Tardor",
L_VIEWICONTIPS_ELM_15: "So",
L_VIEWICONTIPS_ELM_150: "Signe d'exclamaci\u00f3",
L_VIEWICONTIPS_ELM_151: "N\u00famero 1",
L_VIEWICONTIPS_ELM_152: "N\u00famero 2",
L_VIEWICONTIPS_ELM_153: "N\u00famero 3",
L_VIEWICONTIPS_ELM_154: "N\u00famero 4",
L_VIEWICONTIPS_ELM_155: "N\u00famero 5",
L_VIEWICONTIPS_ELM_156: "Cocci\u00f3",
L_VIEWICONTIPS_ELM_157: "Document inacceptable ",
L_VIEWICONTIPS_ELM_158: "Reuni\u00f3",
L_VIEWICONTIPS_ELM_159: "Estrella daurada",
L_VIEWICONTIPS_ELM_16: "Micr\u00f2fon",
L_VIEWICONTIPS_ELM_160: "Cita",
L_VIEWICONTIPS_ELM_161: "Widget",
L_VIEWICONTIPS_ELM_162: "Pregunta",
L_VIEWICONTIPS_ELM_163: "Confidencial",
L_VIEWICONTIPS_ELM_164: "Correu xifrat",
L_VIEWICONTIPS_ELM_165: "Cadenat blau ",
L_VIEWICONTIPS_ELM_166: "Amagat",
L_VIEWICONTIPS_ELM_167: "Marca de selecci\u00f3 blava",
L_VIEWICONTIPS_ELM_168: "Tasques",
L_VIEWICONTIPS_ELM_169: "Medall\u00f3 vermell",
L_VIEWICONTIPS_ELM_17: "Gr\u00e0fica",
L_VIEWICONTIPS_ELM_170: "Medall\u00f3 groc",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Avi\u00f3 ",
L_VIEWICONTIPS_ELM_174: "Cotxe",
L_VIEWICONTIPS_ELM_175: "Edifici",
L_VIEWICONTIPS_ELM_176: "Document nou",
L_VIEWICONTIPS_ELM_177: "Globus",
L_VIEWICONTIPS_ELM_178: "S'ha respost el missatge a",
L_VIEWICONTIPS_ELM_179: "S'ha rem\u00e8s el missatge",
L_VIEWICONTIPS_ELM_18: "Visualitzaci\u00f3 verda",
L_VIEWICONTIPS_ELM_180: "S'ha respost i rem\u00e8s el missatge",
L_VIEWICONTIPS_ELM_181: "Seguiment de prioritat alta.",
L_VIEWICONTIPS_ELM_182: "Seguiment de prioritat normal.",
L_VIEWICONTIPS_ELM_183: "Seguiment de prioritat baixa.",
L_VIEWICONTIPS_ELM_184: "Enviat nom\u00e9s a mi",
L_VIEWICONTIPS_ELM_185: "Enviat a mi i a certes persones",
L_VIEWICONTIPS_ELM_186: "Enviat a mi i a moltes persones ",
L_VIEWICONTIPS_ELM_187: "Av\u00eds de reuni\u00f3 sense processar",
L_VIEWICONTIPS_ELM_188: "Missatge sense llegir",
L_VIEWICONTIPS_ELM_189: "Reuni\u00f3 en l\u00ednia ",
L_VIEWICONTIPS_ELM_19: "Taula",
L_VIEWICONTIPS_ELM_190: "Import\u00e0ncia alta ",
L_VIEWICONTIPS_ELM_191: "Import\u00e0ncia mitja ",
L_VIEWICONTIPS_ELM_192: "Import\u00e0ncia baixa ",
L_VIEWICONTIPS_ELM_193: "Sense import\u00e0ncia ",
L_VIEWICONTIPS_ELM_194: "Esdeveniment de tot el dia ",
L_VIEWICONTIPS_ELM_195: "Recordatori ",
L_VIEWICONTIPS_ELM_196: "Replanificat ",
L_VIEWICONTIPS_ELM_197: "Rebutja la invitaci\u00f3 ",
L_VIEWICONTIPS_ELM_198: "Invitaci\u00f3 amb contraproposta ",
L_VIEWICONTIPS_ELM_199: "Aniversari ",
L_VIEWICONTIPS_ELM_2: "Carpeta sense obrir",
L_VIEWICONTIPS_ELM_20: "Text",
L_VIEWICONTIPS_ELM_200: "Reuni\u00f3 cancel\u00b7lada ",
L_VIEWICONTIPS_ELM_201: "Tasca acabada ",
L_VIEWICONTIPS_ELM_202: "Acceptat ",
L_VIEWICONTIPS_ELM_203: "Rebutjat ",
L_VIEWICONTIPS_ELM_204: "Prioritat alta ",
L_VIEWICONTIPS_ELM_205: "Cita ",
L_VIEWICONTIPS_ELM_206: "Invitaci\u00f3 privada ",
L_VIEWICONTIPS_ELM_207: "Emoticona d'acudit ",
L_VIEWICONTIPS_ELM_208: "Emoticona confidencial ",
L_VIEWICONTIPS_ELM_209: "Emoticona personal ",
L_VIEWICONTIPS_ELM_21: "Diversos documents",
L_VIEWICONTIPS_ELM_210: "Invitaci\u00f3 acceptada ",
L_VIEWICONTIPS_ELM_211: "Llegeix missatge ",
L_VIEWICONTIPS_ELM_212: "Invitaci\u00f3 nova ",
L_VIEWICONTIPS_ELM_22: "Dos documents",
L_VIEWICONTIPS_ELM_23: "Not\u00edcies",
L_VIEWICONTIPS_ELM_24: "Llibreta vermella",
L_VIEWICONTIPS_ELM_25: "Llibreta d'adreces",
L_VIEWICONTIPS_ELM_26: "Llibreta oberta",
L_VIEWICONTIPS_ELM_27: "Llibreta tancada",
L_VIEWICONTIPS_ELM_28: "Llibreta groga",
L_VIEWICONTIPS_ELM_29: "P\u00e0gina groga estripada",
L_VIEWICONTIPS_ELM_3: "Persona",
L_VIEWICONTIPS_ELM_30: "P\u00e0gina blava estripada",
L_VIEWICONTIPS_ELM_31: "Bombeta encesa",
L_VIEWICONTIPS_ELM_32: "Bombeta apagada",
L_VIEWICONTIPS_ELM_33: "Actualitza",
L_VIEWICONTIPS_ELM_34: "Cerca document",
L_VIEWICONTIPS_ELM_35: "Cerca document completat",
L_VIEWICONTIPS_ELM_36: "Document acceptable",
L_VIEWICONTIPS_ELM_37: "Document complet",
L_VIEWICONTIPS_ELM_38: "Problema del document",
L_VIEWICONTIPS_ELM_39: "Q\u00fcesti\u00f3 del document",
L_VIEWICONTIPS_ELM_4: "Grup",
L_VIEWICONTIPS_ELM_40: "Atenci\u00f3 del document",
L_VIEWICONTIPS_ELM_41: "Document groc",
L_VIEWICONTIPS_ELM_42: "Resposta al document groc",
L_VIEWICONTIPS_ELM_43: "Resposta al document blau",
L_VIEWICONTIPS_ELM_44: "Tel\u00e8fon",
L_VIEWICONTIPS_ELM_45: "Tel\u00e8fon actiu",
L_VIEWICONTIPS_ELM_46: "Terminal inform\u00e0tic",
L_VIEWICONTIPS_ELM_47: "Fax",
L_VIEWICONTIPS_ELM_48: "CD-ROM",
L_VIEWICONTIPS_ELM_49: "Disquet",
L_VIEWICONTIPS_ELM_5: "Adjunci\u00f3",
L_VIEWICONTIPS_ELM_50: "Disc flexible",
L_VIEWICONTIPS_ELM_51: "Disc dur",
L_VIEWICONTIPS_ELM_52: "Xarxa",
L_VIEWICONTIPS_ELM_53: "Ordinador",
L_VIEWICONTIPS_ELM_54: "Servidor",
L_VIEWICONTIPS_ELM_55: "Connexi\u00f3",
L_VIEWICONTIPS_ELM_56: "Troba",
L_VIEWICONTIPS_ELM_57: "Escriu",
L_VIEWICONTIPS_ELM_58: "Esborrany",
L_VIEWICONTIPS_ELM_59: "Divisa",
L_VIEWICONTIPS_ELM_6: "Vinculat",
L_VIEWICONTIPS_ELM_60: "Monedes",
L_VIEWICONTIPS_ELM_61: "Clau",
L_VIEWICONTIPS_ELM_62: "Cadenat",
L_VIEWICONTIPS_ELM_63: "Calendari",
L_VIEWICONTIPS_ELM_64: "Rellotge",
L_VIEWICONTIPS_ELM_65: "Alarma",
L_VIEWICONTIPS_ELM_66: "Volant",
L_VIEWICONTIPS_ELM_67: "Sat\u00e8l\u00b7lit",
L_VIEWICONTIPS_ELM_68: "Cartera",
L_VIEWICONTIPS_ELM_69: "Inici",
L_VIEWICONTIPS_ELM_7: "Animal",
L_VIEWICONTIPS_ELM_70: "Globus",
L_VIEWICONTIPS_ELM_71: "Salut",
L_VIEWICONTIPS_ELM_72: "Finances",
L_VIEWICONTIPS_ELM_73: "Transport",
L_VIEWICONTIPS_ELM_74: "Qu\u00edmica",
L_VIEWICONTIPS_ELM_75: "Manufactura",
L_VIEWICONTIPS_ELM_76: "Utilitats",
L_VIEWICONTIPS_ELM_77: "Telecomunicaci\u00f3",
L_VIEWICONTIPS_ELM_78: "Construcci\u00f3 ",
L_VIEWICONTIPS_ELM_79: "Rellotge d'arena",
L_VIEWICONTIPS_ELM_8: "Cerca",
L_VIEWICONTIPS_ELM_80: "Prohibit",
L_VIEWICONTIPS_ELM_81: "Rebutjat",
L_VIEWICONTIPS_ELM_82: "Completat",
L_VIEWICONTIPS_ELM_83: "Acceptable",
L_VIEWICONTIPS_ELM_84: "Inacceptable",
L_VIEWICONTIPS_ELM_85: "Feli\u00e7",
L_VIEWICONTIPS_ELM_86: "Indiferent ",
L_VIEWICONTIPS_ELM_87: "Trist ",
L_VIEWICONTIPS_ELM_88: "Tebi",
L_VIEWICONTIPS_ELM_89: "Calent",
L_VIEWICONTIPS_ELM_9: "Activitat de xarxa",
L_VIEWICONTIPS_ELM_90: "Molt calent",
L_VIEWICONTIPS_ELM_91: "Bomba ",
L_VIEWICONTIPS_ELM_92: "Senyal d'aturada",
L_VIEWICONTIPS_ELM_93: "Aturada",
L_VIEWICONTIPS_ELM_94: "Precauci\u00f3",
L_VIEWICONTIPS_ELM_95: "V\u00e9s-hi",
L_VIEWICONTIPS_ELM_96: "Positiu",
L_VIEWICONTIPS_ELM_97: "Negatiu",
L_VIEWICONTIPS_ELM_98: "Diamant vermell ",
L_VIEWICONTIPS_ELM_99: "Diamant verd",
L_VIEWMAIL: "Correu"
})
