({
L_CAL_NAV_PREVIOUS: "\u00d6nceki",
L_CAL_NAV_NEXT: "Sonraki",
L_CAL_NAV_MONTH: "Ay",
L_CAL_HEADER_DAYS_WEEK: "Haftan\u0131n g\u00fcnleri",
L_CAL_HEADER: "Takvim \u00fcstbilgisi",
L_CAL_HEADER_DAY: "G\u00fcn \u00fcstbilgisi %1",
L_CAL_EVENT_ALLDAY: "Tam g\u00fcnl\u00fck olay %1",
L_CAL_NOENTRY: "Girdi yok",
L_CAL_GRID: "Takvim \u0131zgaras\u0131",
L_CAL_PICKER_POPUP: "Tarih se\u00e7ici a\u00e7\u0131lan penceresi",
L_CAL_NAV_TIMESCALE_PREV_D: "\u00d6nceki g\u00fcn",
L_CAL_NAV_TIMESCALE_NEXT_D: "Sonraki g\u00fcn",
L_CAL_NAV_TIMESCALE_PREV_T: "\u00d6nceki iki g\u00fcn",
L_CAL_NAV_TIMESCALE_NEXT_T: "Sonraki iki g\u00fcn",
L_CAL_NAV_TIMESCALE_PREV_F: "\u00d6nceki i\u015f haftas\u0131",
L_CAL_NAV_TIMESCALE_NEXT_F: "Sonraki i\u015f haftas\u0131",
L_CAL_NAV_TIMESCALE_PREV_W: "\u00d6nceki hafta",
L_CAL_NAV_TIMESCALE_NEXT_W: "Sonraki hafta",
L_CAL_NAV_TIMESCALE_PREV_2: "\u00d6nceki iki hafta",
L_CAL_NAV_TIMESCALE_NEXT_2: "Sonraki iki hafta",
L_CAL_NAV_TIMESCALE_PREV_M: "\u00d6nceki ay",
L_CAL_NAV_TIMESCALE_NEXT_M: "Sonraki ay",
L_CAL_NAV_TIMESCALE_PREV_Y: "\u00d6nceki y\u0131l",
L_CAL_NAV_TIMESCALE_NEXT_Y: "sonraki y\u0131l"
})
