({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM de yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM de yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Dia %1 - \u00faltimo dia do ano",
L_CAL_LAST_MONTH: "M\u00eas %1 - \u00faltimo m\u00eas do ano",
L_CAL_LAST_WEEK: "Semana %1 - \u00faltima semana do ano",
L_CAL_LEFT_DAY: "Dia %1 - %2 dia restante no ano",
L_CAL_LEFT_DAYS: "Dia %1 - %2 dias restantes no ano",
L_CAL_LEFT_MONTH: "M\u00eas %1 - %2 m\u00eas restante no ano",
L_CAL_LEFT_MONTHS: "M\u00eas %1 - %2 meses restantes no ano",
L_CAL_LEFT_WEEK: "Semana %1 - %2 semana restante no ano",
L_CAL_LEFT_WEEKS: "Semana %1 - %2 semanas restantes no ano",
L_CHARDAY_FRI: "S",
L_CHARDAY_MON: "S",
L_CHARDAY_SAT: "S",
L_CHARDAY_SUN: "D",
L_CHARDAY_THU: "Q",
L_CHARDAY_TUE: "T",
L_CHARDAY_WED: "Q",
L_NO_CAL_ENTRY_SELECTED: "N\u00e3o foi seleccionada nenhuma entrada de Agenda.  Seleccione uma entrada e tente de novo.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "Nenhuma entrada da agenda para %1."
})
