({
L_CAL_NAV_PREVIOUS: "Anterior",
L_CAL_NAV_NEXT: "Seguinte",
L_CAL_NAV_MONTH: "M\u00eas",
L_CAL_HEADER_DAYS_WEEK: "Dias da semana",
L_CAL_HEADER: "Cabe\u00e7alho da agenda",
L_CAL_HEADER_DAY: "Cabe\u00e7alho do dia %1",
L_CAL_EVENT_ALLDAY: "Evento para todo o dia %1",
L_CAL_NOENTRY: "Sem entradas",
L_CAL_GRID: "Grelha da agenda",
L_CAL_PICKER_POPUP: "Janela instant\u00e2nea de selector de data",
L_CAL_NAV_TIMESCALE_PREV_D: "Dia anterior",
L_CAL_NAV_TIMESCALE_NEXT_D: "Dia seguinte",
L_CAL_NAV_TIMESCALE_PREV_T: "Dois dias anteriores",
L_CAL_NAV_TIMESCALE_NEXT_T: "Dois dias seguintes",
L_CAL_NAV_TIMESCALE_PREV_F: "Dia \u00fatil anterior",
L_CAL_NAV_TIMESCALE_NEXT_F: "Dia \u00fatil seguinte",
L_CAL_NAV_TIMESCALE_PREV_W: "Semana anterior",
L_CAL_NAV_TIMESCALE_NEXT_W: "Semana seguinte",
L_CAL_NAV_TIMESCALE_PREV_2: "Duas semanas anteriores",
L_CAL_NAV_TIMESCALE_NEXT_2: "Duas semanas seguintes",
L_CAL_NAV_TIMESCALE_PREV_M: "M\u00eas anterior",
L_CAL_NAV_TIMESCALE_NEXT_M: "M\u00eas seguinte",
L_CAL_NAV_TIMESCALE_PREV_Y: "Ano anterior",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Ano seguinte"
})
