({
D_DIR_DEFAULT: "ltr",
D_GIGABYTES: "%1G",
D_KILOBYTES: "%1K",
D_MEGABYTES: "%1M",
D_NUMFMT_DECIMALSYMBOL: ".",
D_NUMFMT_THOUSANDSSEPARATOR: ",",
D_PADDING_REVERSE: "padding-right",
D_TERABYTES: "%1T"
})
