({
L_CANCEL: "Annulla",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Voce non trovata",
L_ERR_INVALIDDATE: "Data specificata non valida.",
L_FETCHING: "Richiamo record. . .",
L_FETCHINGNEXT: "Richiamo successiva pagina di record. . .",
L_FETCHINGPREV: "Richiamo precedente pagina di record. . .",
L_JAWS_GIGABYTES: "%1Gigabyte",
L_JAWS_KILOBYTES: "%1Kirobyte",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Ordinato in senso ascendente",
L_JAWS_LISTVIEW_COLUMN: "Colonna %1 %2. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Ordinato in senso discendente",
L_JAWS_LISTVIEW_NOENTRY: "nessuna voce selezionata",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Premere invio per riordinare in senso ascendente",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Premere invio per riordinare in senso discendente",
L_JAWS_LISTVIEW_UNDORESORT: "Premere invio per annullare il riordinamento",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "colonna %1. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 di %3",
L_JAWS_MEGABYTES: "%1Megabyte",
L_JAWS_TERABYTES: "%1Terabyte",
L_NARROW_DEFAULT: "Ordina per impostazione predefinita",
L_NARROW_NOTITLE: "Nessun titolo",
L_NARROW_SORTBY: "Ordina per %1",
L_SEARCH: "Cerca",
L_STARTSWITH_COLUMN: "Scegliere la colonna per l'ordinamento:",
L_STARTSWITH_INVALID_NUMBER: "Specificato numero non valido",
L_STARTSWITH_SEARCH: "Ricerca voci che iniziano con:",
L_STARTSWITH_TITLE: "Inizia con...",
L_UPDATINGVIEW_MESSAGE: "Probabilmente \u00e8 in corso l\'aggiornamento della vista sul server.\nApparir\u00e0 non appena l\'aggrionamento sar\u00e0 completo.\nSi pu\u00f2 continuare a lavorare con le altre schede o provare ad accedere ad altre viste o cartelle.",
L_VIEWICONTIPS_ELM_0: ",",
L_VIEWICONTIPS_ELM_1: ",",
L_VIEWICONTIPS_ELM_10: ",",
L_VIEWICONTIPS_ELM_100: "Freccia su rossa ",
L_VIEWICONTIPS_ELM_101: "Freccia gi\u00f9 rossa ",
L_VIEWICONTIPS_ELM_102: "Freccia sinistra rossa ",
L_VIEWICONTIPS_ELM_103: "Freccia destra rossa ",
L_VIEWICONTIPS_ELM_104: "Freccia su verde ",
L_VIEWICONTIPS_ELM_105: "Freccia gi\u00f9 verde ",
L_VIEWICONTIPS_ELM_106: "Freccia sinistra verde ",
L_VIEWICONTIPS_ELM_107: "Freccia destra verde ",
L_VIEWICONTIPS_ELM_108: "Freccia su blu ",
L_VIEWICONTIPS_ELM_109: "Freccia gi\u00f9 blu ",
L_VIEWICONTIPS_ELM_11: ",",
L_VIEWICONTIPS_ELM_110: "Freccia sinistra blu ",
L_VIEWICONTIPS_ELM_111: "Freccia destra blu ",
L_VIEWICONTIPS_ELM_112: "Schermo blu ",
L_VIEWICONTIPS_ELM_113: "Pallino verde ",
L_VIEWICONTIPS_ELM_114: "Pallino rosso ",
L_VIEWICONTIPS_ELM_115: "Pallino marrone ",
L_VIEWICONTIPS_ELM_116: "Pallino blu ",
L_VIEWICONTIPS_ELM_117: "Pallino blu scuro ",
L_VIEWICONTIPS_ELM_118: "Pallino porpora ",
L_VIEWICONTIPS_ELM_119: "Pallino giallo ",
L_VIEWICONTIPS_ELM_12: ",",
L_VIEWICONTIPS_ELM_120: "Busta bianca chiusa ",
L_VIEWICONTIPS_ELM_121: "Messaggio inviato ",
L_VIEWICONTIPS_ELM_122: "Busta blu chiusa ",
L_VIEWICONTIPS_ELM_123: "Busta rossa chiusa ",
L_VIEWICONTIPS_ELM_124: "Busta bianca aperta ",
L_VIEWICONTIPS_ELM_125: "Busta gialla aperta ",
L_VIEWICONTIPS_ELM_126: "Busta blu aperta ",
L_VIEWICONTIPS_ELM_127: "Busta rossa aperta ",
L_VIEWICONTIPS_ELM_128: "Busta bianca retro ",
L_VIEWICONTIPS_ELM_129: "Busta gialla retro ",
L_VIEWICONTIPS_ELM_13: ",",
L_VIEWICONTIPS_ELM_130: "Busta rossa retro ",
L_VIEWICONTIPS_ELM_131: "Invito bianco ",
L_VIEWICONTIPS_ELM_132: "Invito giallo ",
L_VIEWICONTIPS_ELM_133: "Invito rosso ",
L_VIEWICONTIPS_ELM_134: "Lotus 123 ",
L_VIEWICONTIPS_ELM_135: "Documento word processing ",
L_VIEWICONTIPS_ELM_136: "Presentazione ",
L_VIEWICONTIPS_ELM_137: "Lotus Approach ",
L_VIEWICONTIPS_ELM_138: "Videocamera ",
L_VIEWICONTIPS_ELM_139: "Documento workflow ",
L_VIEWICONTIPS_ELM_14: ",",
L_VIEWICONTIPS_ELM_140: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_141: "Microsoft Word ",
L_VIEWICONTIPS_ELM_142: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_143: "Grafico a torta ",
L_VIEWICONTIPS_ELM_144: "Visio ",
L_VIEWICONTIPS_ELM_145: "Inverno ",
L_VIEWICONTIPS_ELM_146: "Primavera ",
L_VIEWICONTIPS_ELM_147: "Estate ",
L_VIEWICONTIPS_ELM_148: "Autunno ",
L_VIEWICONTIPS_ELM_149: "Punto esclamativo ",
L_VIEWICONTIPS_ELM_15: ",",
L_VIEWICONTIPS_ELM_150: "Numero 1 ",
L_VIEWICONTIPS_ELM_151: "Numero 2 ",
L_VIEWICONTIPS_ELM_152: "Numero 3 ",
L_VIEWICONTIPS_ELM_153: "Numero 4 ",
L_VIEWICONTIPS_ELM_154: "Numero 5 ",
L_VIEWICONTIPS_ELM_155: "Cucina ",
L_VIEWICONTIPS_ELM_156: "Documento inaccettabile ",
L_VIEWICONTIPS_ELM_157: "Riunione ",
L_VIEWICONTIPS_ELM_158: "Stella dorata ",
L_VIEWICONTIPS_ELM_159: "Appuntamento ",
L_VIEWICONTIPS_ELM_16: ",",
L_VIEWICONTIPS_ELM_160: "Widget ",
L_VIEWICONTIPS_ELM_161: "Domanda ",
L_VIEWICONTIPS_ELM_162: "Confidenziale ",
L_VIEWICONTIPS_ELM_163: "Posta cifrata ",
L_VIEWICONTIPS_ELM_164: "Lucchetto blu ",
L_VIEWICONTIPS_ELM_165: "Travestimento ",
L_VIEWICONTIPS_ELM_166: "Segno di spunta blu ",
L_VIEWICONTIPS_ELM_167: "Attivit\u00e0 ",
L_VIEWICONTIPS_ELM_168: "Medaglione rosso ",
L_VIEWICONTIPS_ELM_169: "Medaglione giallo ",
L_VIEWICONTIPS_ELM_17: ",",
L_VIEWICONTIPS_ELM_170: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_171: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_172: "Aeroplano ",
L_VIEWICONTIPS_ELM_173: "Auto ",
L_VIEWICONTIPS_ELM_174: "Edificio ",
L_VIEWICONTIPS_ELM_175: "Nuovo documento ",
L_VIEWICONTIPS_ELM_176: "Palloncino ",
L_VIEWICONTIPS_ELM_177: "Risposta messaggio a ",
L_VIEWICONTIPS_ELM_178: "Messaggio inoltrato ",
L_VIEWICONTIPS_ELM_179: "Risposta e inoltro messaggio ",
L_VIEWICONTIPS_ELM_18: ",",
L_VIEWICONTIPS_ELM_180: "Completa con alta priorit\u00e0.",
L_VIEWICONTIPS_ELM_181: "Completa con priorit\u00e0 normale.",
L_VIEWICONTIPS_ELM_182: "Completa con bassa priorit\u00e0.",
L_VIEWICONTIPS_ELM_183: "Inviato solo a me ",
L_VIEWICONTIPS_ELM_184: "Inviato a me e a pochi altri ",
L_VIEWICONTIPS_ELM_185: "Inviato a me e a molti altri ",
L_VIEWICONTIPS_ELM_186: "Avviso di riunione non elaborato ",
L_VIEWICONTIPS_ELM_187: "Messaggio non letto ",
L_VIEWICONTIPS_ELM_188: "Riunione on-line ",
L_VIEWICONTIPS_ELM_189: "Molto rilevante ",
L_VIEWICONTIPS_ELM_19: ",",
L_VIEWICONTIPS_ELM_190: "Mediamente rilevante ",
L_VIEWICONTIPS_ELM_191: "Poco rilevante ",
L_VIEWICONTIPS_ELM_192: "Non rilevante ",
L_VIEWICONTIPS_ELM_193: "Evento di un giorno ",
L_VIEWICONTIPS_ELM_194: "Promemoria ",
L_VIEWICONTIPS_ELM_195: "Ripianificata ",
L_VIEWICONTIPS_ELM_196: "Declina invito ",
L_VIEWICONTIPS_ELM_197: "Controproposta all\'invito ",
L_VIEWICONTIPS_ELM_198: "Anniversario ",
L_VIEWICONTIPS_ELM_199: "Riunione annullata ",
L_VIEWICONTIPS_ELM_2: ",",
L_VIEWICONTIPS_ELM_20: ",",
L_VIEWICONTIPS_ELM_200: "Attivit\u00e0 completata ",
L_VIEWICONTIPS_ELM_201: "Accettata ",
L_VIEWICONTIPS_ELM_202: "Declinata ",
L_VIEWICONTIPS_ELM_203: "Alta priorit\u00e0 ",
L_VIEWICONTIPS_ELM_204: "Appuntamento ",
L_VIEWICONTIPS_ELM_205: "Invito privato ",
L_VIEWICONTIPS_ELM_206: "Emoticon scherzo ",
L_VIEWICONTIPS_ELM_207: "Emoticon confidenziale ",
L_VIEWICONTIPS_ELM_208: "Emoticon personale ",
L_VIEWICONTIPS_ELM_209: "Invito accettato ",
L_VIEWICONTIPS_ELM_21: ",",
L_VIEWICONTIPS_ELM_210: "Messaggio letto ",
L_VIEWICONTIPS_ELM_211: "Nuovo invito ",
L_VIEWICONTIPS_ELM_22: ",",
L_VIEWICONTIPS_ELM_23: ",",
L_VIEWICONTIPS_ELM_24: ",",
L_VIEWICONTIPS_ELM_25: ",",
L_VIEWICONTIPS_ELM_26: ",",
L_VIEWICONTIPS_ELM_27: ",",
L_VIEWICONTIPS_ELM_28: ",",
L_VIEWICONTIPS_ELM_29: "Pagina blu strappata ",
L_VIEWICONTIPS_ELM_3: ",",
L_VIEWICONTIPS_ELM_30: "Lampadina accesa ",
L_VIEWICONTIPS_ELM_31: "Lampadina spenta ",
L_VIEWICONTIPS_ELM_32: "Aggiorna ",
L_VIEWICONTIPS_ELM_33: "Ricerca documento ",
L_VIEWICONTIPS_ELM_34: "Ricerca documento completata ",
L_VIEWICONTIPS_ELM_35: "Documento accettabile ",
L_VIEWICONTIPS_ELM_36: "Documento completo ",
L_VIEWICONTIPS_ELM_37: "Documento con problema ",
L_VIEWICONTIPS_ELM_38: "Domanda sul documento ",
L_VIEWICONTIPS_ELM_39: "Documento attenzione ",
L_VIEWICONTIPS_ELM_4: ",",
L_VIEWICONTIPS_ELM_40: "Documento giallo ",
L_VIEWICONTIPS_ELM_41: "Documento risposta giallo ",
L_VIEWICONTIPS_ELM_42: "Documento risposta blu ",
L_VIEWICONTIPS_ELM_43: "Telefono ",
L_VIEWICONTIPS_ELM_44: "Telefono attivo ",
L_VIEWICONTIPS_ELM_45: "Terminale di computer ",
L_VIEWICONTIPS_ELM_46: "Fax ",
L_VIEWICONTIPS_ELM_47: "CD-ROM ",
L_VIEWICONTIPS_ELM_48: "Floppy disk ",
L_VIEWICONTIPS_ELM_49: "Dischetto ",
L_VIEWICONTIPS_ELM_5: ",",
L_VIEWICONTIPS_ELM_50: "Disco rigido ",
L_VIEWICONTIPS_ELM_51: "Rete ",
L_VIEWICONTIPS_ELM_52: "Computer ",
L_VIEWICONTIPS_ELM_53: "Server ",
L_VIEWICONTIPS_ELM_54: "Connessione ",
L_VIEWICONTIPS_ELM_55: "Trova ",
L_VIEWICONTIPS_ELM_56: "Scrivi ",
L_VIEWICONTIPS_ELM_57: "Bozza ",
L_VIEWICONTIPS_ELM_58: "Valuta ",
L_VIEWICONTIPS_ELM_59: "Monete ",
L_VIEWICONTIPS_ELM_6: ",",
L_VIEWICONTIPS_ELM_60: "Chiave ",
L_VIEWICONTIPS_ELM_61: "Lucchetto ",
L_VIEWICONTIPS_ELM_62: "Calendario",
L_VIEWICONTIPS_ELM_63: "Orologio ",
L_VIEWICONTIPS_ELM_64: "Sveglia ",
L_VIEWICONTIPS_ELM_65: "Volo ",
L_VIEWICONTIPS_ELM_66: "Satellite ",
L_VIEWICONTIPS_ELM_67: "Valigetta ",
L_VIEWICONTIPS_ELM_68: "Casa ",
L_VIEWICONTIPS_ELM_69: "Globo ",
L_VIEWICONTIPS_ELM_7: ",",
L_VIEWICONTIPS_ELM_70: "Salute ",
L_VIEWICONTIPS_ELM_71: "Finanza ",
L_VIEWICONTIPS_ELM_72: "Trasporti ",
L_VIEWICONTIPS_ELM_73: "Chimica ",
L_VIEWICONTIPS_ELM_74: "Industria ",
L_VIEWICONTIPS_ELM_75: "Servizi ",
L_VIEWICONTIPS_ELM_76: "Telecomunicazioni ",
L_VIEWICONTIPS_ELM_77: "Edilizia ",
L_VIEWICONTIPS_ELM_78: "Clessidra ",
L_VIEWICONTIPS_ELM_79: "Scartato ",
L_VIEWICONTIPS_ELM_8: ",",
L_VIEWICONTIPS_ELM_80: "Rifiutato ",
L_VIEWICONTIPS_ELM_81: "Completato ",
L_VIEWICONTIPS_ELM_82: "Accettabile ",
L_VIEWICONTIPS_ELM_83: "Inaccettabile ",
L_VIEWICONTIPS_ELM_84: "Felice ",
L_VIEWICONTIPS_ELM_85: "Indifferente ",
L_VIEWICONTIPS_ELM_86: "Triste ",
L_VIEWICONTIPS_ELM_87: "Tiepido ",
L_VIEWICONTIPS_ELM_88: "Caldo ",
L_VIEWICONTIPS_ELM_89: "Molto caldo ",
L_VIEWICONTIPS_ELM_9: ",",
L_VIEWICONTIPS_ELM_90: "Bomba ",
L_VIEWICONTIPS_ELM_91: "Segnale di Stop ",
L_VIEWICONTIPS_ELM_92: "Stop ",
L_VIEWICONTIPS_ELM_93: "Attenzione ",
L_VIEWICONTIPS_ELM_94: "Vai ",
L_VIEWICONTIPS_ELM_95: "Positivo ",
L_VIEWICONTIPS_ELM_96: "Negativo ",
L_VIEWICONTIPS_ELM_97: "Losanga rossa ",
L_VIEWICONTIPS_ELM_98: "Losanga verde ",
L_VIEWICONTIPS_ELM_99: "Losanga blu ",
L_VIEWMAIL: "Posta"
})
