/*
 * © Copyright IBM Corp. 2013
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at:
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing 
 * permissions and limitations under the License.
 */
/*
* Author: Maire Kehoe (mkehoe@ie.ibm.com)
* Date: 23 Jan 2012
* ExtlibSinceVersionNullList.java
*/
package xsp.extlib.test.version;

import com.ibm.commons.util.StringUtil;
import com.ibm.xsp.test.framework.version.SinceVersionList;

/**
 * Note, this file was generated in an 8.5.3_UP1 stream - do not overwrite it
 * with content from UP2 or later.
 * 
 * @author Maire Kehoe (mkehoe@ie.ibm.com)
 */
public class ExtlibSinceVersionNullList implements SinceVersionList {
    private Object[][] tagsAndProps = new Object[][]{
            // new Object[]{"prefixedTagName", newTagThisVersion, new String[]{
            //    "propName",
            //    "propName",
            // }},
            new Object[]{"xe-com.ibm.xsp.extlib.component.data.ValueColumn", true, new String[]{
                "columnName",
                "columnTitle",
                "contentType",
                "converter",
                "headerStyle",
                "headerStyleClass",
                "href",
                "style",
                "styleClass",
                "value",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.component.layout.ApplicationConfiguration", true},
            new Object[]{"xe-com.ibm.xsp.extlib.component.picker.data.INamePickerData", true},
            new Object[]{"xe-com.ibm.xsp.extlib.component.picker.data.IPickerData", true},
            new Object[]{"xe-com.ibm.xsp.extlib.component.picker.data.IValuePickerData", true},
            new Object[]{"xe-com.ibm.xsp.extlib.component.rest.AbstractRestService", true, new String[]{
                "dojoAttributes",
                "dojoType",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.component.rest.DominoDocumentService", true, new String[]{
                "computeWithForm",
                "defaultItems",
                "documentUnid",
                "formName",
                "globalValues",
                "items",
                "markRead",
                "parentId",
                "postDeleteDocument",
                "postNewDocument",
                "postOpenDocument",
                "postSaveDocument",
                "queryDeleteDocument",
                "queryNewDocument",
                "queryOpenDocument",
                "querySaveDocument",
                "search",
                "searchMaxDocs",
                "since",
                "strongType",
                "systemItems",
                "var",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.component.rest.DominoService", true, new String[]{
                "databaseName",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.component.rest.DominoViewService", true, new String[]{
                "categoryFilter",
                "columns",
                "computeWithForm",
                "count",
                "defaultColumns",
                "expandLevel",
                "formName",
                "globalValues",
                "keys",
                "keysExactMatch",
                "parentId",
                "postDeleteDocument",
                "postNewDocument",
                "postOpenDocument",
                "postSaveDocument",
                "queryDeleteDocument",
                "queryNewDocument",
                "queryOpenDocument",
                "querySaveDocument",
                "search",
                "searchMaxDocs",
                "sortColumn",
                "sortOrder",
                "start",
                "startKeys",
                "systemColumns",
                "var",
                "viewName",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.component.rest.IRestService", true},
            new Object[]{"xe-com.ibm.xsp.extlib.component.tagcloud.ITagCloudData", true},
            new Object[]{"xe-com.ibm.xsp.extlib.data.AbstractDataView", true, new String[]{
                "collapsibleDetail",
                "detailsOnClient",
                "disableHideRow",
                "openDocAsReadonly",
                "pageName",
                "rowStyle",
                "rowStyleClass",
                "showItemsFlat",
                "style",
                "styleClass",
                "summaryColumn",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.data.AbstractPager", true, new String[]{
                "for",
                "partialExecute",
                "partialRefresh",
                "refreshId",
                "style",
                "styleClass",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.data.DataSourceIterator", true, new String[]{
                "data",
                "expandedDetail",
                "partialExecute",
                "partialRefresh",
                "refreshId",
                "rows",
                "value",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.data.FormLayout", true, new String[]{
                "disableErrorSummary",
                "disableRequiredMarks",
                "disableRowError",
                "errorSummaryText",
                "fieldHelp",
                "formDescription",
                "formTitle",
                "labelPosition",
                "legend",
                "style",
                "styleClass",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.dojo.Widget", true, new String[]{
                "dragRestriction",
                "onBlur",
                "onClick",
                "onClose",
                "onDblClick",
                "onFocus",
                "onHide",
                "onKeyDown",
                "onKeyPress",
                "onKeyUp",
                "onMouseDown",
                "onMouseEnter",
                "onMouseLeave",
                "onMouseMove",
                "onMouseOut",
                "onMouseOver",
                "onMouseUp",
                "onShow",
                "waiRole",
                "waiState",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.dojo.WidgetBase", true, new String[]{
                "dir",
                "dojoAttributes",
                "dojoType",
                "lang",
                "style",
                "styleClass",
                "title",
                "tooltip",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.dojo.form.FormWidgetBase", true, new String[]{
                "alt",
                "dir",
                "disabled",
                "dragRestriction",
                "intermediateChanges",
                "lang",
                "onBlur",
                "onChange",
                "onClick",
                "onClose",
                "onDblClick",
                "onFocus",
                "onHide",
                "onKeyDown",
                "onKeyPress",
                "onKeyUp",
                "onMouseDown",
                "onMouseEnter",
                "onMouseLeave",
                "onMouseMove",
                "onMouseOut",
                "onMouseOver",
                "onMouseUp",
                "onShow",
                "readOnly",
                "style",
                "styleClass",
                "tabIndex",
                "title",
                "tooltip",
                "type",
                "waiRole",
                "waiState",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.dojo.form.MappedTextBox", true},
            new Object[]{"xe-com.ibm.xsp.extlib.dojo.form.RangeBoundTextBox", true, new String[]{
                "rangeMessage",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.dojo.form.SliderBase", true, new String[]{
                "clickSelect",
                "discreteValues",
                "maximum",
                "minimum",
                "pageIncrement",
                "showButtons",
                "slideDuration",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.dojoext.form.AbstractListTextBox", true},
            new Object[]{"xe-com.ibm.xsp.extlib.dynamiccontent.Dynamic", true},
            new Object[]{"xe-com.ibm.xsp.extlib.outline.AbstractOutline", true, new String[]{
                "onItemClick",
                "style",
                "styleClass",
                "treeNodes",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.picker.AbstractPicker", true, new String[]{
                "dialogTitle",
                "dojoAttributes",
                "dojoType",
                "for",
                "listHeight",
                "listWidth",
                "pickerIcon",
                "pickerText",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.renderkit.html_extended.outline.tree.HtmlTagsRenderer", true, new String[]{
                "containerStyle",
                "containerStyleClass",
                "disabledItemStyle",
                "disabledItemStyleClass",
                "itemStyle",
                "itemStyleClass",
                "selectedItemStyle",
                "selectedItemStyleClass",
            }},
            new Object[]{"xe-com.ibm.xsp.extlib.tree.ITreeNode", true},
            new Object[]{"xe-com.ibm.xsp.extlib.tree.ITreeRenderer", true},
            new Object[]{"xe-com.ibm.xsp.extlib.tree.complex.BasicComplexTreeNode", true, new String[]{
                "enabled",
                "image",
                "imageAlt",
                "imageHeight",
                "imageWidth",
                "label",
                "rendered",
                "role",
                "selected",
                "style",
                "styleClass",
            }},
            new Object[]{"xe:accordion", true},
            new Object[]{"xe:addRows", true, new String[]{
                "disableId",
                "for",
                "rowCount",
                "state",
            }},
            new Object[]{"xe:alertAction", true, new String[]{
                "text",
            }},
            new Object[]{"xe:appPage", true, new String[]{
                "autoCreate",
                "keepScrollPos",
                "pageName",
                "preload",
                "resetContent",
            }},
            new Object[]{"xe:appSearchBar", true, new String[]{
                "inactiveText",
                "inputTitle",
                "legend",
                "options",
                "optionsParam",
                "pageName",
                "queryParam",
                "rendered",
                "scopeTitle",
            }},
            new Object[]{"xe:applicationConfiguration", true, new String[]{
                "banner",
                "bannerApplicationLinks",
                "bannerUtilityLinks",
                "defaultNavigationPath",
                "footer",
                "footerLinks",
                "legal",
                "legalLogo",
                "legalLogoAlt",
                "legalLogoClass",
                "legalLogoHeight",
                "legalLogoStyle",
                "legalLogoWidth",
                "legalText",
                "mastFooter",
                "mastHeader",
                "navigationPath",
                "placeBar",
                "placeBarActions",
                "placeBarName",
                "productLogo",
                "productLogoAlt",
                "productLogoClass",
                "productLogoHeight",
                "productLogoStyle",
                "productLogoWidth",
                "searchBar",
                "titleBar",
                "titleBarName",
                "titleBarTabs",
            }},
            new Object[]{"xe:applicationLayout", true, new String[]{
                "configuration",
                "onItemClick",
            }},
            new Object[]{"xe:basicContainerNode", true, new String[]{
                "children",
                "transparent",
            }},
            new Object[]{"xe:basicLeafNode", true, new String[]{
                "href",
                "onClick",
                "submitValue",
            }},
            new Object[]{"xe:beanNamePicker", true, new String[]{
                "dataBean",
            }},
            new Object[]{"xe:beanTreeNode", true, new String[]{
                "nodeBean",
            }},
            new Object[]{"xe:beanValuePicker", true, new String[]{
                "dataBean",
            }},
            new Object[]{"xe:breadCrumbs", true, new String[]{
                "label",
            }},
            new Object[]{"xe:calendarJsonLegacyService", true, new String[]{
                "colAltSubject",
                "colCalendarDate",
                "colChair",
                "colConfidential",
                "colCustomData",
                "colEndTime",
                "colEntryIcon",
                "colEntryType",
                "colStartTime",
                "colStatus",
                "colSubject",
                "compact",
                "contentType",
                "var",
                "viewName",
            }},
            new Object[]{"xe:calendarView", true, new String[]{
                "date",
                "jsId",
                "onChangeView",
                "onContextMenu",
                "onDeleteEntry",
                "onNewEntry",
                "onOpenEntry",
                "onRescheduleEntry",
                "onSelectEntry",
                "storeComponentId",
                "style",
                "styleClass",
                "summarize",
                "type",
            }},
            new Object[]{"xe:changeDynamicContentAction", true, new String[]{
                "facetName",
                "for",
                "parameters",
            }},
            new Object[]{"xe:dataView", true, new String[]{
                "categoryColumn",
                "collapsibleCategory",
                "collapsibleRows",
                "columnTitles",
                "extraColumns",
                "iconColumn",
                "multiColumnCount",
                "role",
                "showCheckbox",
                "showHeaderCheckbox",
            }},
            new Object[]{"xe:databaseCollectionJsonService", true, new String[]{
                "compact",
                "contentType",
            }},
            new Object[]{"xe:dialog", true, new String[]{
                "afterContentLoad",
                "beforeContentLoad",
                "keepComponents",
            }},
            new Object[]{"xe:dialogButtonBar", true, new String[]{
                "style",
                "styleClass",
            }},
            new Object[]{"xe:djAccordionContainer", true, new String[]{
                "duration",
                "selectedTab",
            }},
            new Object[]{"xe:djAccordionPane", true},
            new Object[]{"xe:djBorderContainer", true, new String[]{
                "design",
                "gutters",
                "liveSplitters",
                "persist",
            }},
            new Object[]{"xe:djBorderPane", true, new String[]{
                "layoutPriority",
                "maxSize",
                "minSize",
                "region",
                "splitter",
            }},
            new Object[]{"xe:djButton", true, new String[]{
                "iconClass",
                "label",
                "showLabel",
            }},
            new Object[]{"xe:djCheckBox", true},
            new Object[]{"xe:djComboBox", true, new String[]{
                "autoComplete",
                "hasDownArrow",
                "ignoreCase",
                "pageSize",
                "queryExpr",
                "searchAttr",
                "searchDelay",
                "store",
            }},
            new Object[]{"xe:djContentPane", true, new String[]{
                "errorMessage",
                "extractContent",
                "href",
                "loadingMessage",
                "onContentError",
                "onDownloadEnd",
                "onDownloadError",
                "onDownloadStart",
                "onLoad",
                "onUnload",
                "parseOnLoad",
                "partialRefresh",
                "preload",
                "preventCache",
                "refreshOnShow",
            }},
            new Object[]{"xe:djCurrencyTextBox", true, new String[]{
                "constraints",
            }},
            new Object[]{"xe:djDateTextBox", true, new String[]{
                "constraints",
            }},
            new Object[]{"xe:djDateTimeConstraints", true, new String[]{
                "am",
                "clickableIncrement",
                "datePattern",
                "formatLength",
                "locale",
                "pm",
                "selector",
                "strict",
                "timePattern",
                "visibleIncrement",
                "visibleRange",
            }},
            new Object[]{"xe:djFilteringSelect", true, new String[]{
                "labelAttr",
                "labelFunc",
                "labelType",
            }},
            new Object[]{"xe:djHorizontalSlider", true},
            new Object[]{"xe:djNumberConstraints", true, new String[]{
                "currency",
                "fractional",
                "locale",
                "max",
                "min",
                "pattern",
                "places",
                "strict",
                "symbol",
                "type",
            }},
            new Object[]{"xe:djNumberSpinner", true, new String[]{
                "defaultTimeout",
                "largeDelta",
                "smallDelta",
                "timeoutChangeRate",
            }},
            new Object[]{"xe:djNumberTextBox", true, new String[]{
                "constraints",
                "javaType",
            }},
            new Object[]{"xe:djRadioButton", true, new String[]{
                "groupName",
                "selectedValue",
                "skipContainers",
            }},
            new Object[]{"xe:djSimpleTextarea", true},
            new Object[]{"xe:djSliderRule", true, new String[]{
                "container",
                "count",
                "ruleStyle",
            }},
            new Object[]{"xe:djSliderRuleLabel", true, new String[]{
                "label",
            }},
            new Object[]{"xe:djSliderRuleLabels", true, new String[]{
                "constraints",
                "labelStyle",
                "labels",
                "labelsList",
                "maximum",
                "minimum",
                "numericMargin",
            }},
            new Object[]{"xe:djStackContainer", true, new String[]{
                "doLayout",
                "persist",
                "selectedTab",
            }},
            new Object[]{"xe:djStackPane", true},
            new Object[]{"xe:djTabContainer", true, new String[]{
                "defaultTabContent",
                "tabPosition",
                "tabStrip",
                "useMenu",
                "useSlider",
            }},
            new Object[]{"xe:djTabPane", true, new String[]{
                "closable",
                "partialEvents",
                "tabUniqueKey",
            }},
            new Object[]{"xe:djTextBox", true, new String[]{
                "lowercase",
                "maxLength",
                "propercase",
                "trim",
                "uppercase",
            }},
            new Object[]{"xe:djTextarea", true, new String[]{
                "cols",
                "rows",
            }},
            new Object[]{"xe:djTimeTextBox", true, new String[]{
                "constraints",
            }},
            new Object[]{"xe:djToggleButton", true, new String[]{
                "checkedValue",
                "uncheckedValue",
            }},
            new Object[]{"xe:djValidationTextBox", true, new String[]{
                "displayMessageExt",
                "invalidMessage",
                "promptMessage",
                "regExp",
                "regExpGen",
                "tooltipPosition",
                "validatorExt",
            }},
            new Object[]{"xe:djVerticalSlider", true},
            new Object[]{"xe:djextImageSelect", true, new String[]{
                "imageValues",
            }},
            new Object[]{"xe:djextLinkSelect", true, new String[]{
                "dataProvider",
                "firstItemStyle",
                "firstItemStyleClass",
                "itemStyle",
                "itemStyleClass",
                "lastItemStyle",
                "lastItemStyleClass",
            }},
            new Object[]{"xe:djextListTextBox", true, new String[]{
                "dataProvider",
                "displayLabel",
            }},
            new Object[]{"xe:djextNameTextBox", true},
            new Object[]{"xe:djxDataGrid", true, new String[]{
                "autoHeight",
                "errorMessage",
                "escapeHTMLInData",
                "headerMenu",
                "initialWidth",
                "jsId",
                "loadingMessage",
                "onRowClick",
                "onRowContextMenu",
                "onRowDblClick",
                "onStyleRow",
                "query",
                "rowSelector",
                "rowsPerPage",
                "selectable",
                "selectionMode",
                "singleClickEdit",
                "store",
                "storeComponentId",
                "updateDelay",
            }},
            new Object[]{"xe:djxDataGridColumn", true, new String[]{
                "cellType",
                "editable",
                "field",
                "formatter",
                "get",
                "hidden",
                "label",
                "options",
                "width",
            }},
            new Object[]{"xe:djxDataGridRow", true},
            new Object[]{"xe:djxmHeading", true, new String[]{
                "back",
                "href",
                "label",
                "moveTo",
                "transition",
            }},
            new Object[]{"xe:djxmLineItem", true, new String[]{
                "icon",
                "label",
                "moveTo",
                "rightText",
                "transition",
            }},
            new Object[]{"xe:djxmRoundRectList", true, new String[]{
                "iconBase",
                "iconPos",
                "transition",
            }},
            new Object[]{"xe:djxmSwitch", true, new String[]{
                "leftLabel",
                "onStateChanged",
                "onTouchEnd",
                "onTouchMove",
                "onTouchStart",
                "rightLabel",
                "value",
            }},
            new Object[]{"xe:documentJsonService", true, new String[]{
                "compact",
                "contentType",
            }},
            new Object[]{"xe:dojoAnimateProperty", true, new String[]{
                "attributes",
                "delay",
                "duration",
                "easing",
                "node",
                "properties",
                "rate",
                "repeat",
                "var",
            }},
            new Object[]{"xe:dojoAnimationProps", true, new String[]{
                "end",
                "name",
                "start",
                "unit",
            }},
            new Object[]{"xe:dojoFadeIn", true, new String[]{
                "attributes",
                "duration",
                "easing",
                "node",
                "var",
            }},
            new Object[]{"xe:dojoFadeOut", true, new String[]{
                "attributes",
                "duration",
                "easing",
                "node",
                "var",
            }},
            new Object[]{"xe:dojofxSlideTo", true, new String[]{
                "attributes",
                "duration",
                "easing",
                "left",
                "node",
                "top",
                "var",
            }},
            new Object[]{"xe:dojofxWipeIn", true, new String[]{
                "attributes",
                "duration",
                "easing",
                "node",
                "var",
            }},
            new Object[]{"xe:dojofxWipeOut", true, new String[]{
                "attributes",
                "duration",
                "easing",
                "node",
                "var",
            }},
            new Object[]{"xe:dominoNABNamePicker", true, new String[]{
                "addressBookDb",
                "addressBookSel",
                "groups",
                "nameList",
                "people",
            }},
            new Object[]{"xe:dominoViewCloudData", true, new String[]{
                "cacheMode",
                "cacheRefreshInterval",
                "categoryColumn",
                "linkMetaSeparator",
                "linkRequestParam",
                "linkTargetPage",
                "maxTagLimit",
                "minEntryCount",
                "sortTags",
                "tagThreshold",
                "viewName",
            }},
            new Object[]{"xe:dominoViewEntriesTreeNode", true, new String[]{
                "databaseName",
                "keys",
                "keysExactMatch",
                "labelColumn",
                "var",
                "viewName",
            }},
            new Object[]{"xe:dominoViewListTreeNode", true, new String[]{
                "databaseName",
                "filter",
                "folders",
                "var",
                "views",
            }},
            new Object[]{"xe:dominoViewNamePicker", true, new String[]{
                "databaseName",
                "label",
                "labelColumn",
                "viewName",
            }},
            new Object[]{"xe:dominoViewValuePicker", true, new String[]{
                "databaseName",
                "labelColumn",
                "viewName",
            }},
            new Object[]{"xe:dropDownButton", true},
            new Object[]{"xe:dumpObject", true, new String[]{
                "levels",
                "maxGridRows",
                "objectNames",
                "startFilter",
                "title",
                "useBeanProperties",
                "value",
            }},
            new Object[]{"xe:dynamicContent", true, new String[]{
                "afterContentLoad",
                "beforeContentLoad",
                "defaultFacet",
                "partialEvents",
                "useHash",
            }},
            new Object[]{"xe:dynamicViewPanel", true, new String[]{
                "customizerBean",
                "onColumnClick",
                "rows",
                "showCheckbox",
                "showHeaderCheckbox",
            }},
            new Object[]{"xe:firebugLite", true, new String[]{
                "url",
            }},
            new Object[]{"xe:formColumn", true, new String[]{
                "colSpan",
                "style",
                "styleClass",
            }},
            new Object[]{"xe:formRow", true, new String[]{
                "for",
                "helpId",
                "label",
                "labelPosition",
                "labelWidth",
                "style",
                "styleClass",
            }},
            new Object[]{"xe:formTable", true, new String[]{
                "labelWidth",
            }},
            new Object[]{"xe:forumPost", true, new String[]{
                "style",
                "styleClass",
            }},
            new Object[]{"xe:forumView", true},
            new Object[]{"xe:htmlDivSpanRenderer", true},
            new Object[]{"xe:htmlListRenderer", true},
            new Object[]{"xe:iCalReadStore", true, new String[]{
                "bgColorMeeting",
                "borderColorMeeting",
                "fontColorMeeting",
                "jsId",
                "storeTitle",
                "url",
            }},
            new Object[]{"xe:iconEntry", true, new String[]{
                "alt",
                "selected",
                "selectedValue",
                "style",
                "styleClass",
                "title",
                "url",
            }},
            new Object[]{"xe:inPlaceForm", true, new String[]{
                "afterContentLoad",
                "beforeContentLoad",
                "partialEvents",
            }},
            new Object[]{"xe:jsonRpcService", true, new String[]{
                "methods",
                "pathInfo",
                "serviceName",
                "state",
            }},
            new Object[]{"xe:keepSessionAlive", true, new String[]{
                "delay",
            }},
            new Object[]{"xe:linksList", true},
            new Object[]{"xe:list", true, new String[]{
                "firstItemStyle",
                "firstItemStyleClass",
                "itemStyle",
                "itemStyleClass",
                "lastItemStyle",
                "lastItemStyleClass",
                "style",
                "styleClass",
            }},
            new Object[]{"xe:listInline", true},
            new Object[]{"xe:listSeparator", true},
            new Object[]{"xe:listView", true, new String[]{
                "alternateRows",
                "canBeNarrowMode",
                "hideColumns",
                "jsId",
                "onCellClick",
                "onCellDblClick",
                "onContextMenu",
                "onDeleteEntry",
                "onNewEntry",
                "onOpenEntry",
                "onSelectEntry",
                "onSortChanged",
                "showColumnNameForEmptyTitle",
                "storeComponentId",
                "structureComponentId",
                "style",
                "styleClass",
            }},
            new Object[]{"xe:listViewColumn", true, new String[]{
                "beginWrapUnder",
                "columnName",
                "columnTitle",
                "extendable",
                "fixedWidth",
                "icon",
                "narrowDisplay",
                "response",
                "sequenceNumber",
                "showGradient",
                "sort",
                "twistie",
                "width",
            }},
            new Object[]{"xe:loginTreeNode", true},
            new Object[]{"xe:mobileAccordionMenu", true},
            new Object[]{"xe:moveTo", true, new String[]{
                "direction",
                "forceFullRefresh",
                "saveDocument",
                "targetPage",
                "transitionType",
            }},
            new Object[]{"xe:multiImage", true, new String[]{
                "icons",
            }},
            new Object[]{"xe:namePicker", true, new String[]{
                "dataProvider",
            }},
            new Object[]{"xe:namePickerAggregator", true, new String[]{
                "dataProviders",
            }},
            new Object[]{"xe:navigator", true, new String[]{
                "expandEffect",
                "expandLevel",
                "expandable",
            }},
            new Object[]{"xe:notesCalendarStore", true, new String[]{
                "databaseName",
                "dojoAttributes",
                "dojoType",
                "jsId",
                "storeTitle",
            }},
            new Object[]{"xe:notesListViewDesign", true, new String[]{
                "databaseName",
                "jsId",
                "viewName",
            }},
            new Object[]{"xe:notesListViewStore", true, new String[]{
                "databaseName",
                "jsId",
                "viewName",
            }},
            new Object[]{"xe:objectData", true, new String[]{
                "createObject",
                "ignoreRequestParams",
                "readonly",
                "requestParamPrefix",
                "saveObject",
                "scope",
                "var",
            }},
            new Object[]{"xe:oneuiApplication", true},
            new Object[]{"xe:outline", true, new String[]{
                "treeRenderer",
            }},
            new Object[]{"xe:pageTreeNode", true, new String[]{
                "children",
                "page",
                "queryString",
                "selection",
            }},
            new Object[]{"xe:pagerAddRows", true, new String[]{
                "disabledFormat",
                "refreshPage",
                "rowCount",
                "state",
                "text",
            }},
            new Object[]{"xe:pagerDetail", true, new String[]{
                "hideText",
                "showText",
            }},
            new Object[]{"xe:pagerExpand", true, new String[]{
                "collapseText",
                "expandText",
            }},
            new Object[]{"xe:pagerSaveState", true, new String[]{
                "globalRows",
            }},
            new Object[]{"xe:pagerSizes", true, new String[]{
                "sizes",
                "text",
            }},
            new Object[]{"xe:pickerValidator", true, new String[]{
                "dataProvider",
                "for",
                "message",
            }},
            new Object[]{"xe:popupMenu", true},
            new Object[]{"xe:remoteMethod", true, new String[]{
                "arguments",
                "name",
                "script",
            }},
            new Object[]{"xe:remoteMethodArg", true, new String[]{
                "name",
                "type",
            }},
            new Object[]{"xe:repeatTreeNode", true, new String[]{
                "children",
                "indexVar",
                "value",
                "var",
            }},
            new Object[]{"xe:restDocumentItem", true, new String[]{
                "itemName",
                "name",
                "value",
            }},
            new Object[]{"xe:restService", true, new String[]{
                "ignoreRequestParams",
                "jsId",
                "pathInfo",
                "preventDojoStore",
                "service",
                "state",
            }},
            new Object[]{"xe:restViewColumn", true, new String[]{
                "columnName",
                "name",
                "value",
            }},
            new Object[]{"xe:selectImage", true, new String[]{
                "image",
                "imageAlt",
                "selectedImage",
                "selectedStyle",
                "selectedStyleClass",
                "selectedValue",
                "style",
                "styleClass",
                "title",
            }},
            new Object[]{"xe:separatorTreeNode", true, new String[]{
                "rendered",
                "style",
                "styleClass",
            }},
            new Object[]{"xe:simpleValuePicker", true, new String[]{
                "caseInsensitive",
                "labelSeparator",
                "valueList",
                "valueListSeparator",
            }},
            new Object[]{"xe:singlePageApp", true, new String[]{
                "selectedPageName",
            }},
            new Object[]{"xe:sortLinks", true},
            new Object[]{"xe:switchFacet", true, new String[]{
                "defaultFacet",
                "selectedFacet",
            }},
            new Object[]{"xe:tabBar", true, new String[]{
                "barType",
                "inHeading",
            }},
            new Object[]{"xe:tabBarButton", true, new String[]{
                "icon1",
                "icon2",
                "iconPos1",
                "iconPos2",
                "label",
                "onClick",
                "selectOne",
                "selected",
                "transition",
            }},
            new Object[]{"xe:tagCloud", true, new String[]{
                "alternateText",
                "cloudData",
                "sliderVisible",
            }},
            new Object[]{"xe:toolbar", true, new String[]{
                "showButtonLabels",
            }},
            new Object[]{"xe:tooltip", true, new String[]{
                "afterContentLoad",
                "beforeContentLoad",
                "dojoAttributes",
                "dojoType",
                "dynamicContent",
                "for",
                "label",
                "position",
                "showDelay",
            }},
            new Object[]{"xe:tooltipDialog", true},
            new Object[]{"xe:userTreeNode", true, new String[]{
                "userField",
            }},
            new Object[]{"xe:valuePicker", true, new String[]{
                "dataProvider",
            }},
            new Object[]{"xe:viewCategoryColumn", true, new String[]{
                "columnName",
            }},
            new Object[]{"xe:viewCollectionJsonService", true, new String[]{
                "compact",
                "contentType",
            }},
            new Object[]{"xe:viewExtraColumn", true},
            new Object[]{"xe:viewIconColumn", true, new String[]{
                "columnName",
                "icons",
                "value",
            }},
            new Object[]{"xe:viewItemFileService", true, new String[]{
                "compact",
                "contentType",
            }},
            new Object[]{"xe:viewJsonLegacyService", true, new String[]{
                "compact",
                "contentType",
            }},
            new Object[]{"xe:viewJsonService", true, new String[]{
                "compact",
                "contentType",
            }},
            new Object[]{"xe:viewSummaryColumn", true},
            new Object[]{"xe:viewXmlLegacyService", true, new String[]{
                "compact",
                "contentType",
            }},
            new Object[]{"xe:widgetContainer", true, new String[]{
                "dropDownNodes",
                "dropDownRendered",
                "onScrollDown",
                "onScrollUp",
                "scrollable",
                "style",
                "styleClass",
                "titleBar",
                "titleBarHref",
                "titleBarText",
                "type",
            }},
    };
    private String[] skips = StringUtil.EMPTY_STRING_ARRAY;
    public Object[][] tagsAndProps() {
        return tagsAndProps;
    }
    public String sinceVersion() {
        // null - the first version
        return null;
    }
    public String[] skips() {
        return skips;
    }
}
