({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "P\u00e4iv\u00e4 %1 - vuoden viimeinen p\u00e4iv\u00e4",
L_CAL_LAST_MONTH: "Kuukausi %1 - vuoden viimeinen kuukausi",
L_CAL_LAST_WEEK: "Viikko %1 - vuoden viimeinen viikko",
L_CAL_LEFT_DAY: "P\u00e4iv\u00e4 %1 - %2 p\u00e4iv\u00e4\u00e4 j\u00e4ljell\u00e4 vuodesta",
L_CAL_LEFT_DAYS: "P\u00e4iv\u00e4 %1 - %2 p\u00e4iv\u00e4\u00e4 j\u00e4ljell\u00e4 vuodesta",
L_CAL_LEFT_MONTH: "Kuukausi %1 - %2 kuukausi j\u00e4ljell\u00e4 vuodesta",
L_CAL_LEFT_MONTHS: "Kuukausi %1 - %2 kuukautta j\u00e4ljell\u00e4 vuodesta",
L_CAL_LEFT_WEEK: "Viikko %1 - %2 viikko j\u00e4ljell\u00e4 vuodesta",
L_CAL_LEFT_WEEKS: "Viikko %1 - %2 viikkoa j\u00e4ljell\u00e4 vuodesta",
L_CHARDAY_FRI: "P",
L_CHARDAY_MON: "M",
L_CHARDAY_SAT: "L",
L_CHARDAY_SUN: "S",
L_CHARDAY_THU: "T",
L_CHARDAY_TUE: "T",
L_CHARDAY_WED: "K",
L_NO_CAL_ENTRY_SELECTED: "Kalenterimerkint\u00e4\u00e4 ei ole valittu.  Valitse merkint\u00e4 ja yrit\u00e4 uudelleen.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "%1 - ei ole kalenterimerkint\u00f6j\u00e4."
})
