({
L_CAL_NAV_PREVIOUS: "Edellinen",
L_CAL_NAV_NEXT: "Seuraava",
L_CAL_NAV_MONTH: "Kuukausi",
L_CAL_HEADER_DAYS_WEEK: "Viikonp\u00e4iv\u00e4t",
L_CAL_HEADER: "Kalenterin otsikko",
L_CAL_HEADER_DAY: "P\u00e4iv\u00e4otsikko %1",
L_CAL_EVENT_ALLDAY: "Koko p\u00e4iv\u00e4n tapahtuma %1",
L_CAL_NOENTRY: "Ei merkint\u00f6j\u00e4",
L_CAL_GRID: "Kalenteriruudukko",
L_CAL_PICKER_POPUP: "P\u00e4iv\u00e4m\u00e4\u00e4r\u00e4valitsimen ponnahdusikkuna",
L_CAL_NAV_TIMESCALE_PREV_D: "Edellinen p\u00e4iv\u00e4",
L_CAL_NAV_TIMESCALE_NEXT_D: "Seuraava p\u00e4iv\u00e4",
L_CAL_NAV_TIMESCALE_PREV_T: "Edelliset kaksi p\u00e4iv\u00e4\u00e4",
L_CAL_NAV_TIMESCALE_NEXT_T: "Seuraavat kaksi p\u00e4iv\u00e4\u00e4",
L_CAL_NAV_TIMESCALE_PREV_F: "Edellinen ty\u00f6viikko",
L_CAL_NAV_TIMESCALE_NEXT_F: "Seuraava ty\u00f6viikko",
L_CAL_NAV_TIMESCALE_PREV_W: "Edellinen viikko",
L_CAL_NAV_TIMESCALE_NEXT_W: "Seuraava viikko",
L_CAL_NAV_TIMESCALE_PREV_2: "Edelliset kaksi viikkoa",
L_CAL_NAV_TIMESCALE_NEXT_2: "Seuraavat kaksi viikkoa",
L_CAL_NAV_TIMESCALE_PREV_M: "Edellinen kuukausi",
L_CAL_NAV_TIMESCALE_NEXT_M: "Seuraava kuukausi",
L_CAL_NAV_TIMESCALE_PREV_Y: "Edellinen vuosi",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Seuraava vuosi"
})
