({
L_CANCEL: "Avbryt",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Oppf\u00f8ring ikke funnet",
L_ERR_INVALIDDATE: "Ugyldig dato.",
L_FETCHING: "Henter poster . . .",
L_FETCHINGNEXT: "Henter neste side med poster . . .",
L_FETCHINGPREV: "Henter forrige side med poster . . .",
L_JAWS_GIGABYTES: "%1 gigabyte",
L_JAWS_KILOBYTES: "%1 kilobyte",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Sortert stigende",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 kolonne. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Sortert synkende",
L_JAWS_LISTVIEW_NOENTRY: "ingen oppf\u00f8ring valgt",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Trykk p\u00e5 Enter for \u00e5 sortere stigende",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Trykk p\u00e5 Enter for \u00e5 sortere synkende",
L_JAWS_LISTVIEW_UNDORESORT: "Trykk p\u00e5 Enter for \u00e5 oppheve sorteringen",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 kolonne. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 av %3",
L_JAWS_MEGABYTES: "%1 megabyte",
L_JAWS_TERABYTES: "%1 terabyte",
L_NARROW_DEFAULT: "Sorter etter standard",
L_NARROW_NOTITLE: "Ingen tittel",
L_NARROW_SORTBY: "Sorter etter %1",
L_SEARCH: "S\u00f8k",
L_STARTSWITH_COLUMN: "Velg kolonnen det skal sorteres etter:",
L_STARTSWITH_INVALID_NUMBER: "Ugyldig tall angitt",
L_STARTSWITH_SEARCH: "S\u00f8k etter oppf\u00f8ringer som begynner med:",
L_STARTSWITH_TITLE: "Starter med...",
L_UPDATINGVIEW_MESSAGE: "Denne oversikten oppdateres trolig p\u00e5 serveren.\nDen vil vises n\u00e5r oppdateringen er fullf\u00f8rt.\nDu kan fortsette \u00e5 arbeide med andre kategorier eller andre oversikter/mapper.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "Nytt dokument ",
L_VIEWICONTIPS_ELM_10: "P\u00e5minnelse ",
L_VIEWICONTIPS_ELM_100: "Bl\u00e5 diamant ",
L_VIEWICONTIPS_ELM_101: "R\u00f8d opp-pil ",
L_VIEWICONTIPS_ELM_102: "R\u00f8d nedpil ",
L_VIEWICONTIPS_ELM_103: "R\u00f8d venstrepil ",
L_VIEWICONTIPS_ELM_104: "R\u00f8d h\u00f8yrepil ",
L_VIEWICONTIPS_ELM_105: "Gr\u00f8nn opp-pil ",
L_VIEWICONTIPS_ELM_106: "Gr\u00f8nn nedpil ",
L_VIEWICONTIPS_ELM_107: "Gr\u00f8nn venstrepil ",
L_VIEWICONTIPS_ELM_108: "Gr\u00f8nn h\u00f8yrepil ",
L_VIEWICONTIPS_ELM_109: "Bl\u00e5 opp-pil ",
L_VIEWICONTIPS_ELM_11: "Informasjon ",
L_VIEWICONTIPS_ELM_110: "Bl\u00e5 nedpil ",
L_VIEWICONTIPS_ELM_111: "Bl\u00e5 venstrepil ",
L_VIEWICONTIPS_ELM_112: "Bl\u00e5 h\u00f8yrepil ",
L_VIEWICONTIPS_ELM_113: "Bl\u00e5 skjerm ",
L_VIEWICONTIPS_ELM_114: "Gr\u00f8nn ball ",
L_VIEWICONTIPS_ELM_115: "R\u00f8d ball ",
L_VIEWICONTIPS_ELM_116: "Brun ball ",
L_VIEWICONTIPS_ELM_117: "Bl\u00e5 ball ",
L_VIEWICONTIPS_ELM_118: "M\u00f8rk bl\u00e5 ball ",
L_VIEWICONTIPS_ELM_119: "Purpurr\u00f8d ball ",
L_VIEWICONTIPS_ELM_12: "Skriv tekst ",
L_VIEWICONTIPS_ELM_120: "Gul ball ",
L_VIEWICONTIPS_ELM_121: "U\u00e5pnet hvit konvolutt ",
L_VIEWICONTIPS_ELM_122: "Sendt melding ",
L_VIEWICONTIPS_ELM_123: "U\u00e5pnet bl\u00e5 konvolutt ",
L_VIEWICONTIPS_ELM_124: "U\u00e5pnet r\u00f8d konvolutt ",
L_VIEWICONTIPS_ELM_125: "\u00c5pnet hvit konvolutt ",
L_VIEWICONTIPS_ELM_126: "\u00c5pnet gul konvolutt ",
L_VIEWICONTIPS_ELM_127: "\u00c5pnet bl\u00e5 konvolutt ",
L_VIEWICONTIPS_ELM_128: "R\u00f8d konvoluttbakside ",
L_VIEWICONTIPS_ELM_129: "Hvit konvoluttbakside ",
L_VIEWICONTIPS_ELM_13: "Grafikk ",
L_VIEWICONTIPS_ELM_130: "Gul konvoluttbakside ",
L_VIEWICONTIPS_ELM_131: "R\u00f8d konvoluttbakside ",
L_VIEWICONTIPS_ELM_132: "Hvit invitasjon ",
L_VIEWICONTIPS_ELM_133: "Gul invitasjon ",
L_VIEWICONTIPS_ELM_134: "R\u00f8d invitasjon ",
L_VIEWICONTIPS_ELM_135: "Lotus 123 ",
L_VIEWICONTIPS_ELM_136: "Tekstbehandlingsdokument ",
L_VIEWICONTIPS_ELM_137: "Presentasjon ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "Videokamera ",
L_VIEWICONTIPS_ELM_14: "Diagram ",
L_VIEWICONTIPS_ELM_140: "Arbeidsflytdokument ",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft PowerPoint ",
L_VIEWICONTIPS_ELM_144: "Kakediagram ",
L_VIEWICONTIPS_ELM_145: "Visio ",
L_VIEWICONTIPS_ELM_146: "Vinter ",
L_VIEWICONTIPS_ELM_147: "V\u00e5r ",
L_VIEWICONTIPS_ELM_148: "Sommer ",
L_VIEWICONTIPS_ELM_149: "H\u00f8st ",
L_VIEWICONTIPS_ELM_15: "Lyd ",
L_VIEWICONTIPS_ELM_150: "Utropstegn ",
L_VIEWICONTIPS_ELM_151: "Ettall ",
L_VIEWICONTIPS_ELM_152: "Totall ",
L_VIEWICONTIPS_ELM_153: "Tretall ",
L_VIEWICONTIPS_ELM_154: "Firetall ",
L_VIEWICONTIPS_ELM_155: "Femtall ",
L_VIEWICONTIPS_ELM_156: "Matlaging ",
L_VIEWICONTIPS_ELM_157: "Uakseptabelt dokument ",
L_VIEWICONTIPS_ELM_158: "M\u00f8te ",
L_VIEWICONTIPS_ELM_159: "Gullstjerne ",
L_VIEWICONTIPS_ELM_16: "Mikrofon ",
L_VIEWICONTIPS_ELM_160: "Avtale ",
L_VIEWICONTIPS_ELM_161: "Dings ",
L_VIEWICONTIPS_ELM_162: "Sp\u00f8rsm\u00e5l ",
L_VIEWICONTIPS_ELM_163: "Konfidensielt ",
L_VIEWICONTIPS_ELM_164: "Kryptert e-post ",
L_VIEWICONTIPS_ELM_165: "Bl\u00e5 hengel\u00e5s ",
L_VIEWICONTIPS_ELM_166: "Forkledd ",
L_VIEWICONTIPS_ELM_167: "Bl\u00e5 hake ",
L_VIEWICONTIPS_ELM_168: "Huskelisteoppf\u00f8ring ",
L_VIEWICONTIPS_ELM_169: "R\u00f8d medaljong ",
L_VIEWICONTIPS_ELM_17: "Grafikk ",
L_VIEWICONTIPS_ELM_170: "Gul medaljong ",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Fly ",
L_VIEWICONTIPS_ELM_174: "Bil ",
L_VIEWICONTIPS_ELM_175: "Bygning ",
L_VIEWICONTIPS_ELM_176: "Nytt dokument ",
L_VIEWICONTIPS_ELM_177: "Ballong ",
L_VIEWICONTIPS_ELM_178: "Besvart melding ",
L_VIEWICONTIPS_ELM_179: "Videresendt melding ",
L_VIEWICONTIPS_ELM_18: "Gr\u00f8nn skjerm ",
L_VIEWICONTIPS_ELM_180: "Besvart og videresendt melding ",
L_VIEWICONTIPS_ELM_181: "Oppf\u00f8lging, h\u00f8y prioritet",
L_VIEWICONTIPS_ELM_182: "Oppf\u00f8lging, normal prioritet",
L_VIEWICONTIPS_ELM_183: "Oppf\u00f8lging, lav prioritet",
L_VIEWICONTIPS_ELM_184: "Sendt bare til meg ",
L_VIEWICONTIPS_ELM_185: "Sendt til meg og noen f\u00e5 andre ",
L_VIEWICONTIPS_ELM_186: "Sendt til meg og mange andre ",
L_VIEWICONTIPS_ELM_187: "Ubehandlet m\u00f8tevarsel ",
L_VIEWICONTIPS_ELM_188: "Ulest melding ",
L_VIEWICONTIPS_ELM_189: "Online-m\u00f8te ",
L_VIEWICONTIPS_ELM_19: "Tabell ",
L_VIEWICONTIPS_ELM_190: "H\u00f8y relevans ",
L_VIEWICONTIPS_ELM_191: "Middels relevans ",
L_VIEWICONTIPS_ELM_192: "Lav relevans ",
L_VIEWICONTIPS_ELM_193: "Ikke relevant ",
L_VIEWICONTIPS_ELM_194: "Heldagshendelse ",
L_VIEWICONTIPS_ELM_195: "P\u00e5minnelse ",
L_VIEWICONTIPS_ELM_196: "Flyttet ",
L_VIEWICONTIPS_ELM_197: "Avsl\u00e5 innkalling ",
L_VIEWICONTIPS_ELM_198: "Motforslag ",
L_VIEWICONTIPS_ELM_199: "\u00c5rsdag ",
L_VIEWICONTIPS_ELM_2: "U\u00e5pnet mappe ",
L_VIEWICONTIPS_ELM_20: "Tekst ",
L_VIEWICONTIPS_ELM_200: "Avlyst m\u00f8te ",
L_VIEWICONTIPS_ELM_201: "Fullf\u00f8rt huskelisteoppf\u00f8ring ",
L_VIEWICONTIPS_ELM_202: "Godtatt ",
L_VIEWICONTIPS_ELM_203: "Avsl\u00e5tt ",
L_VIEWICONTIPS_ELM_204: "H\u00f8y prioritet ",
L_VIEWICONTIPS_ELM_205: "Avtale ",
L_VIEWICONTIPS_ELM_206: "Privat innkalling ",
L_VIEWICONTIPS_ELM_207: "Sp\u00f8k ",
L_VIEWICONTIPS_ELM_208: "Konfidensielt ",
L_VIEWICONTIPS_ELM_209: "Privat ",
L_VIEWICONTIPS_ELM_21: "Flere dokumenter ",
L_VIEWICONTIPS_ELM_210: "Godtatt innkalling ",
L_VIEWICONTIPS_ELM_211: "Lest melding ",
L_VIEWICONTIPS_ELM_212: "Ny innkalling ",
L_VIEWICONTIPS_ELM_22: "To dokumenter ",
L_VIEWICONTIPS_ELM_23: "Nyheter ",
L_VIEWICONTIPS_ELM_24: "R\u00f8d bok ",
L_VIEWICONTIPS_ELM_25: "Adressebok ",
L_VIEWICONTIPS_ELM_26: "\u00c5pen bok ",
L_VIEWICONTIPS_ELM_27: "Lukket bok ",
L_VIEWICONTIPS_ELM_28: "Hvit bok ",
L_VIEWICONTIPS_ELM_29: "Revet gul side ",
L_VIEWICONTIPS_ELM_3: "Person ",
L_VIEWICONTIPS_ELM_30: "Revet bl\u00e5 side ",
L_VIEWICONTIPS_ELM_31: "Tent lysp\u00e6re ",
L_VIEWICONTIPS_ELM_32: "Slukket lysp\u00e6re ",
L_VIEWICONTIPS_ELM_33: "Oppdater ",
L_VIEWICONTIPS_ELM_34: "S\u00f8k i dokument ",
L_VIEWICONTIPS_ELM_35: "S\u00f8k i dokument fullf\u00f8rt ",
L_VIEWICONTIPS_ELM_36: "Akseptabelt dokument ",
L_VIEWICONTIPS_ELM_37: "Fullf\u00f8rt dokument ",
L_VIEWICONTIPS_ELM_38: "Dokumentproblem ",
L_VIEWICONTIPS_ELM_39: "Dokumentsp\u00f8rsm\u00e5l ",
L_VIEWICONTIPS_ELM_4: "Gruppe ",
L_VIEWICONTIPS_ELM_40: "Dokumentadvarsel ",
L_VIEWICONTIPS_ELM_41: "Gult dokument ",
L_VIEWICONTIPS_ELM_42: "Gult svardokument ",
L_VIEWICONTIPS_ELM_43: "Bl\u00e5tt svardokument ",
L_VIEWICONTIPS_ELM_44: "Telefon ",
L_VIEWICONTIPS_ELM_45: "Aktiv telefon ",
L_VIEWICONTIPS_ELM_46: "Dataterminal ",
L_VIEWICONTIPS_ELM_47: "Faks ",
L_VIEWICONTIPS_ELM_48: "CD-ROM ",
L_VIEWICONTIPS_ELM_49: "Diskett ",
L_VIEWICONTIPS_ELM_5: "Vedlegg ",
L_VIEWICONTIPS_ELM_50: "Diskett ",
L_VIEWICONTIPS_ELM_51: "Harddisk ",
L_VIEWICONTIPS_ELM_52: "Nettverk ",
L_VIEWICONTIPS_ELM_53: "Datamaskin ",
L_VIEWICONTIPS_ELM_54: "Server ",
L_VIEWICONTIPS_ELM_55: "Tilkobling ",
L_VIEWICONTIPS_ELM_56: "S\u00f8k ",
L_VIEWICONTIPS_ELM_57: "Skriv ",
L_VIEWICONTIPS_ELM_58: "Utkast ",
L_VIEWICONTIPS_ELM_59: "Valuta ",
L_VIEWICONTIPS_ELM_6: "Sammenvevd ",
L_VIEWICONTIPS_ELM_60: "Mynt ",
L_VIEWICONTIPS_ELM_61: "N\u00f8kkel ",
L_VIEWICONTIPS_ELM_62: "Hengel\u00e5s ",
L_VIEWICONTIPS_ELM_63: "Kalender ",
L_VIEWICONTIPS_ELM_64: "Klokke ",
L_VIEWICONTIPS_ELM_65: "Alarm ",
L_VIEWICONTIPS_ELM_66: "Flyvende ",
L_VIEWICONTIPS_ELM_67: "Satellitt ",
L_VIEWICONTIPS_ELM_68: "Dokumentmappe ",
L_VIEWICONTIPS_ELM_69: "Hjem ",
L_VIEWICONTIPS_ELM_7: "Dyr ",
L_VIEWICONTIPS_ELM_70: "Globus ",
L_VIEWICONTIPS_ELM_71: "Helse ",
L_VIEWICONTIPS_ELM_72: "Finans ",
L_VIEWICONTIPS_ELM_73: "Transport ",
L_VIEWICONTIPS_ELM_74: "Kjemisk ",
L_VIEWICONTIPS_ELM_75: "Produksjon ",
L_VIEWICONTIPS_ELM_76: "Offentlig ",
L_VIEWICONTIPS_ELM_77: "Telekommunikasjon ",
L_VIEWICONTIPS_ELM_78: "Bygg og anlegg ",
L_VIEWICONTIPS_ELM_79: "Timeglass ",
L_VIEWICONTIPS_ELM_8: "S\u00f8k ",
L_VIEWICONTIPS_ELM_80: "Forbudt ",
L_VIEWICONTIPS_ELM_81: "Forkastet ",
L_VIEWICONTIPS_ELM_82: "Fullf\u00f8rt ",
L_VIEWICONTIPS_ELM_83: "Akseptabelt ",
L_VIEWICONTIPS_ELM_84: "Uakseptabelt ",
L_VIEWICONTIPS_ELM_85: "Glad ",
L_VIEWICONTIPS_ELM_86: "Likegyldig ",
L_VIEWICONTIPS_ELM_87: "Trist ",
L_VIEWICONTIPS_ELM_88: "Lunken ",
L_VIEWICONTIPS_ELM_89: "Varm ",
L_VIEWICONTIPS_ELM_9: "Nettverksaktivitet ",
L_VIEWICONTIPS_ELM_90: "Sv\u00e6rt varm ",
L_VIEWICONTIPS_ELM_91: "Bombe ",
L_VIEWICONTIPS_ELM_92: "Stoppskilt ",
L_VIEWICONTIPS_ELM_93: "Stopp ",
L_VIEWICONTIPS_ELM_94: "Advarsel ",
L_VIEWICONTIPS_ELM_95: "G\u00e5 ",
L_VIEWICONTIPS_ELM_96: "Positiv ",
L_VIEWICONTIPS_ELM_97: "Negativ ",
L_VIEWICONTIPS_ELM_98: "R\u00f8d diamant ",
L_VIEWICONTIPS_ELM_99: "Gr\u00f8nn diamant ",
L_VIEWMAIL: "Post"
})
