({
L_CANCEL: "Prekli\u010di",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Vnosa ni mogo\u010de najti",
L_ERR_INVALIDDATE: "Navedli ste neveljaven datum.",
L_FETCHING: "Pridobivanje zapisov  . . .",
L_FETCHINGNEXT: "Pridobivanje prej\u0161nje strani zapisov. . .",
L_FETCHINGPREV: "Pridobivanje prej\u0161nje strani zapisov. . .",
L_JAWS_GIGABYTES: "%1 gigabajtov",
L_JAWS_KILOBYTES: "%1 kilobajtov",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Razvr\u0161\u010deno nara\u0161\u010dajo\u010de",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 stolpec. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Razvr\u0161\u010deno padajo\u010de",
L_JAWS_LISTVIEW_NOENTRY: "izbran ni noben vnos",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Pritisnite tipko enter, da razvrstite nara\u0161\u010dajo\u010de",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Pritisnite tipko enter, da razvrstite padajo\u010de",
L_JAWS_LISTVIEW_UNDORESORT: "Pritisnite tipko enter, da razveljavite ponovno razvr\u0161\u010danje",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 stolpec. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 od %3",
L_JAWS_MEGABYTES: "%1 megabajtov",
L_JAWS_TERABYTES: "%1 terabajtov",
L_NARROW_DEFAULT: "Razvrsti po privzetku",
L_NARROW_NOTITLE: "Brez naslova",
L_NARROW_SORTBY: "Razvrsti po %1",
L_SEARCH: "Iskanje",
L_STARTSWITH_COLUMN: "Izberite stolpec, ki ga \u017eelite razvrstiti po:",
L_STARTSWITH_INVALID_NUMBER: "Dolo\u010dena je neveljavna \u0161tevilka",
L_STARTSWITH_SEARCH: "Iskanje vnosov, ki se za\u010dnejo z:",
L_STARTSWITH_TITLE: "Se za\u010dne z ...",
L_UPDATINGVIEW_MESSAGE: "Pogled se verjetno ravnokar posodablja v stre\u017eniku.\nPrikazal se bo takoj, ko bo posodobitev kon\u010dana.\nNadaljujete lahko z delom na drugih karticah, ali pa posku\u0161ate dostopati do drugih pogledov/map.",
L_VIEWMAIL: "Po\u0161ta"
})
