({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Jour %1 - dernier jour de l'ann\u00e9e",
L_CAL_LAST_MONTH: "Mois %1 - dernier mois de l'ann\u00e9e",
L_CAL_LAST_WEEK: "Semaine %1 - derni\u00e8re semaine de l'ann\u00e9e",
L_CAL_LEFT_DAY: "Jour %1 - %2 jour restant dans l'ann\u00e9e",
L_CAL_LEFT_DAYS: "Jour %1 - %2 jours restant dans l'ann\u00e9e",
L_CAL_LEFT_MONTH: "Mois %1 - %2 mois restant dans l'ann\u00e9e",
L_CAL_LEFT_MONTHS: "Mois %1 - %2 mois restant dans l'ann\u00e9e",
L_CAL_LEFT_WEEK: "Semaine %1 - %2 semaine restant dans l'ann\u00e9e",
L_CAL_LEFT_WEEKS: "Semaine %1 - %2 semaines restant dans l'ann\u00e9e",
L_CHARDAY_FRI: "V",
L_CHARDAY_MON: "L",
L_CHARDAY_SAT: "S",
L_CHARDAY_SUN: "D",
L_CHARDAY_THU: "J",
L_CHARDAY_TUE: "M",
L_CHARDAY_WED: "M",
L_NO_CAL_ENTRY_SELECTED: "Aucune entr\u00e9e d\'agenda s\u00e9lectionn\u00e9e.  S\u00e9lectionnez une entr\u00e9e, puis r\u00e9essayez.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "Aucune entr\u00e9e d'agenda pour %1."
})
