({
L_CAL_NAV_PREVIOUS: "Pr\u00e9c\u00e9dent",
L_CAL_NAV_NEXT: "Suivant",
L_CAL_NAV_MONTH: "Mois",
L_CAL_HEADER_DAYS_WEEK: "Jours de la semaine",
L_CAL_HEADER: "En-t\u00eate d'agenda",
L_CAL_HEADER_DAY: "En-t\u00eate de jour %1",
L_CAL_EVENT_ALLDAY: "Ev\u00e9nement sur une journ\u00e9e %1",
L_CAL_NOENTRY: "Pas d'entr\u00e9e",
L_CAL_GRID: "Grille d'agenda",
L_CAL_PICKER_POPUP: "S\u00e9lecteur de date en incrustation",
L_CAL_NAV_TIMESCALE_PREV_D: "Jour pr\u00e9c\u00e9dent",
L_CAL_NAV_TIMESCALE_NEXT_D: "Jour suivant",
L_CAL_NAV_TIMESCALE_PREV_T: "Deux jours pr\u00e9c\u00e9dents",
L_CAL_NAV_TIMESCALE_NEXT_T: "Deux jours suivants",
L_CAL_NAV_TIMESCALE_PREV_F: "Semaine de travail pr\u00e9c\u00e9dent",
L_CAL_NAV_TIMESCALE_NEXT_F: "Semaine de travail suivante",
L_CAL_NAV_TIMESCALE_PREV_W: "Semaine pr\u00e9c\u00e9dente",
L_CAL_NAV_TIMESCALE_NEXT_W: "Semaine suivante",
L_CAL_NAV_TIMESCALE_PREV_2: "Quinzaine pr\u00e9c\u00e9dente",
L_CAL_NAV_TIMESCALE_NEXT_2: "Quinzaine suivante",
L_CAL_NAV_TIMESCALE_PREV_M: "Mois pr\u00e9c\u00e9dent",
L_CAL_NAV_TIMESCALE_NEXT_M: "Mois suivant",
L_CAL_NAV_TIMESCALE_PREV_Y: "Ann\u00e9e pr\u00e9c\u00e9dente",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Ann\u00e9e suivante"
})
