({
L_CAL_NAV_PREVIOUS: "Vorheriger",
L_CAL_NAV_NEXT: "N\u00e4chster",
L_CAL_NAV_MONTH: "Monat",
L_CAL_HEADER_DAYS_WEEK: "Wochentage",
L_CAL_HEADER: "Kopfzeile Kalender",
L_CAL_HEADER_DAY: "Tag Kopfzeile %1",
L_CAL_EVENT_ALLDAY: "Ereignis alle Tage %1",
L_CAL_NOENTRY: "Keine Eintr\u00e4ge",
L_CAL_GRID: "Kalenderraster",
L_CAL_PICKER_POPUP: "Popupfenster f\u00fcr Datumsauswahl",
L_CAL_NAV_TIMESCALE_PREV_D: "Vorheriger Tag",
L_CAL_NAV_TIMESCALE_NEXT_D: "N\u00e4chster Tag",
L_CAL_NAV_TIMESCALE_PREV_T: "Die vorherigen zwei Tage",
L_CAL_NAV_TIMESCALE_NEXT_T: "Die n\u00e4chsten beiden Tage",
L_CAL_NAV_TIMESCALE_PREV_F: "Vorherige Arbeitswoche",
L_CAL_NAV_TIMESCALE_NEXT_F: "N\u00e4chste Arbeitswoche",
L_CAL_NAV_TIMESCALE_PREV_W: "Vorherige Woche",
L_CAL_NAV_TIMESCALE_NEXT_W: "N\u00e4chste Woche",
L_CAL_NAV_TIMESCALE_PREV_2: "Die vorherigen zwei Wochen",
L_CAL_NAV_TIMESCALE_NEXT_2: "Die n\u00e4chsten beiden Wochen",
L_CAL_NAV_TIMESCALE_PREV_M: "Vorheriger Monat",
L_CAL_NAV_TIMESCALE_NEXT_M: "N\u00e4chster Monat",
L_CAL_NAV_TIMESCALE_PREV_Y: "Vorjahr",
L_CAL_NAV_TIMESCALE_NEXT_Y: "N\u00e4chstes Jahr"
})
