({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Tag %1 - letzter Tag des Jahres",
L_CAL_LAST_MONTH: "Monat %1 - letzter Monat des Jahres",
L_CAL_LAST_WEEK: "Woche %1 - letzte Woche des Jahres",
L_CAL_LEFT_DAY: "Tag %1 - noch %2 Tag in diesem Jahr",
L_CAL_LEFT_DAYS: "Tag %1 - noch %2 Tage in diesem Jahr",
L_CAL_LEFT_MONTH: "Monat %1 - noch %2 Monat in diesem Jahr",
L_CAL_LEFT_MONTHS: "Monat %1 - noch %2 Monate in diesem Jahr",
L_CAL_LEFT_WEEK: "Woche %1 - noch %2 Woche in diesem Jahr",
L_CAL_LEFT_WEEKS: "Woche %1 - noch %2 Wochen in diesem Jahr",
L_CHARDAY_FRI: "F",
L_CHARDAY_MON: "M",
L_CHARDAY_SAT: "S",
L_CHARDAY_SUN: "S",
L_CHARDAY_THU: "D",
L_CHARDAY_TUE: "D",
L_CHARDAY_WED: "M",
L_NO_CAL_ENTRY_SELECTED: "Es wurde kein Kalendereintrag gefunden. W\u00e4hlen Sie einen Eintrag aus und versuchen Sie es erneut.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "Keine Kalendereintr\u00e4ge f\u00fcr %1 vorhanden."
})
