({
L_CAL_NAV_PREVIOUS: "Forrige",
L_CAL_NAV_NEXT: "Neste",
L_CAL_NAV_MONTH: "M\u00e5ned",
L_CAL_HEADER_DAYS_WEEK: "Ukedager",
L_CAL_HEADER: "Kalenderoverskrift",
L_CAL_HEADER_DAY: "Dagoverskrift %1",
L_CAL_EVENT_ALLDAY: "Heldagshendelse %1",
L_CAL_NOENTRY: "Ingen oppf\u00f8ringer",
L_CAL_GRID: "Kalenderrutenett",
L_CAL_PICKER_POPUP: "Datovelgermeny",
L_CAL_NAV_TIMESCALE_PREV_D: "Forrige dag",
L_CAL_NAV_TIMESCALE_NEXT_D: "Neste dag",
L_CAL_NAV_TIMESCALE_PREV_T: "Forrige to dager",
L_CAL_NAV_TIMESCALE_NEXT_T: "Neste to dager",
L_CAL_NAV_TIMESCALE_PREV_F: "Forrige arbeidsuke",
L_CAL_NAV_TIMESCALE_NEXT_F: "Neste arbeidsuke",
L_CAL_NAV_TIMESCALE_PREV_W: "Forrige uke",
L_CAL_NAV_TIMESCALE_NEXT_W: "Neste uke",
L_CAL_NAV_TIMESCALE_PREV_2: "Forrige to uker",
L_CAL_NAV_TIMESCALE_NEXT_2: "Neste to uker",
L_CAL_NAV_TIMESCALE_PREV_M: "Forrige m\u00e5ned",
L_CAL_NAV_TIMESCALE_NEXT_M: "Neste m\u00e5ned",
L_CAL_NAV_TIMESCALE_PREV_Y: "Forrige \u00e5r",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Neste \u00e5r"
})
