({
L_CAL_NAV_PREVIOUS: "Previous",
L_CAL_NAV_NEXT: "Next",
L_CAL_NAV_MONTH: "Month",
L_CAL_HEADER_DAYS_WEEK: "Days of the week",
L_CAL_HEADER: "Calendar header",
L_CAL_HEADER_DAY: "Day header %1",
L_CAL_EVENT_ALLDAY: "All day event %1",
L_CAL_NOENTRY: "No entries",
L_CAL_GRID: "Calendar grid",
L_CAL_PICKER_POPUP: "Date picker popup",
L_CAL_NAV_TIMESCALE_PREV_D: "Previous day",
L_CAL_NAV_TIMESCALE_NEXT_D: "Next day",
L_CAL_NAV_TIMESCALE_PREV_T: "Previous two days",
L_CAL_NAV_TIMESCALE_NEXT_T: "Next two days",
L_CAL_NAV_TIMESCALE_PREV_F: "Previous work week",
L_CAL_NAV_TIMESCALE_NEXT_F: "Next work week",
L_CAL_NAV_TIMESCALE_PREV_W: "Previous week",
L_CAL_NAV_TIMESCALE_NEXT_W: "Next week",
L_CAL_NAV_TIMESCALE_PREV_2: "Previous fortnight",
L_CAL_NAV_TIMESCALE_NEXT_2: "Next fortnight",
L_CAL_NAV_TIMESCALE_PREV_M: "Previous month",
L_CAL_NAV_TIMESCALE_NEXT_M: "Next month",
L_CAL_NAV_TIMESCALE_PREV_Y: "Previous year",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Next year"
})
