({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Day %1 - last day in the year",
L_CAL_LAST_MONTH: "Month %1 - last month in the year",
L_CAL_LAST_WEEK: "Week %1 - last week in the year",
L_CAL_LEFT_DAY: "Day %1 - %2 day left in the year",
L_CAL_LEFT_DAYS: "Day %1 - %2 days left in the year",
L_CAL_LEFT_MONTH: "Month %1 - %2 month left in the year",
L_CAL_LEFT_MONTHS: "Month %1 - %2 months left in the year",
L_CAL_LEFT_WEEK: "Week %1 - %2 week left in the year",
L_CAL_LEFT_WEEKS: "Week %1 - %2 weeks left in the year",
L_CHARDAY_FRI: "F",
L_CHARDAY_MON: "M",
L_CHARDAY_SAT: "S",
L_CHARDAY_SUN: "S",
L_CHARDAY_THU: "T",
L_CHARDAY_TUE: "T",
L_CHARDAY_WED: "W",
L_NO_CAL_ENTRY_SELECTED: "No Calendar entry was selected.  Select an entry and try again.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "No calendar entries for %1."
})
