({
D_DIR_DEFAULT: "ltr",
D_GIGABYTES: "%1 GB",
D_KILOBYTES: "%1 KB",
D_MEGABYTES: "%1 MB",
D_NUMFMT_DECIMALSYMBOL: ".",
D_NUMFMT_THOUSANDSSEPARATOR: ".",
D_PADDING_REVERSE: "padding-right",
D_TERABYTES: "%1 TB"
})
