({
L_CANCEL: "Abbrechen",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Eintrag wurde nicht gefunden",
L_ERR_INVALIDDATE: "Ung\u00fcltiges Datum angegeben.",
L_FETCHING: "Dokumente werden abgerufen . . .",
L_FETCHINGNEXT: "Dokumente der n\u00e4chsten Seite werden abgerufen . . .",
L_FETCHINGPREV: "Dokumente der vorherigen Seite werden abgerufen . . .",
L_JAWS_GIGABYTES: "%1 Gigabyte",
L_JAWS_KILOBYTES: "%1 Kilobyte",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Aufsteigend sortiert",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 Spalte. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Absteigend sortiert",
L_JAWS_LISTVIEW_NOENTRY: "Kein Eintrag ausgew\u00e4hlt",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Eingabetaste dr\u00fccken, um erneut aufsteigend zu sortieren",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Eingabetaste dr\u00fccken, um erneut absteigend zu sortieren",
L_JAWS_LISTVIEW_UNDORESORT: "Eingabetaste dr\u00fccken, um Sortierung r\u00fcckg\u00e4ngig zu machen",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 Spalte. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 von %3",
L_JAWS_MEGABYTES: "%1 Megabyte",
L_JAWS_TERABYTES: "%1 Terabyte",
L_NARROW_DEFAULT: "Standardm\u00e4\u00dfig sortieren",
L_NARROW_NOTITLE: "Ohne Titel",
L_NARROW_SORTBY: "Sortieren nach %1",
L_SEARCH: "Suchen",
L_STARTSWITH_COLUMN: "Spalte w\u00e4hlen, nach der sortiert werden soll:",
L_STARTSWITH_INVALID_NUMBER: "Ung\u00fcltige Zahl angegeben",
L_STARTSWITH_SEARCH: "Eintr\u00e4ge suchen, die beginnen mit:",
L_STARTSWITH_TITLE: "Beginnt mit...",
L_UPDATINGVIEW_MESSAGE: "Diese Ansicht wird wahrscheinlich auf dem Server aktualisiert.\nSie wird angezeigt, sobald die Aktualisierung abgeschlossen ist.\nSie k\u00f6nnen Ihre Arbeit in anderen Fenstern fortsetzen oder auf andere Ansichten/Ordner zugreifen.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "Neues Dokument ",
L_VIEWICONTIPS_ELM_10: "Erinnerung ",
L_VIEWICONTIPS_ELM_100: "Blaue Raute ",
L_VIEWICONTIPS_ELM_101: "Roter Aufw\u00e4rtspfeil ",
L_VIEWICONTIPS_ELM_102: "Roter Abw\u00e4rtspfeil ",
L_VIEWICONTIPS_ELM_103: "Roter Linksspfeil ",
L_VIEWICONTIPS_ELM_104: "Roter Rechtspfeil ",
L_VIEWICONTIPS_ELM_105: "Gr\u00fcner Aufw\u00e4rtspfeil ",
L_VIEWICONTIPS_ELM_106: "Gr\u00fcner Abw\u00e4rtspfeil ",
L_VIEWICONTIPS_ELM_107: "Gr\u00fcner Linksspfeil ",
L_VIEWICONTIPS_ELM_108: "Gr\u00fcner Rechtspfeil ",
L_VIEWICONTIPS_ELM_109: "Blauer Aufw\u00e4rtspfeil ",
L_VIEWICONTIPS_ELM_11: "Information ",
L_VIEWICONTIPS_ELM_110: "Blauer Abw\u00e4rtspfeil ",
L_VIEWICONTIPS_ELM_111: "Blauer Linksspfeil ",
L_VIEWICONTIPS_ELM_112: "Blauer Rechtspfeil ",
L_VIEWICONTIPS_ELM_113: "Blaue Anzeige ",
L_VIEWICONTIPS_ELM_114: "Gr\u00fcner Ball ",
L_VIEWICONTIPS_ELM_115: "Roter Ball ",
L_VIEWICONTIPS_ELM_116: "Brauner Ball ",
L_VIEWICONTIPS_ELM_117: "Blauer Ball ",
L_VIEWICONTIPS_ELM_118: "Dunkelblauer Ball ",
L_VIEWICONTIPS_ELM_119: "Violetter Ball ",
L_VIEWICONTIPS_ELM_12: "Text schreiben ",
L_VIEWICONTIPS_ELM_120: "Gelber Ball ",
L_VIEWICONTIPS_ELM_121: "Unge\u00f6ffneter wei\u00dfer Umschlag ",
L_VIEWICONTIPS_ELM_122: "Gesendete Nachricht ",
L_VIEWICONTIPS_ELM_123: "Unge\u00f6ffneter blauer Umschlag ",
L_VIEWICONTIPS_ELM_124: "Unge\u00f6ffneter roter Umschlag ",
L_VIEWICONTIPS_ELM_125: "Ge\u00f6ffneter wei\u00dfer Umschlag ",
L_VIEWICONTIPS_ELM_126: "Ge\u00f6ffneter gelber Umschlag ",
L_VIEWICONTIPS_ELM_127: "Ge\u00f6ffneter blauer Umschlag ",
L_VIEWICONTIPS_ELM_128: "Rote Umschlagr\u00fcckseite ",
L_VIEWICONTIPS_ELM_129: "Wei\u00dfe Umschlagr\u00fcckseite ",
L_VIEWICONTIPS_ELM_13: "Grafik ",
L_VIEWICONTIPS_ELM_130: "Gelbe Umschlagr\u00fcckseite ",
L_VIEWICONTIPS_ELM_131: "Rote Umschlagr\u00fcckseite ",
L_VIEWICONTIPS_ELM_132: "Wei\u00dfe Einladung ",
L_VIEWICONTIPS_ELM_133: "Gelbe Einladung ",
L_VIEWICONTIPS_ELM_134: "Rote Einladung ",
L_VIEWICONTIPS_ELM_135: "Lotus 123 ",
L_VIEWICONTIPS_ELM_136: "Textverarbeitungsdokument ",
L_VIEWICONTIPS_ELM_137: "Pr\u00e4sentation ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "Videokamera ",
L_VIEWICONTIPS_ELM_14: "Diagramm ",
L_VIEWICONTIPS_ELM_140: "Workflow-Dokument ",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_144: "Kreisdiagramm ",
L_VIEWICONTIPS_ELM_145: "Visio ",
L_VIEWICONTIPS_ELM_146: "Winter ",
L_VIEWICONTIPS_ELM_147: "Fr\u00fchling ",
L_VIEWICONTIPS_ELM_148: "Sommer ",
L_VIEWICONTIPS_ELM_149: "Herbst ",
L_VIEWICONTIPS_ELM_15: "Klang ",
L_VIEWICONTIPS_ELM_150: "Ausrufezeichen ",
L_VIEWICONTIPS_ELM_151: "Ziffer 1 ",
L_VIEWICONTIPS_ELM_152: "Ziffer 2 ",
L_VIEWICONTIPS_ELM_153: "Ziffer 3 ",
L_VIEWICONTIPS_ELM_154: "Ziffer 4 ",
L_VIEWICONTIPS_ELM_155: "Ziffer 5 ",
L_VIEWICONTIPS_ELM_156: "Kochen ",
L_VIEWICONTIPS_ELM_157: "Dokument ist unzul\u00e4ssig ",
L_VIEWICONTIPS_ELM_158: "Besprechung ",
L_VIEWICONTIPS_ELM_159: "Goldener Stern ",
L_VIEWICONTIPS_ELM_16: "Mikrofon ",
L_VIEWICONTIPS_ELM_160: "Termin ",
L_VIEWICONTIPS_ELM_161: "Widget ",
L_VIEWICONTIPS_ELM_162: "Frage ",
L_VIEWICONTIPS_ELM_163: "Vertraulich ",
L_VIEWICONTIPS_ELM_164: "Verschl\u00fcsselte Mail ",
L_VIEWICONTIPS_ELM_165: "Blaues Vorh\u00e4ngeschloss ",
L_VIEWICONTIPS_ELM_166: "Verkleidet ",
L_VIEWICONTIPS_ELM_167: "Blaues H\u00e4kchen ",
L_VIEWICONTIPS_ELM_168: "Aufgabe ",
L_VIEWICONTIPS_ELM_169: "Rotes Medallion ",
L_VIEWICONTIPS_ELM_17: "Grafik ",
L_VIEWICONTIPS_ELM_170: "Gelbes Medallion ",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Flugzeug ",
L_VIEWICONTIPS_ELM_174: "Auto ",
L_VIEWICONTIPS_ELM_175: "Geb\u00e4ude ",
L_VIEWICONTIPS_ELM_176: "Neues Dokument ",
L_VIEWICONTIPS_ELM_177: "Party-Ballon ",
L_VIEWICONTIPS_ELM_178: "Nachricht beantwortet ",
L_VIEWICONTIPS_ELM_179: "Nachricht weitergeleitet ",
L_VIEWICONTIPS_ELM_18: "Gr\u00fcne Anzeige ",
L_VIEWICONTIPS_ELM_180: "Nachricht beantwortet und weitergeleitet ",
L_VIEWICONTIPS_ELM_181: "Wiedervorlage - Hohe Priorit\u00e4t.",
L_VIEWICONTIPS_ELM_182: "Wiedervorlage - Normale Priorit\u00e4t.",
L_VIEWICONTIPS_ELM_183: "Wiedervorlage - Niedrige Priorit\u00e4t.",
L_VIEWICONTIPS_ELM_184: "Nur an mich gesendete ",
L_VIEWICONTIPS_ELM_185: "Nur an mich und an wenige Personen gesendete ",
L_VIEWICONTIPS_ELM_186: "Nur an mich und an viele Personen gesendete ",
L_VIEWICONTIPS_ELM_187: "Nicht verarbeiteter Besprechungshinweis ",
L_VIEWICONTIPS_ELM_188: "Ungelesene Nachricht ",
L_VIEWICONTIPS_ELM_189: "Online-Besprechung ",
L_VIEWICONTIPS_ELM_19: "Tabelle ",
L_VIEWICONTIPS_ELM_190: "Hohe Relevanz ",
L_VIEWICONTIPS_ELM_191: "Mittlere Relevanz ",
L_VIEWICONTIPS_ELM_192: "Niedrige Relevanz ",
L_VIEWICONTIPS_ELM_193: "Nicht relevant ",
L_VIEWICONTIPS_ELM_194: "Ganzt\u00e4gige Veranstaltung ",
L_VIEWICONTIPS_ELM_195: "Erinnerung ",
L_VIEWICONTIPS_ELM_196: "Neu geplant ",
L_VIEWICONTIPS_ELM_197: "Einladung ablehnen ",
L_VIEWICONTIPS_ELM_198: "Gegenvorschlag ",
L_VIEWICONTIPS_ELM_199: "Jahrestag ",
L_VIEWICONTIPS_ELM_2: "Nicht ge\u00f6ffneter Ordner ",
L_VIEWICONTIPS_ELM_20: "Text ",
L_VIEWICONTIPS_ELM_200: "Abgesagte Besprechung ",
L_VIEWICONTIPS_ELM_201: "Abgeschlossene Aufgabe ",
L_VIEWICONTIPS_ELM_202: "Angenommen ",
L_VIEWICONTIPS_ELM_203: "Abgelehnt ",
L_VIEWICONTIPS_ELM_204: "Hohe Priorit\u00e4t ",
L_VIEWICONTIPS_ELM_205: "Termin ",
L_VIEWICONTIPS_ELM_206: "Private Einladung ",
L_VIEWICONTIPS_ELM_207: "Emoticon 'Witz' ",
L_VIEWICONTIPS_ELM_208: "Emoticon 'Vertraulich' ",
L_VIEWICONTIPS_ELM_209: "Emoticon 'Pers\u00f6nlich' ",
L_VIEWICONTIPS_ELM_21: "Mehrere Dokumente ",
L_VIEWICONTIPS_ELM_210: "Angenommene Einladung ",
L_VIEWICONTIPS_ELM_211: "Gelesene Nachricht ",
L_VIEWICONTIPS_ELM_212: "Neue Einladung ",
L_VIEWICONTIPS_ELM_22: "Zwei Dokumente ",
L_VIEWICONTIPS_ELM_23: "News ",
L_VIEWICONTIPS_ELM_24: "Rotes Buch ",
L_VIEWICONTIPS_ELM_25: "Adressbuch ",
L_VIEWICONTIPS_ELM_26: "Ge\u00f6ffnetes Buch ",
L_VIEWICONTIPS_ELM_27: "Geschlossenes Buch ",
L_VIEWICONTIPS_ELM_28: "Wei\u00dfes Buch ",
L_VIEWICONTIPS_ELM_29: "Gerissene gelbe Seite ",
L_VIEWICONTIPS_ELM_3: "Person ",
L_VIEWICONTIPS_ELM_30: "Gerissene blaue Seite ",
L_VIEWICONTIPS_ELM_31: "Gl\u00fchbirne ein ",
L_VIEWICONTIPS_ELM_32: "Gl\u00fchbirne aus ",
L_VIEWICONTIPS_ELM_33: "Aktualisieren ",
L_VIEWICONTIPS_ELM_34: "Dokument durchsuchen ",
L_VIEWICONTIPS_ELM_35: "Durchsuchen des Dokuments abgeschlossen ",
L_VIEWICONTIPS_ELM_36: "Dokument zul\u00e4ssig ",
L_VIEWICONTIPS_ELM_37: "Dokument vollst\u00e4ndig ",
L_VIEWICONTIPS_ELM_38: "Dokument Problem ",
L_VIEWICONTIPS_ELM_39: "Dokument Frage ",
L_VIEWICONTIPS_ELM_4: "Gruppe ",
L_VIEWICONTIPS_ELM_40: "Dokument Vorsicht ",
L_VIEWICONTIPS_ELM_41: "Dokument gelb ",
L_VIEWICONTIPS_ELM_42: "Gelbes Antwortdokument ",
L_VIEWICONTIPS_ELM_43: "Blaues Antwortdokument ",
L_VIEWICONTIPS_ELM_44: "Telefon",
L_VIEWICONTIPS_ELM_45: "Aktives Telefon ",
L_VIEWICONTIPS_ELM_46: "Computer ",
L_VIEWICONTIPS_ELM_47: "Fax ",
L_VIEWICONTIPS_ELM_48: "CD-ROM ",
L_VIEWICONTIPS_ELM_49: "Floppy ",
L_VIEWICONTIPS_ELM_5: "Anhang ",
L_VIEWICONTIPS_ELM_50: "Diskette ",
L_VIEWICONTIPS_ELM_51: "Festplatte ",
L_VIEWICONTIPS_ELM_52: "Netzwerk ",
L_VIEWICONTIPS_ELM_53: "Computer ",
L_VIEWICONTIPS_ELM_54: "Server ",
L_VIEWICONTIPS_ELM_55: "Verbindung ",
L_VIEWICONTIPS_ELM_56: "Suchen ",
L_VIEWICONTIPS_ELM_57: "Schreiben ",
L_VIEWICONTIPS_ELM_58: "Entwurf ",
L_VIEWICONTIPS_ELM_59: "W\u00e4hrung ",
L_VIEWICONTIPS_ELM_6: "Verflochten ",
L_VIEWICONTIPS_ELM_60: "M\u00fcnzen ",
L_VIEWICONTIPS_ELM_61: "Schl\u00fcssel ",
L_VIEWICONTIPS_ELM_62: "Vorh\u00e4ngeschloss ",
L_VIEWICONTIPS_ELM_63: "Kalender ",
L_VIEWICONTIPS_ELM_64: "Uhr ",
L_VIEWICONTIPS_ELM_65: "Alarm ",
L_VIEWICONTIPS_ELM_66: "Fliegen ",
L_VIEWICONTIPS_ELM_67: "Satellit ",
L_VIEWICONTIPS_ELM_68: "Mappe ",
L_VIEWICONTIPS_ELM_69: "Privat ",
L_VIEWICONTIPS_ELM_7: "Tier ",
L_VIEWICONTIPS_ELM_70: "Globus ",
L_VIEWICONTIPS_ELM_71: "Gesundheit ",
L_VIEWICONTIPS_ELM_72: "Finanzen ",
L_VIEWICONTIPS_ELM_73: "Transportwesen ",
L_VIEWICONTIPS_ELM_74: "Chemie ",
L_VIEWICONTIPS_ELM_75: "Produktion ",
L_VIEWICONTIPS_ELM_76: "Versorgung ",
L_VIEWICONTIPS_ELM_77: "Telekommunikation ",
L_VIEWICONTIPS_ELM_78: "Bau ",
L_VIEWICONTIPS_ELM_79: "Sanduhr ",
L_VIEWICONTIPS_ELM_8: "Suchen ",
L_VIEWICONTIPS_ELM_80: "Verboten ",
L_VIEWICONTIPS_ELM_81: "Zur\u00fcckgewiesen ",
L_VIEWICONTIPS_ELM_82: "Abgeschlossen ",
L_VIEWICONTIPS_ELM_83: "Zul\u00e4ssig ",
L_VIEWICONTIPS_ELM_84: "Unzul\u00e4ssig ",
L_VIEWICONTIPS_ELM_85: "Gl\u00fccklich ",
L_VIEWICONTIPS_ELM_86: "Gleichg\u00fcltig ",
L_VIEWICONTIPS_ELM_87: "Traurig ",
L_VIEWICONTIPS_ELM_88: "Lauwarm ",
L_VIEWICONTIPS_ELM_89: "Warm ",
L_VIEWICONTIPS_ELM_9: "Netzwerkaktivit\u00e4t ",
L_VIEWICONTIPS_ELM_90: "Sehr hei\u00df ",
L_VIEWICONTIPS_ELM_91: "Bombe ",
L_VIEWICONTIPS_ELM_92: "Stoppschild ",
L_VIEWICONTIPS_ELM_93: "Stoppen ",
L_VIEWICONTIPS_ELM_94: "Achtung ",
L_VIEWICONTIPS_ELM_95: "Los ",
L_VIEWICONTIPS_ELM_96: "Positiv ",
L_VIEWICONTIPS_ELM_97: "Negativ ",
L_VIEWICONTIPS_ELM_98: "Rote Raute ",
L_VIEWICONTIPS_ELM_99: "Gr\u00fcne Raute ",
L_VIEWMAIL: "Mail"
})
