({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Giorno %1 - ultimo giorno dell'anno",
L_CAL_LAST_MONTH: "Mese %1 - ultimo mese dell'anno",
L_CAL_LAST_WEEK: "Settimana %1 - ultima settimana dell'anno",
L_CAL_LEFT_DAY: "Giorno %1 - manca %2 giorno alla fine dell'anno",
L_CAL_LEFT_DAYS: "Giorno %1 - mancano %2 giorni alla fine dell'anno",
L_CAL_LEFT_MONTH: "Mese %1 - manca %2 mese alla fine dell'anno",
L_CAL_LEFT_MONTHS: "Mese %1 - mancano %2 mesi alla fine dell'anno",
L_CAL_LEFT_WEEK: "Settimana %1 - manca %2 settimana alla fine dell'anno",
L_CAL_LEFT_WEEKS: "Settimana %1 - mancano %2 settimane alla fine dell'anno",
L_CHARDAY_FRI: "V",
L_CHARDAY_MON: "L",
L_CHARDAY_SAT: "S",
L_CHARDAY_SUN: "D",
L_CHARDAY_THU: "G",
L_CHARDAY_TUE: "M",
L_CHARDAY_WED: "M",
L_NO_CAL_ENTRY_SELECTED: "Nessuna voce del diario selezionata. Selezionarne una voce e riprovare.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "Nessuna voce di diario per %1."
})
