({
L_CAL_NAV_PREVIOUS: "Indietro",
L_CAL_NAV_NEXT: "Successivo",
L_CAL_NAV_MONTH: "Mese",
L_CAL_HEADER_DAYS_WEEK: "Giorni della settimana",
L_CAL_HEADER: "Intestazione calendario",
L_CAL_HEADER_DAY: "Intestazione giorno %1",
L_CAL_EVENT_ALLDAY: "Evento di un giorno completo %1",
L_CAL_NOENTRY: "Nessuna voce",
L_CAL_GRID: "Griglia calendario",
L_CAL_PICKER_POPUP: "Pop-up selezione data",
L_CAL_NAV_TIMESCALE_PREV_D: "Giorno precedente",
L_CAL_NAV_TIMESCALE_NEXT_D: "Giorno successivo",
L_CAL_NAV_TIMESCALE_PREV_T: "Due giorni precedenti",
L_CAL_NAV_TIMESCALE_NEXT_T: "Due giorni successivi",
L_CAL_NAV_TIMESCALE_PREV_F: "Settimana lavorativa precedente",
L_CAL_NAV_TIMESCALE_NEXT_F: "Settimana lavorativa successiva",
L_CAL_NAV_TIMESCALE_PREV_W: "Settimana precedente",
L_CAL_NAV_TIMESCALE_NEXT_W: "Settimana successiva",
L_CAL_NAV_TIMESCALE_PREV_2: "Due settimane precedenti",
L_CAL_NAV_TIMESCALE_NEXT_2: "Due settimane successive",
L_CAL_NAV_TIMESCALE_PREV_M: "Mese precedente",
L_CAL_NAV_TIMESCALE_NEXT_M: "Mese successivo",
L_CAL_NAV_TIMESCALE_PREV_Y: "Anno precedente",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Anno successivo"
})
