({
PickerCheckBox_OK: "OK",
PickerCheckBox_Cancel: "Peruuta",
PickerList_OK: "OK",
PickerList_Cancel: "Peruuta",
PickerListSearch_Search: "Hae",
PickerListSearch_OK: "OK",
PickerListSearch_Cancel: "Peruuta",
PickerListSearch_Value: "Arvo",
PickerListSearch_Values: "Arvot",
PickerName_Search: "Hae",
PickerName_Add: "Lis\u00e4\u00e4",
PickerName_AddSelection: "Lis\u00e4\u00e4 valitut nimiluetteloon",
PickerName_Remove: "Poista",
PickerName_RemoveAll: "Poista kaikki",
PickerName_OK: "OK",
PickerName_Cancel: "Peruuta",
PickerName_SearchIn: "Hae kohteesta",
PickerName_SearchFor: "Hakusana(t)",
PickerName_unSelectedListLabel: "Valittavien arvojen luettelo",
PickerName_selectedListLabel: "Valittujen arvojen luettelo"
})
