({
L_CANCEL: "Cancel",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Entry not found",
L_ERR_INVALIDDATE: "Invalid date specified.",
L_FETCHING: "Retrieving records . . .",
L_FETCHINGNEXT: "Retrieving next page of records . . .",
L_FETCHINGPREV: "Retrieving previous page of records . . .",
L_JAWS_GIGABYTES: "%1Gigabytes",
L_JAWS_KILOBYTES: "%1Kirobytes",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Ascendingly sorted",
L_JAWS_LISTVIEW_COLUMN: "%1 %2 column. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Descendingly sorted",
L_JAWS_LISTVIEW_NOENTRY: "no entry selected",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Press enter key to resort ascendingly",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Press enter key to resort descendingly",
L_JAWS_LISTVIEW_UNDORESORT: "Press enter key to undo resort",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "%1 column. ",
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 of %3",
L_JAWS_MEGABYTES: "%1Megabytes",
L_JAWS_TERABYTES: "%1Terabytes",
L_NARROW_DEFAULT: "Sort by default",
L_NARROW_NOTITLE: "No title",
L_NARROW_SORTBY: "Sort by %1",
L_SEARCH: "Search",
L_STARTSWITH_COLUMN: "Choose the column to sort by:",
L_STARTSWITH_INVALID_NUMBER: "Invalid number specified",
L_STARTSWITH_SEARCH: "Search for entries that start with:",
L_STARTSWITH_TITLE: "Starts With...",
L_UPDATINGVIEW_MESSAGE: "This view is likely being updated on the server.\nIt will display as soon as this update completes.\nYou can continue working with other tabs or try accessing other views/folders.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "New document ",
L_VIEWICONTIPS_ELM_10: "Reminder ",
L_VIEWICONTIPS_ELM_100: "Blue diamond ",
L_VIEWICONTIPS_ELM_101: "Red up arrow ",
L_VIEWICONTIPS_ELM_102: "Red down arrow ",
L_VIEWICONTIPS_ELM_103: "Red left arrow ",
L_VIEWICONTIPS_ELM_104: "Red right arrow ",
L_VIEWICONTIPS_ELM_105: "Green up arrow ",
L_VIEWICONTIPS_ELM_106: "Green down arrow ",
L_VIEWICONTIPS_ELM_107: "Green left arrow ",
L_VIEWICONTIPS_ELM_108: "Green right arrow ",
L_VIEWICONTIPS_ELM_109: "Blue up arrow ",
L_VIEWICONTIPS_ELM_11: "Information ",
L_VIEWICONTIPS_ELM_110: "Blue down arrow ",
L_VIEWICONTIPS_ELM_111: "Blue left arrow ",
L_VIEWICONTIPS_ELM_112: "Blue right arrow ",
L_VIEWICONTIPS_ELM_113: "Blue display ",
L_VIEWICONTIPS_ELM_114: "Green ball ",
L_VIEWICONTIPS_ELM_115: "Red ball ",
L_VIEWICONTIPS_ELM_116: "Brown ball ",
L_VIEWICONTIPS_ELM_117: "Blue ball ",
L_VIEWICONTIPS_ELM_118: "Dark blue ball ",
L_VIEWICONTIPS_ELM_119: "Purple ball ",
L_VIEWICONTIPS_ELM_12: "Write text ",
L_VIEWICONTIPS_ELM_120: "Yellow ball ",
L_VIEWICONTIPS_ELM_121: "Unopened white envelope ",
L_VIEWICONTIPS_ELM_122: "Sent message ",
L_VIEWICONTIPS_ELM_123: "Unopened blue envelope ",
L_VIEWICONTIPS_ELM_124: "Unopened red envelope ",
L_VIEWICONTIPS_ELM_125: "Opened white envelope ",
L_VIEWICONTIPS_ELM_126: "Opened yellow envelope ",
L_VIEWICONTIPS_ELM_127: "Opened blue envelope ",
L_VIEWICONTIPS_ELM_128: "Red envelope back ",
L_VIEWICONTIPS_ELM_129: "White envelope back ",
L_VIEWICONTIPS_ELM_13: "Graphic ",
L_VIEWICONTIPS_ELM_130: "Yellow envelope back ",
L_VIEWICONTIPS_ELM_131: "Red envelope back ",
L_VIEWICONTIPS_ELM_132: "White invitation ",
L_VIEWICONTIPS_ELM_133: "Yellow invitation ",
L_VIEWICONTIPS_ELM_134: "Red invitation ",
L_VIEWICONTIPS_ELM_135: "Lotus 123 ",
L_VIEWICONTIPS_ELM_136: "Word processing document ",
L_VIEWICONTIPS_ELM_137: "Presentation ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "Video camera ",
L_VIEWICONTIPS_ELM_14: "Chart ",
L_VIEWICONTIPS_ELM_140: "Workflow document ",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_144: "Pie chart ",
L_VIEWICONTIPS_ELM_145: "Visio ",
L_VIEWICONTIPS_ELM_146: "Winter ",
L_VIEWICONTIPS_ELM_147: "Spring ",
L_VIEWICONTIPS_ELM_148: "Summer ",
L_VIEWICONTIPS_ELM_149: "Fall ",
L_VIEWICONTIPS_ELM_15: "Sound ",
L_VIEWICONTIPS_ELM_150: "Exclamation Point ",
L_VIEWICONTIPS_ELM_151: "Number 1 ",
L_VIEWICONTIPS_ELM_152: "Number 2 ",
L_VIEWICONTIPS_ELM_153: "Number 3 ",
L_VIEWICONTIPS_ELM_154: "Number 4 ",
L_VIEWICONTIPS_ELM_155: "Number 5 ",
L_VIEWICONTIPS_ELM_156: "Cooking ",
L_VIEWICONTIPS_ELM_157: "Document unacceptable ",
L_VIEWICONTIPS_ELM_158: "Meeting ",
L_VIEWICONTIPS_ELM_159: "Gold star ",
L_VIEWICONTIPS_ELM_16: "Microphone ",
L_VIEWICONTIPS_ELM_160: "Appointment ",
L_VIEWICONTIPS_ELM_161: "Widget ",
L_VIEWICONTIPS_ELM_162: "Question ",
L_VIEWICONTIPS_ELM_163: "Confidential ",
L_VIEWICONTIPS_ELM_164: "Encrypted mail ",
L_VIEWICONTIPS_ELM_165: "Blue padlock ",
L_VIEWICONTIPS_ELM_166: "Disguised ",
L_VIEWICONTIPS_ELM_167: "Blue checkmark ",
L_VIEWICONTIPS_ELM_168: "To Do ",
L_VIEWICONTIPS_ELM_169: "Red medallion ",
L_VIEWICONTIPS_ELM_17: "Graphic ",
L_VIEWICONTIPS_ELM_170: "Yellow medallion ",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Airplane ",
L_VIEWICONTIPS_ELM_174: "Car ",
L_VIEWICONTIPS_ELM_175: "Building ",
L_VIEWICONTIPS_ELM_176: "New Document ",
L_VIEWICONTIPS_ELM_177: "Party balloon ",
L_VIEWICONTIPS_ELM_178: "Message replied to ",
L_VIEWICONTIPS_ELM_179: "Message forwarded ",
L_VIEWICONTIPS_ELM_18: "Green display ",
L_VIEWICONTIPS_ELM_180: "Message replied to and forwarded ",
L_VIEWICONTIPS_ELM_181: "Follow up high priority.",
L_VIEWICONTIPS_ELM_182: "Follow up normal priority.",
L_VIEWICONTIPS_ELM_183: "Follow up low priority.",
L_VIEWICONTIPS_ELM_184: "Sent to me only ",
L_VIEWICONTIPS_ELM_185: "Sent to me and a few people ",
L_VIEWICONTIPS_ELM_186: "Sent to me and many people ",
L_VIEWICONTIPS_ELM_187: "Unprocessed meeting notice ",
L_VIEWICONTIPS_ELM_188: "Unread message ",
L_VIEWICONTIPS_ELM_189: "Online meeting ",
L_VIEWICONTIPS_ELM_19: "Table ",
L_VIEWICONTIPS_ELM_190: "High relevance ",
L_VIEWICONTIPS_ELM_191: "Medium relevance ",
L_VIEWICONTIPS_ELM_192: "Low relevance ",
L_VIEWICONTIPS_ELM_193: "Not relevant ",
L_VIEWICONTIPS_ELM_194: "All day event ",
L_VIEWICONTIPS_ELM_195: "Reminder ",
L_VIEWICONTIPS_ELM_196: "Rescheduled ",
L_VIEWICONTIPS_ELM_197: "Decline invitation ",
L_VIEWICONTIPS_ELM_198: "Countered invitation ",
L_VIEWICONTIPS_ELM_199: "Anniversary ",
L_VIEWICONTIPS_ELM_2: "Unopened folder ",
L_VIEWICONTIPS_ELM_20: "Text ",
L_VIEWICONTIPS_ELM_200: "Cancelled meeting ",
L_VIEWICONTIPS_ELM_201: "Completed to do ",
L_VIEWICONTIPS_ELM_202: "Accepted ",
L_VIEWICONTIPS_ELM_203: "Declined ",
L_VIEWICONTIPS_ELM_204: "High priority ",
L_VIEWICONTIPS_ELM_205: "Appointment ",
L_VIEWICONTIPS_ELM_206: "Private invitation ",
L_VIEWICONTIPS_ELM_207: "Joke emoticon ",
L_VIEWICONTIPS_ELM_208: "Confidential emoticon ",
L_VIEWICONTIPS_ELM_209: "Personal emoticon ",
L_VIEWICONTIPS_ELM_21: "Multiple documents ",
L_VIEWICONTIPS_ELM_210: "Accepted invitation ",
L_VIEWICONTIPS_ELM_211: "Read message ",
L_VIEWICONTIPS_ELM_212: "New invitation ",
L_VIEWICONTIPS_ELM_22: "Two documents ",
L_VIEWICONTIPS_ELM_23: "News ",
L_VIEWICONTIPS_ELM_24: "Red book ",
L_VIEWICONTIPS_ELM_25: "Address book ",
L_VIEWICONTIPS_ELM_26: "Open book ",
L_VIEWICONTIPS_ELM_27: "Closed book ",
L_VIEWICONTIPS_ELM_28: "White book ",
L_VIEWICONTIPS_ELM_29: "Torn yellow page ",
L_VIEWICONTIPS_ELM_3: "Person ",
L_VIEWICONTIPS_ELM_30: "Torn blue page ",
L_VIEWICONTIPS_ELM_31: "Light bulb on ",
L_VIEWICONTIPS_ELM_32: "Light bulb off ",
L_VIEWICONTIPS_ELM_33: "Refresh ",
L_VIEWICONTIPS_ELM_34: "Search document ",
L_VIEWICONTIPS_ELM_35: "Search document completed ",
L_VIEWICONTIPS_ELM_36: "Document acceptable ",
L_VIEWICONTIPS_ELM_37: "Document complete ",
L_VIEWICONTIPS_ELM_38: "Document problem ",
L_VIEWICONTIPS_ELM_39: "Document question ",
L_VIEWICONTIPS_ELM_4: "Group ",
L_VIEWICONTIPS_ELM_40: "Document caution ",
L_VIEWICONTIPS_ELM_41: "Document yellow ",
L_VIEWICONTIPS_ELM_42: "Response yellow document ",
L_VIEWICONTIPS_ELM_43: "Response blue document ",
L_VIEWICONTIPS_ELM_44: "Phone ",
L_VIEWICONTIPS_ELM_45: "Active phone ",
L_VIEWICONTIPS_ELM_46: "Computer terminal ",
L_VIEWICONTIPS_ELM_47: "Fax ",
L_VIEWICONTIPS_ELM_48: "CD-ROM ",
L_VIEWICONTIPS_ELM_49: "Floppy disk ",
L_VIEWICONTIPS_ELM_5: "Attachment ",
L_VIEWICONTIPS_ELM_50: "Diskette ",
L_VIEWICONTIPS_ELM_51: "Hard drive ",
L_VIEWICONTIPS_ELM_52: "Network ",
L_VIEWICONTIPS_ELM_53: "Computer ",
L_VIEWICONTIPS_ELM_54: "Server ",
L_VIEWICONTIPS_ELM_55: "Connection ",
L_VIEWICONTIPS_ELM_56: "Find ",
L_VIEWICONTIPS_ELM_57: "Write ",
L_VIEWICONTIPS_ELM_58: "Draft ",
L_VIEWICONTIPS_ELM_59: "Currency ",
L_VIEWICONTIPS_ELM_6: "Interwoven ",
L_VIEWICONTIPS_ELM_60: "Coins ",
L_VIEWICONTIPS_ELM_61: "Key ",
L_VIEWICONTIPS_ELM_62: "Padlock ",
L_VIEWICONTIPS_ELM_63: "Calendar ",
L_VIEWICONTIPS_ELM_64: "Clock ",
L_VIEWICONTIPS_ELM_65: "Alarm ",
L_VIEWICONTIPS_ELM_66: "Flying ",
L_VIEWICONTIPS_ELM_67: "Satellite ",
L_VIEWICONTIPS_ELM_68: "Briefcase ",
L_VIEWICONTIPS_ELM_69: "Home ",
L_VIEWICONTIPS_ELM_7: "Animal ",
L_VIEWICONTIPS_ELM_70: "Globe ",
L_VIEWICONTIPS_ELM_71: "Health ",
L_VIEWICONTIPS_ELM_72: "Finance ",
L_VIEWICONTIPS_ELM_73: "Transportation ",
L_VIEWICONTIPS_ELM_74: "Chemical ",
L_VIEWICONTIPS_ELM_75: "Manufacturing ",
L_VIEWICONTIPS_ELM_76: "Utilities ",
L_VIEWICONTIPS_ELM_77: "Telecommunication ",
L_VIEWICONTIPS_ELM_78: "Construction ",
L_VIEWICONTIPS_ELM_79: "Hourglass ",
L_VIEWICONTIPS_ELM_8: "Search ",
L_VIEWICONTIPS_ELM_80: "Banned ",
L_VIEWICONTIPS_ELM_81: "Rejected ",
L_VIEWICONTIPS_ELM_82: "Completed ",
L_VIEWICONTIPS_ELM_83: "Acceptable ",
L_VIEWICONTIPS_ELM_84: "Unacceptable ",
L_VIEWICONTIPS_ELM_85: "Happy ",
L_VIEWICONTIPS_ELM_86: "Indifferent ",
L_VIEWICONTIPS_ELM_87: "Sad ",
L_VIEWICONTIPS_ELM_88: "Lukewarm ",
L_VIEWICONTIPS_ELM_89: "Warm ",
L_VIEWICONTIPS_ELM_9: "Network activity ",
L_VIEWICONTIPS_ELM_90: "Very hot ",
L_VIEWICONTIPS_ELM_91: "Bomb ",
L_VIEWICONTIPS_ELM_92: "Stop sign ",
L_VIEWICONTIPS_ELM_93: "Stop ",
L_VIEWICONTIPS_ELM_94: "Caution ",
L_VIEWICONTIPS_ELM_95: "Go ",
L_VIEWICONTIPS_ELM_96: "Positive ",
L_VIEWICONTIPS_ELM_97: "Negative ",
L_VIEWICONTIPS_ELM_98: "Red diamond ",
L_VIEWICONTIPS_ELM_99: "Green diamond ",
L_VIEWMAIL: "Mail"
})
