({
L_CANCEL: "Peruuta",
L_DOCUMENTS_SELECTED: "%1 documents selected",
L_ENTRY_NOT_FOUND: "Merkint\u00e4\u00e4 ei l\u00f6ydy",
L_ERR_INVALIDDATE: "P\u00e4iv\u00e4m\u00e4\u00e4r\u00e4 ei kelpaa",
L_FETCHING: "Noudetaan tietueita . .  .",
L_FETCHINGNEXT: "Noudetaan seuraavaa tietuesivua . .  .",
L_FETCHINGPREV: "Noudetaan edellist\u00e4 tietuesivua . .  .",
L_JAWS_GIGABYTES: "%1 gigatavua",
L_JAWS_KILOBYTES: "%1 kilotavua",
L_JAWS_LISTVIEW_ASCENDINGSORTED: "Lajiteltu nousevasti",
L_JAWS_LISTVIEW_COLUMN: "%1 sarake %2. %3",
L_JAWS_LISTVIEW_DESCENDINGSORTED: "Lajiteltu laskevasti",
L_JAWS_LISTVIEW_NOENTRY: "yht\u00e4\u00e4n merkint\u00e4\u00e4 ei ole valittu",
L_JAWS_LISTVIEW_NOSORTED: "",
L_JAWS_LISTVIEW_RESORTASCENDING: "Lajittele uudelleen nousevasti painamalla Enter-n\u00e4pp\u00e4int\u00e4",
L_JAWS_LISTVIEW_RESORTDESCENDING: "Lajittele uudelleen laskevasti painamalla Enter-n\u00e4pp\u00e4int\u00e4",
L_JAWS_LISTVIEW_UNDORESORT: "Kumoa uudelleenlajittelu painamalla Enter-n\u00e4pp\u00e4int\u00e4",
L_JAWS_LISTVIEW_WITHAPPLICATION: "%1 %2",
L_JAWS_LISTVIEW_WITHCOLNAME: "Sarake %1.", 
L_JAWS_LISTVIEW_WITHPAGENUM: "%1 %2 / %3",
L_JAWS_MEGABYTES: "%1 megatavua",
L_JAWS_TERABYTES: "%1 teratavua",
L_NARROW_DEFAULT: "Oletuslajitteluperuste",
L_NARROW_NOTITLE: "Ei otsikkoa",
L_NARROW_SORTBY: "Lajitteluperuste %1&nbsp;%2&nbsp;",
L_SEARCH: "Hae",
L_STARTSWITH_COLUMN: "Valitse lajiteltava sarake:",
L_STARTSWITH_INVALID_NUMBER: "M\u00e4\u00e4ritetty luku on virheellinen",
L_STARTSWITH_SEARCH: "Hae merkint\u00f6j\u00e4, jotka alkavat:",
L_STARTSWITH_TITLE: "Alkaa...",
L_UPDATINGVIEW_MESSAGE: "T\u00e4t\u00e4 n\u00e4kym\u00e4\u00e4 todenn\u00e4k\u00f6isesti p\u00e4ivitet\u00e4\u00e4n palvelimesta.\nSe n\u00e4kyy heti, kun p\u00e4ivitys on valmis.\nVoit jatkaa muiden v\u00e4lilehtien k\u00e4sittelemist\u00e4 tai yritt\u00e4\u00e4 k\u00e4ytt\u00e4\u00e4 muita n\u00e4kymi\u00e4/kansioita.",
L_VIEWICONTIPS_ELM_0: "",
L_VIEWICONTIPS_ELM_1: "Uusi asiakirja ",
L_VIEWICONTIPS_ELM_10: "Muistutus ",
L_VIEWICONTIPS_ELM_100: "Sininen vinoneli\u00f6 ",
L_VIEWICONTIPS_ELM_101: "Punainen yl\u00e4nuoli ",
L_VIEWICONTIPS_ELM_102: "Punainen alanuoli ",
L_VIEWICONTIPS_ELM_103: "Punainen nuoli vasemmalle ",
L_VIEWICONTIPS_ELM_104: "Punainen nuoli oikealle ",
L_VIEWICONTIPS_ELM_105: "Vihre\u00e4 yl\u00e4nuoli ",
L_VIEWICONTIPS_ELM_106: "Vihre\u00e4 alanuoli ",
L_VIEWICONTIPS_ELM_107: "Vihre\u00e4 nuoli vasemmalle ",
L_VIEWICONTIPS_ELM_108: "Vihre\u00e4 nuoli oikealle ",
L_VIEWICONTIPS_ELM_109: "Sininen yl\u00e4nuoli ",
L_VIEWICONTIPS_ELM_11: "Tiedot ",
L_VIEWICONTIPS_ELM_110: "Sininen alanuoli ",
L_VIEWICONTIPS_ELM_111: "Sininen nuoli vasemmalle ",
L_VIEWICONTIPS_ELM_112: "Sininen nuoli oikealle ",
L_VIEWICONTIPS_ELM_113: "Sininen n\u00e4ytt\u00f6 ",
L_VIEWICONTIPS_ELM_114: "Vihre\u00e4 pallo ",
L_VIEWICONTIPS_ELM_115: "Punainen pallo ",
L_VIEWICONTIPS_ELM_116: "Ruskea pallo ",
L_VIEWICONTIPS_ELM_117: "Sininen pallo ",
L_VIEWICONTIPS_ELM_118: "Tummansininen pallo ",
L_VIEWICONTIPS_ELM_119: "Purppura pallo ",
L_VIEWICONTIPS_ELM_12: "Kirjoita teksti\u00e4 ",
L_VIEWICONTIPS_ELM_120: "Keltainen pallo ",
L_VIEWICONTIPS_ELM_121: "Avaamaton valkoinen kirjekuori ",
L_VIEWICONTIPS_ELM_122: "L\u00e4hetetty viesti",
L_VIEWICONTIPS_ELM_123: "Avaamaton sininen kirjekuori ",
L_VIEWICONTIPS_ELM_124: "Avaamaton punainen kirjekuori ",
L_VIEWICONTIPS_ELM_125: "Avattu valkoinen kirjekuori ",
L_VIEWICONTIPS_ELM_126: "Avattu keltainen kirjekuori ",
L_VIEWICONTIPS_ELM_127: "Avattu sininen kirjekuori ",
L_VIEWICONTIPS_ELM_128: "Punainen kirjekuori takaa ",
L_VIEWICONTIPS_ELM_129: "Valkoinen kirjekuori takaa ",
L_VIEWICONTIPS_ELM_13: "Kuva ",
L_VIEWICONTIPS_ELM_130: "Keltainen kirjekuori takaa ",
L_VIEWICONTIPS_ELM_131: "Punainen kirjekuori takaa ",
L_VIEWICONTIPS_ELM_132: "Valkoinen kutsu ",
L_VIEWICONTIPS_ELM_133: "Keltainen kutsu ",
L_VIEWICONTIPS_ELM_134: "Punainen kutsu ",
L_VIEWICONTIPS_ELM_135: "Lotus 123 ",
L_VIEWICONTIPS_ELM_136: "Tekstink\u00e4sittelyasiakirja ",
L_VIEWICONTIPS_ELM_137: "Esitys ",
L_VIEWICONTIPS_ELM_138: "Lotus Approach ",
L_VIEWICONTIPS_ELM_139: "Videokamera ",
L_VIEWICONTIPS_ELM_14: "Kaavio ",
L_VIEWICONTIPS_ELM_140: "Ty\u00f6nkulkuasiakirja ",
L_VIEWICONTIPS_ELM_141: "Microsoft Excel ",
L_VIEWICONTIPS_ELM_142: "Microsoft Word ",
L_VIEWICONTIPS_ELM_143: "Microsoft Powerpoint ",
L_VIEWICONTIPS_ELM_144: "Ympyr\u00e4kaavio ",
L_VIEWICONTIPS_ELM_145: "Visio ",
L_VIEWICONTIPS_ELM_146: "Talvi ",
L_VIEWICONTIPS_ELM_147: "Kev\u00e4t ",
L_VIEWICONTIPS_ELM_148: "Kes\u00e4 ",
L_VIEWICONTIPS_ELM_149: "Syksy ",
L_VIEWICONTIPS_ELM_15: "\u00c4\u00e4ni ",
L_VIEWICONTIPS_ELM_150: "Huutomerkki ",
L_VIEWICONTIPS_ELM_151: "Numero 1 ",
L_VIEWICONTIPS_ELM_152: "Numero 2 ",
L_VIEWICONTIPS_ELM_153: "Numero 3 ",
L_VIEWICONTIPS_ELM_154: "Numero 4 ",
L_VIEWICONTIPS_ELM_155: "Numero 5 ",
L_VIEWICONTIPS_ELM_156: "Keitt\u00e4minen ",
L_VIEWICONTIPS_ELM_157: "Asiakirja ei kelpaa ",
L_VIEWICONTIPS_ELM_158: "Kokous ",
L_VIEWICONTIPS_ELM_159: "Kultainen t\u00e4hti ",
L_VIEWICONTIPS_ELM_16: "Mikrofoni ",
L_VIEWICONTIPS_ELM_160: "Tapaaminen ",
L_VIEWICONTIPS_ELM_161: "Widget ",
L_VIEWICONTIPS_ELM_162: "Kysymys ",
L_VIEWICONTIPS_ELM_163: "Luottamuksellinen ",
L_VIEWICONTIPS_ELM_164: "Salattu posti ",
L_VIEWICONTIPS_ELM_165: "Sininen lukko ",
L_VIEWICONTIPS_ELM_166: "Piilotettu ",
L_VIEWICONTIPS_ELM_167: "Sininen valintamerkki ",
L_VIEWICONTIPS_ELM_168: "Teht\u00e4v\u00e4luettelo",
L_VIEWICONTIPS_ELM_169: "Punainen medaljonki ",
L_VIEWICONTIPS_ELM_17: "Kuva ",
L_VIEWICONTIPS_ELM_170: "Keltainen medaljonki ",
L_VIEWICONTIPS_ELM_171: "Lotus Word Pro ",
L_VIEWICONTIPS_ELM_172: "Lotus Freelance ",
L_VIEWICONTIPS_ELM_173: "Lentokone ",
L_VIEWICONTIPS_ELM_174: "Auto ",
L_VIEWICONTIPS_ELM_175: "Rakennus ",
L_VIEWICONTIPS_ELM_176: "Uusi asiakirja ",
L_VIEWICONTIPS_ELM_177: "Ilmapallo ",
L_VIEWICONTIPS_ELM_178: "Vastattu viesti ",
L_VIEWICONTIPS_ELM_179: "V\u00e4litetty viesti ",
L_VIEWICONTIPS_ELM_18: "Vihre\u00e4 n\u00e4ytt\u00f6 ",
L_VIEWICONTIPS_ELM_180: "Vastattu ja v\u00e4litetty viesti ",
L_VIEWICONTIPS_ELM_181: "Eritt\u00e4in t\u00e4rke\u00e4 seuranta.",
L_VIEWICONTIPS_ELM_182: "Normaalin t\u00e4rke\u00e4 seuranta.",
L_VIEWICONTIPS_ELM_183: "Ei t\u00e4rke\u00e4 seuranta.",
L_VIEWICONTIPS_ELM_184: "L\u00e4hetetty vain minulle ",
L_VIEWICONTIPS_ELM_185: "L\u00e4hetetty minulle ja muutamalle muulle ",
L_VIEWICONTIPS_ELM_186: "L\u00e4hetetty minulle ja useille muille",
L_VIEWICONTIPS_ELM_187: "K\u00e4sittelem\u00e4t\u00f6n kokousilmoitus ",
L_VIEWICONTIPS_ELM_188: "Lukematon viesti ",
L_VIEWICONTIPS_ELM_189: "Online-kokous ",
L_VIEWICONTIPS_ELM_19: "Taulukko ",
L_VIEWICONTIPS_ELM_190: "Eritt\u00e4in t\u00e4rke\u00e4 ",
L_VIEWICONTIPS_ELM_191: "Tavallisen t\u00e4rke\u00e4 ",
L_VIEWICONTIPS_ELM_192: "Ei kovin t\u00e4rke\u00e4 ",
L_VIEWICONTIPS_ELM_193: "Ei t\u00e4rke\u00e4 ",
L_VIEWICONTIPS_ELM_194: "Koko p\u00e4iv\u00e4n tapahtuma ",
L_VIEWICONTIPS_ELM_195: "Muistutus ",
L_VIEWICONTIPS_ELM_196: "Siirretty ",
L_VIEWICONTIPS_ELM_197: "Hylk\u00e4\u00e4 kutsu ",
L_VIEWICONTIPS_ELM_198: "Vastaehdotus kutsuun ",
L_VIEWICONTIPS_ELM_199: "Vuosip\u00e4iv\u00e4 ",
L_VIEWICONTIPS_ELM_2: "Avaamaton kansio ",
L_VIEWICONTIPS_ELM_20: "Teksti ",
L_VIEWICONTIPS_ELM_200: "Peruutettu tapaaminen ",
L_VIEWICONTIPS_ELM_201: "Valmis teht\u00e4v\u00e4 ",
L_VIEWICONTIPS_ELM_202: "Hyv\u00e4ksytty ",
L_VIEWICONTIPS_ELM_203: "Hyl\u00e4tty ",
L_VIEWICONTIPS_ELM_204: "Eritt\u00e4in t\u00e4rke\u00e4 ",
L_VIEWICONTIPS_ELM_205: "Tapaaminen ",
L_VIEWICONTIPS_ELM_206: "Yksityinen kutsu ",
L_VIEWICONTIPS_ELM_207: "Vitsihymi\u00f6 ",
L_VIEWICONTIPS_ELM_208: "Luottamuksellinen-hymi\u00f6 ",
L_VIEWICONTIPS_ELM_209: "Yksityinen-hymi\u00f6 ",
L_VIEWICONTIPS_ELM_21: "Useita asiakirjoja ",
L_VIEWICONTIPS_ELM_210: "Hyv\u00e4ksytty kutsu ",
L_VIEWICONTIPS_ELM_211: "Luettu viesti ",
L_VIEWICONTIPS_ELM_212: "Uusi kutsu ",
L_VIEWICONTIPS_ELM_22: "Kaksi asiakirjaa ",
L_VIEWICONTIPS_ELM_23: "Uutiset ",
L_VIEWICONTIPS_ELM_24: "Punainen kirja ",
L_VIEWICONTIPS_ELM_25: "Osoitekirja ",
L_VIEWICONTIPS_ELM_26: "Avoin kirja ",
L_VIEWICONTIPS_ELM_27: "Suljettu kirja ",
L_VIEWICONTIPS_ELM_28: "Valkoinen kirja ",
L_VIEWICONTIPS_ELM_29: "Revitty keltainen sivu ",
L_VIEWICONTIPS_ELM_3: "Henkil\u00f6 ",
L_VIEWICONTIPS_ELM_30: "Revitty sininen sivu ",
L_VIEWICONTIPS_ELM_31: "Palava hehkulamppu ",
L_VIEWICONTIPS_ELM_32: "Pime\u00e4 hehkulamppu ",
L_VIEWICONTIPS_ELM_33: "P\u00e4ivit\u00e4 ",
L_VIEWICONTIPS_ELM_34: "Asiakirjahaku ",
L_VIEWICONTIPS_ELM_35: "Asiakirjahaku valmis ",
L_VIEWICONTIPS_ELM_36: "Asiakirja hyv\u00e4ksytt\u00e4v\u00e4 ",
L_VIEWICONTIPS_ELM_37: "Asiakirja valmis ",
L_VIEWICONTIPS_ELM_38: "Asiakirjan ongelma ",
L_VIEWICONTIPS_ELM_39: "Asiakirjan kysymys ",
L_VIEWICONTIPS_ELM_4: "Ryhm\u00e4 ",
L_VIEWICONTIPS_ELM_40: "Asiakirjan valoitus ",
L_VIEWICONTIPS_ELM_41: "Asiakirja keltainen ",
L_VIEWICONTIPS_ELM_42: "Vastaus keltainen asiakirja ",
L_VIEWICONTIPS_ELM_43: "Vastaus sininen asiakirja ",
L_VIEWICONTIPS_ELM_44: "Puhelin ",
L_VIEWICONTIPS_ELM_45: "Aktiivinen puhelin ",
L_VIEWICONTIPS_ELM_46: "Tietokonep\u00e4\u00e4te ",
L_VIEWICONTIPS_ELM_47: "Faksi ",
L_VIEWICONTIPS_ELM_48: "CD-ROM ",
L_VIEWICONTIPS_ELM_49: "Levyke ",
L_VIEWICONTIPS_ELM_5: "Liite ",
L_VIEWICONTIPS_ELM_50: "Levyke ",
L_VIEWICONTIPS_ELM_51: "Kiintolevyasema ",
L_VIEWICONTIPS_ELM_52: "Verkko ",
L_VIEWICONTIPS_ELM_53: "Tietokone ",
L_VIEWICONTIPS_ELM_54: "Palvelin ",
L_VIEWICONTIPS_ELM_55: "Yhteys ",
L_VIEWICONTIPS_ELM_56: "Etsi ",
L_VIEWICONTIPS_ELM_57: "Kirjoita ",
L_VIEWICONTIPS_ELM_58: "Vedos ",
L_VIEWICONTIPS_ELM_59: "Valuutta ",
L_VIEWICONTIPS_ELM_6: "Punottu ",
L_VIEWICONTIPS_ELM_60: "Kolikot ",
L_VIEWICONTIPS_ELM_61: "Avain ",
L_VIEWICONTIPS_ELM_62: "Lukko ",
L_VIEWICONTIPS_ELM_63: "Kalenteri ",
L_VIEWICONTIPS_ELM_64: "Kello ",
L_VIEWICONTIPS_ELM_65: "H\u00e4lytys ",
L_VIEWICONTIPS_ELM_66: "Lent\u00e4minen ",
L_VIEWICONTIPS_ELM_67: "Satelliitti ",
L_VIEWICONTIPS_ELM_68: "Salkku ",
L_VIEWICONTIPS_ELM_69: "Koti ",
L_VIEWICONTIPS_ELM_7: "El\u00e4in ",
L_VIEWICONTIPS_ELM_70: "Maapallo ",
L_VIEWICONTIPS_ELM_71: "Terveys ",
L_VIEWICONTIPS_ELM_72: "Talous ",
L_VIEWICONTIPS_ELM_73: "Kuljetus ",
L_VIEWICONTIPS_ELM_74: "Kemia ",
L_VIEWICONTIPS_ELM_75: "Teollisuus ",
L_VIEWICONTIPS_ELM_76: "Apuohjelmat ",
L_VIEWICONTIPS_ELM_77: "Televiestint\u00e4 ",
L_VIEWICONTIPS_ELM_78: "Rakennus ",
L_VIEWICONTIPS_ELM_79: "Tiimalasi ",
L_VIEWICONTIPS_ELM_8: "Haku ",
L_VIEWICONTIPS_ELM_80: "Estetty ",
L_VIEWICONTIPS_ELM_81: "Hyl\u00e4tty ",
L_VIEWICONTIPS_ELM_82: "Valmis ",
L_VIEWICONTIPS_ELM_83: "Hyv\u00e4ksytt\u00e4v\u00e4 ",
L_VIEWICONTIPS_ELM_84: "Ei kelpaa ",
L_VIEWICONTIPS_ELM_85: "Iloinen ",
L_VIEWICONTIPS_ELM_86: "V\u00e4linpit\u00e4m\u00e4t\u00f6n ",
L_VIEWICONTIPS_ELM_87: "Surullinen ",
L_VIEWICONTIPS_ELM_88: "Haalea ",
L_VIEWICONTIPS_ELM_89: "L\u00e4mmin ",
L_VIEWICONTIPS_ELM_9: "Verkkotoiminto ",
L_VIEWICONTIPS_ELM_90: "Eritt\u00e4in kuuma ",
L_VIEWICONTIPS_ELM_91: "Pommi ",
L_VIEWICONTIPS_ELM_92: "Pys\u00e4htymismerkki ",
L_VIEWICONTIPS_ELM_93: "Pys\u00e4hdy ",
L_VIEWICONTIPS_ELM_94: "Varoitus ",
L_VIEWICONTIPS_ELM_95: "Siirry ",
L_VIEWICONTIPS_ELM_96: "Positiivinen ",
L_VIEWICONTIPS_ELM_97: "Negatiivinen ",
L_VIEWICONTIPS_ELM_98: "Punainen vinoneli\u00f6 ",
L_VIEWICONTIPS_ELM_99: "Vihre\u00e4 vinoneli\u00f6 ",
L_VIEWMAIL: "Posti"
})
