({
L_CAL_NAV_PREVIOUS: "Prej\u0161nji",
L_CAL_NAV_NEXT: "Naslednji",
L_CAL_NAV_MONTH: "Mesec",
L_CAL_HEADER_DAYS_WEEK: "Dnevi v tednu",
L_CAL_HEADER: "Glava koledarja",
L_CAL_HEADER_DAY: "Glava dneva %1",
L_CAL_EVENT_ALLDAY: "Celodnevni dogodek %1",
L_CAL_NOENTRY: "Ni vnosov",
L_CAL_GRID: "Mre\u017ea koledarja",
L_CAL_PICKER_POPUP: "Pojavno okno izbirnika datuma",
L_CAL_NAV_TIMESCALE_PREV_D: "Prej\u0161nji dan",
L_CAL_NAV_TIMESCALE_NEXT_D: "Naslednji dan",
L_CAL_NAV_TIMESCALE_PREV_T: "Prej\u0161nja dva dneva",
L_CAL_NAV_TIMESCALE_NEXT_T: "Naslednja dva dneva",
L_CAL_NAV_TIMESCALE_PREV_F: "Prej\u0161nji delovni teden",
L_CAL_NAV_TIMESCALE_NEXT_F: "Naslednji delovni teden",
L_CAL_NAV_TIMESCALE_PREV_W: "Prej\u0161nji teden",
L_CAL_NAV_TIMESCALE_NEXT_W: "Naslednji teden",
L_CAL_NAV_TIMESCALE_PREV_2: "Prej\u0161nja dva tedna",
L_CAL_NAV_TIMESCALE_NEXT_2: "Naslednja dva tedna",
L_CAL_NAV_TIMESCALE_PREV_M: "Prej\u0161nji mesec",
L_CAL_NAV_TIMESCALE_NEXT_M: "Naslednji mesec",
L_CAL_NAV_TIMESCALE_PREV_Y: "Prej\u0161nje leto",
L_CAL_NAV_TIMESCALE_NEXT_Y: "Naslednje leto"
})
