({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "dopoldne",
L_CAL_LAST_DAY: "Dan %1 - zadnji dan v letu",
L_CAL_LAST_MONTH: "Mesec %1 - zadnji mesec v letu",
L_CAL_LAST_WEEK: "Teden %1 - zadnji teden v letu",
L_CAL_LEFT_DAY: "Dan %1 - preostalih dni v letu: %2",
L_CAL_LEFT_DAYS: "Dan %1 - preostalih dni v letu: %2",
L_CAL_LEFT_MONTH: "Mesec %1 - %2 preostal mesec v letu",
L_CAL_LEFT_MONTHS: "Mesec %1 - preostalih mesecev v letu: %2",
L_CAL_LEFT_WEEK: "Teden %1 - %2 preostal teden v letu",
L_CAL_LEFT_WEEKS: "Teden %1 - preostalih tednov v letu: %2",
L_CHARDAY_FRI: "P",
L_CHARDAY_MON: "P",
L_CHARDAY_SAT: "S",
L_CHARDAY_SUN: "N",
L_CHARDAY_THU: "\u010c",
L_CHARDAY_TUE: "T",
L_CHARDAY_WED: "S",
L_NO_CAL_ENTRY_SELECTED: "Izbran ni bil noben vnos v koledar. Izberite vnos in poskusite znova.",
L_PM_SUFFIX: "popoldne",
L_SIDECALENDAR_NOENTRY: "Za %1 ni koledarskih vnosov."
})
