({
D_DTFMT_CALVIEW_LONG: "d|dddd|MMMM yyyy",
D_DTFMT_CALVIEW_SHORT: "d|ddd|MMM yyyy",
D_DTFMT_CALVIEW_TINY: "d|ddd|MMM",
L_AM_SUFFIX: "AM",
L_CAL_LAST_DAY: "Dag %1 - siste dag i \u00e5ret",
L_CAL_LAST_MONTH: "M\u00e5ned %1 - siste m\u00e5ned av \u00e5ret",
L_CAL_LAST_WEEK: "Uke %1 - siste uke av \u00e5ret",
L_CAL_LEFT_DAY: "Dag %1 - %2 dag igjen av \u00e5ret",
L_CAL_LEFT_DAYS: "Dag %1 - %2 dager igjen av \u00e5ret",
L_CAL_LEFT_MONTH: "M\u00e5ned %1 - %2 m\u00e5ned igjen av \u00e5ret",
L_CAL_LEFT_MONTHS: "M\u00e5ned %1 - %2 m\u00e5neder igjen av \u00e5ret",
L_CAL_LEFT_WEEK: "Uke %1 - %2 uke igjen av \u00e5ret",
L_CAL_LEFT_WEEKS: "Uke %1 - %2 uker igjen av \u00e5ret",
L_CHARDAY_FRI: "F",
L_CHARDAY_MON: "M",
L_CHARDAY_SAT: "L",
L_CHARDAY_SUN: "S",
L_CHARDAY_THU: "T",
L_CHARDAY_TUE: "T",
L_CHARDAY_WED: "O",
L_NO_CAL_ENTRY_SELECTED: "Ingen kalenderoppf\u00f8ringer er valgt. Velg en oppf\u00f8ring og pr\u00f8v p\u00e5 nytt.",
L_PM_SUFFIX: "PM",
L_SIDECALENDAR_NOENTRY: "Ingen kalenderoppf\u00f8ringer for %1."
})
